// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const addAgentGrant = `-- name: AddAgentGrant :exec
INSERT OR IGNORE INTO agent_grants (agent_id, permission, scope) VALUES (?, ?, ?)
`

type AddAgentGrantParams struct {
	AgentID    string `json:"agent_id"`
	Permission string `json:"permission"`
	Scope      string `json:"scope"`
}

func (q *Queries) AddAgentGrant(ctx context.Context, arg AddAgentGrantParams) error {
	_, err := q.db.ExecContext(ctx, addAgentGrant, arg.AgentID, arg.Permission, arg.Scope)
	return err
}

const countActiveAgents = `-- name: CountActiveAgents :one
SELECT COUNT(*) FROM agents WHERE status = 'active'
`

func (q *Queries) CountActiveAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, status, default_author_id, created_by_user_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	Status          string         `json:"status"`
	DefaultAuthorID sql.NullString `json:"default_author_id"`
	CreatedByUserID sql.NullString `json:"created_by_user_id"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.DefaultAuthorID,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createAgentToken = `-- name: CreateAgentToken :exec
INSERT INTO agent_tokens (id, agent_id, token_hash, token_prefix, label, created_at, expires_at, last_used_at, revoked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentTokenParams struct {
	ID          string        `json:"id"`
	AgentID     string        `json:"agent_id"`
	TokenHash   string        `json:"token_hash"`
	TokenPrefix string        `json:"token_prefix"`
	Label       string        `json:"label"`
	CreatedAt   int64         `json:"created_at"`
	ExpiresAt   sql.NullInt64 `json:"expires_at"`
	LastUsedAt  sql.NullInt64 `json:"last_used_at"`
	RevokedAt   sql.NullInt64 `json:"revoked_at"`
}

func (q *Queries) CreateAgentToken(ctx context.Context, arg CreateAgentTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAgentToken,
		arg.ID,
		arg.AgentID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Label,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	return err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const deleteAgentGrants = `-- name: DeleteAgentGrants :exec
DELETE FROM agent_grants WHERE agent_id = ?
`

func (q *Queries) DeleteAgentGrants(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentGrants, agentID)
	return err
}

const deleteAgentTokensByAgent = `-- name: DeleteAgentTokensByAgent :exec
DELETE FROM agent_tokens WHERE agent_id = ?
`

func (q *Queries) DeleteAgentTokensByAgent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deleteAgentTokensByAgent, agentID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, status, default_author_id, created_by_user_id, created_at, updated_at FROM agents WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.DefaultAuthorID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentToken = `-- name: GetAgentToken :one
SELECT id, agent_id, token_hash, token_prefix, label, created_at, expires_at, last_used_at, revoked_at FROM agent_tokens WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgentToken(ctx context.Context, id string) (AgentToken, error) {
	row := q.db.QueryRowContext(ctx, getAgentToken, id)
	var i AgentToken
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Label,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAgentGrants = `-- name: ListAgentGrants :many
SELECT agent_id, permission, scope FROM agent_grants WHERE agent_id = ? ORDER BY permission, scope
`

func (q *Queries) ListAgentGrants(ctx context.Context, agentID string) ([]AgentGrant, error) {
	rows, err := q.db.QueryContext(ctx, listAgentGrants, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentGrant{}
	for rows.Next() {
		var i AgentGrant
		if err := rows.Scan(&i.AgentID, &i.Permission, &i.Scope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTokens = `-- name: ListAgentTokens :many
SELECT id, agent_id, token_hash, token_prefix, label, created_at, expires_at, last_used_at, revoked_at FROM agent_tokens WHERE agent_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAgentTokens(ctx context.Context, agentID string) ([]AgentToken, error) {
	rows, err := q.db.QueryContext(ctx, listAgentTokens, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentToken{}
	for rows.Next() {
		var i AgentToken
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Label,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, status, default_author_id, created_by_user_id, created_at, updated_at FROM agents ORDER BY created_at DESC, name ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.DefaultAuthorID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupAgentByTokenHash = `-- name: LookupAgentByTokenHash :one
SELECT
    a.id as agent_id, a.name as agent_name, a.status as agent_status, a.default_author_id,
    t.id as token_id, t.token_hash, t.token_prefix, t.label, t.expires_at, t.revoked_at, t.last_used_at
FROM agent_tokens t
JOIN agents a ON a.id = t.agent_id
WHERE t.token_hash = ?
LIMIT 1
`

type LookupAgentByTokenHashRow struct {
	AgentID         string         `json:"agent_id"`
	AgentName       string         `json:"agent_name"`
	AgentStatus     string         `json:"agent_status"`
	DefaultAuthorID sql.NullString `json:"default_author_id"`
	TokenID         string         `json:"token_id"`
	TokenHash       string         `json:"token_hash"`
	TokenPrefix     string         `json:"token_prefix"`
	Label           string         `json:"label"`
	ExpiresAt       sql.NullInt64  `json:"expires_at"`
	RevokedAt       sql.NullInt64  `json:"revoked_at"`
	LastUsedAt      sql.NullInt64  `json:"last_used_at"`
}

func (q *Queries) LookupAgentByTokenHash(ctx context.Context, tokenHash string) (LookupAgentByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, lookupAgentByTokenHash, tokenHash)
	var i LookupAgentByTokenHashRow
	err := row.Scan(
		&i.AgentID,
		&i.AgentName,
		&i.AgentStatus,
		&i.DefaultAuthorID,
		&i.TokenID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Label,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const removeAgentGrant = `-- name: RemoveAgentGrant :exec
DELETE FROM agent_grants WHERE agent_id = ? AND permission = ? AND scope = ?
`

type RemoveAgentGrantParams struct {
	AgentID    string `json:"agent_id"`
	Permission string `json:"permission"`
	Scope      string `json:"scope"`
}

func (q *Queries) RemoveAgentGrant(ctx context.Context, arg RemoveAgentGrantParams) error {
	_, err := q.db.ExecContext(ctx, removeAgentGrant, arg.AgentID, arg.Permission, arg.Scope)
	return err
}

const revokeAgentToken = `-- name: RevokeAgentToken :exec
UPDATE agent_tokens SET revoked_at = ? WHERE id = ?
`

type RevokeAgentTokenParams struct {
	RevokedAt sql.NullInt64 `json:"revoked_at"`
	ID        string        `json:"id"`
}

func (q *Queries) RevokeAgentToken(ctx context.Context, arg RevokeAgentTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeAgentToken, arg.RevokedAt, arg.ID)
	return err
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE agents SET name = ?, default_author_id = ?, updated_at = ? WHERE id = ?
`

type UpdateAgentParams struct {
	Name            string         `json:"name"`
	DefaultAuthorID sql.NullString `json:"default_author_id"`
	UpdatedAt       int64          `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.ExecContext(ctx, updateAgent,
		arg.Name,
		arg.DefaultAuthorID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateAgentStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateAgentTokenLastUsed = `-- name: UpdateAgentTokenLastUsed :exec
UPDATE agent_tokens SET last_used_at = ? WHERE id = ? AND (last_used_at IS NULL OR ? - last_used_at > 300)
`

type UpdateAgentTokenLastUsedParams struct {
	LastUsedAt   sql.NullInt64 `json:"last_used_at"`
	ID           string        `json:"id"`
	LastUsedAt_2 sql.NullInt64 `json:"last_used_at_2"`
}

func (q *Queries) UpdateAgentTokenLastUsed(ctx context.Context, arg UpdateAgentTokenLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentTokenLastUsed, arg.LastUsedAt, arg.ID, arg.LastUsedAt_2)
	return err
}
