// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAllAnalyticsDimensionDaily = `-- name: DeleteAllAnalyticsDimensionDaily :exec
DELETE FROM analytics_dimension_daily
`

func (q *Queries) DeleteAllAnalyticsDimensionDaily(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAnalyticsDimensionDaily)
	return err
}

const deleteAllAnalyticsPageDaily = `-- name: DeleteAllAnalyticsPageDaily :exec
DELETE FROM analytics_page_daily
`

func (q *Queries) DeleteAllAnalyticsPageDaily(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAnalyticsPageDaily)
	return err
}

const deleteAllAnalyticsSiteHourly = `-- name: DeleteAllAnalyticsSiteHourly :exec
DELETE FROM analytics_site_hourly
`

func (q *Queries) DeleteAllAnalyticsSiteHourly(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAnalyticsSiteHourly)
	return err
}

const deleteAllAnalyticsTransitionDaily = `-- name: DeleteAllAnalyticsTransitionDaily :exec
DELETE FROM analytics_transition_daily
`

func (q *Queries) DeleteAllAnalyticsTransitionDaily(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAnalyticsTransitionDaily)
	return err
}

const deleteAnalyticsDimensionDailyBefore = `-- name: DeleteAnalyticsDimensionDailyBefore :exec
DELETE FROM analytics_dimension_daily WHERE day < ?
`

func (q *Queries) DeleteAnalyticsDimensionDailyBefore(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsDimensionDailyBefore, day)
	return err
}

const deleteAnalyticsPageDailyBefore = `-- name: DeleteAnalyticsPageDailyBefore :exec
DELETE FROM analytics_page_daily WHERE day < ?
`

func (q *Queries) DeleteAnalyticsPageDailyBefore(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsPageDailyBefore, day)
	return err
}

const deleteAnalyticsSiteHourlyBefore = `-- name: DeleteAnalyticsSiteHourlyBefore :exec
DELETE FROM analytics_site_hourly WHERE hour < ?
`

func (q *Queries) DeleteAnalyticsSiteHourlyBefore(ctx context.Context, hour int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsSiteHourlyBefore, hour)
	return err
}

const deleteAnalyticsTransitionDailyBefore = `-- name: DeleteAnalyticsTransitionDailyBefore :exec
DELETE FROM analytics_transition_daily WHERE day < ?
`

func (q *Queries) DeleteAnalyticsTransitionDailyBefore(ctx context.Context, day string) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsTransitionDailyBefore, day)
	return err
}

const existsAnalyticsDimensionValue = `-- name: ExistsAnalyticsDimensionValue :one
SELECT EXISTS(SELECT 1 FROM analytics_dimension_daily WHERE day = ? AND dimension = ? AND value = ?)
`

type ExistsAnalyticsDimensionValueParams struct {
	Day       string `json:"day"`
	Dimension string `json:"dimension"`
	Value     string `json:"value"`
}

// For cardinality protection: count distinct values per dimension per day already via GetAnalyticsDimensionCount, but we also need to check existence of value
func (q *Queries) ExistsAnalyticsDimensionValue(ctx context.Context, arg ExistsAnalyticsDimensionValueParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsAnalyticsDimensionValue, arg.Day, arg.Dimension, arg.Value)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAnalyticsDimensionCount = `-- name: GetAnalyticsDimensionCount :one
SELECT COUNT(*) FROM analytics_dimension_daily WHERE day = ? AND dimension = ?
`

type GetAnalyticsDimensionCountParams struct {
	Day       string `json:"day"`
	Dimension string `json:"dimension"`
}

func (q *Queries) GetAnalyticsDimensionCount(ctx context.Context, arg GetAnalyticsDimensionCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsDimensionCount, arg.Day, arg.Dimension)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnalyticsPageDaily = `-- name: GetAnalyticsPageDaily :one
SELECT day, resource_key, path, route_type, entry_id, revision_id, content_type_id, taxonomy_id, term_id,
       views, human_views, crawler_views, direct_views, internal_views, organic_search_views, organic_social_views, ai_referral_views, referral_views, campaign_views,
       cache_hits, cache_misses, response_count, response_bytes, response_duration_sum,
       latency_lt5, latency_lt20, latency_lt50, latency_lt100, latency_lt250, latency_lt1000, latency_gte1000
FROM analytics_page_daily
WHERE day = ? AND resource_key = ?
LIMIT 1
`

type GetAnalyticsPageDailyParams struct {
	Day         string `json:"day"`
	ResourceKey string `json:"resource_key"`
}

func (q *Queries) GetAnalyticsPageDaily(ctx context.Context, arg GetAnalyticsPageDailyParams) (AnalyticsPageDaily, error) {
	row := q.db.QueryRowContext(ctx, getAnalyticsPageDaily, arg.Day, arg.ResourceKey)
	var i AnalyticsPageDaily
	err := row.Scan(
		&i.Day,
		&i.ResourceKey,
		&i.Path,
		&i.RouteType,
		&i.EntryID,
		&i.RevisionID,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
		&i.Views,
		&i.HumanViews,
		&i.CrawlerViews,
		&i.DirectViews,
		&i.InternalViews,
		&i.OrganicSearchViews,
		&i.OrganicSocialViews,
		&i.AiReferralViews,
		&i.ReferralViews,
		&i.CampaignViews,
		&i.CacheHits,
		&i.CacheMisses,
		&i.ResponseCount,
		&i.ResponseBytes,
		&i.ResponseDurationSum,
		&i.LatencyLt5,
		&i.LatencyLt20,
		&i.LatencyLt50,
		&i.LatencyLt100,
		&i.LatencyLt250,
		&i.LatencyLt1000,
		&i.LatencyGte1000,
	)
	return i, err
}

const listAnalyticsDimensionDaily = `-- name: ListAnalyticsDimensionDaily :many
SELECT day, dimension, value, count
FROM analytics_dimension_daily
WHERE day >= ? AND day <= ? AND dimension = ?
ORDER BY count DESC
LIMIT ?
`

type ListAnalyticsDimensionDailyParams struct {
	Day       string `json:"day"`
	Day_2     string `json:"day_2"`
	Dimension string `json:"dimension"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListAnalyticsDimensionDaily(ctx context.Context, arg ListAnalyticsDimensionDailyParams) ([]AnalyticsDimensionDaily, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticsDimensionDaily,
		arg.Day,
		arg.Day_2,
		arg.Dimension,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDimensionDaily{}
	for rows.Next() {
		var i AnalyticsDimensionDaily
		if err := rows.Scan(
			&i.Day,
			&i.Dimension,
			&i.Value,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsDimensionValues = `-- name: ListAnalyticsDimensionValues :many
SELECT value FROM analytics_dimension_daily WHERE day = ? AND dimension = ?
`

type ListAnalyticsDimensionValuesParams struct {
	Day       string `json:"day"`
	Dimension string `json:"dimension"`
}

func (q *Queries) ListAnalyticsDimensionValues(ctx context.Context, arg ListAnalyticsDimensionValuesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticsDimensionValues, arg.Day, arg.Dimension)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsPageDaily = `-- name: ListAnalyticsPageDaily :many
SELECT day, resource_key, path, route_type, entry_id, revision_id, content_type_id, taxonomy_id, term_id,
       views, human_views, crawler_views, direct_views, internal_views, organic_search_views, organic_social_views, ai_referral_views, referral_views, campaign_views,
       cache_hits, cache_misses, response_count, response_bytes, response_duration_sum,
       latency_lt5, latency_lt20, latency_lt50, latency_lt100, latency_lt250, latency_lt1000, latency_gte1000
FROM analytics_page_daily
WHERE day >= ? AND day <= ?
ORDER BY views DESC
LIMIT ? OFFSET ?
`

type ListAnalyticsPageDailyParams struct {
	Day    string `json:"day"`
	Day_2  string `json:"day_2"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListAnalyticsPageDaily(ctx context.Context, arg ListAnalyticsPageDailyParams) ([]AnalyticsPageDaily, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticsPageDaily,
		arg.Day,
		arg.Day_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsPageDaily{}
	for rows.Next() {
		var i AnalyticsPageDaily
		if err := rows.Scan(
			&i.Day,
			&i.ResourceKey,
			&i.Path,
			&i.RouteType,
			&i.EntryID,
			&i.RevisionID,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
			&i.Views,
			&i.HumanViews,
			&i.CrawlerViews,
			&i.DirectViews,
			&i.InternalViews,
			&i.OrganicSearchViews,
			&i.OrganicSocialViews,
			&i.AiReferralViews,
			&i.ReferralViews,
			&i.CampaignViews,
			&i.CacheHits,
			&i.CacheMisses,
			&i.ResponseCount,
			&i.ResponseBytes,
			&i.ResponseDurationSum,
			&i.LatencyLt5,
			&i.LatencyLt20,
			&i.LatencyLt50,
			&i.LatencyLt100,
			&i.LatencyLt250,
			&i.LatencyLt1000,
			&i.LatencyGte1000,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsPageDailyByEntry = `-- name: ListAnalyticsPageDailyByEntry :many
SELECT day, resource_key, path, route_type, entry_id, revision_id, content_type_id, taxonomy_id, term_id,
       views, human_views, crawler_views, direct_views, internal_views, organic_search_views, organic_social_views, ai_referral_views, referral_views, campaign_views,
       cache_hits, cache_misses, response_count, response_bytes, response_duration_sum,
       latency_lt5, latency_lt20, latency_lt50, latency_lt100, latency_lt250, latency_lt1000, latency_gte1000
FROM analytics_page_daily
WHERE entry_id = ? AND day >= ? AND day <= ?
ORDER BY day ASC
`

type ListAnalyticsPageDailyByEntryParams struct {
	EntryID sql.NullString `json:"entry_id"`
	Day     string         `json:"day"`
	Day_2   string         `json:"day_2"`
}

func (q *Queries) ListAnalyticsPageDailyByEntry(ctx context.Context, arg ListAnalyticsPageDailyByEntryParams) ([]AnalyticsPageDaily, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticsPageDailyByEntry, arg.EntryID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsPageDaily{}
	for rows.Next() {
		var i AnalyticsPageDaily
		if err := rows.Scan(
			&i.Day,
			&i.ResourceKey,
			&i.Path,
			&i.RouteType,
			&i.EntryID,
			&i.RevisionID,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
			&i.Views,
			&i.HumanViews,
			&i.CrawlerViews,
			&i.DirectViews,
			&i.InternalViews,
			&i.OrganicSearchViews,
			&i.OrganicSocialViews,
			&i.AiReferralViews,
			&i.ReferralViews,
			&i.CampaignViews,
			&i.CacheHits,
			&i.CacheMisses,
			&i.ResponseCount,
			&i.ResponseBytes,
			&i.ResponseDurationSum,
			&i.LatencyLt5,
			&i.LatencyLt20,
			&i.LatencyLt50,
			&i.LatencyLt100,
			&i.LatencyLt250,
			&i.LatencyLt1000,
			&i.LatencyGte1000,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsSiteHourly = `-- name: ListAnalyticsSiteHourly :many
SELECT hour, requests, views, human_views, crawler_views, speculative_requests, cache_hits, cache_misses, status_2xx, status_3xx, status_4xx, status_5xx, response_bytes, response_count, response_duration_sum, latency_lt5, latency_lt20, latency_lt50, latency_lt100, latency_lt250, latency_lt1000, latency_gte1000
FROM analytics_site_hourly
WHERE hour >= ? AND hour <= ?
ORDER BY hour ASC
`

type ListAnalyticsSiteHourlyParams struct {
	Hour   int64 `json:"hour"`
	Hour_2 int64 `json:"hour_2"`
}

func (q *Queries) ListAnalyticsSiteHourly(ctx context.Context, arg ListAnalyticsSiteHourlyParams) ([]AnalyticsSiteHourly, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticsSiteHourly, arg.Hour, arg.Hour_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsSiteHourly{}
	for rows.Next() {
		var i AnalyticsSiteHourly
		if err := rows.Scan(
			&i.Hour,
			&i.Requests,
			&i.Views,
			&i.HumanViews,
			&i.CrawlerViews,
			&i.SpeculativeRequests,
			&i.CacheHits,
			&i.CacheMisses,
			&i.Status2xx,
			&i.Status3xx,
			&i.Status4xx,
			&i.Status5xx,
			&i.ResponseBytes,
			&i.ResponseCount,
			&i.ResponseDurationSum,
			&i.LatencyLt5,
			&i.LatencyLt20,
			&i.LatencyLt50,
			&i.LatencyLt100,
			&i.LatencyLt250,
			&i.LatencyLt1000,
			&i.LatencyGte1000,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsTransitions = `-- name: ListAnalyticsTransitions :many
SELECT day, from_resource_key, to_resource_key, from_path, to_path, count
FROM analytics_transition_daily
WHERE day >= ? AND day <= ?
ORDER BY count DESC
LIMIT ?
`

type ListAnalyticsTransitionsParams struct {
	Day   string `json:"day"`
	Day_2 string `json:"day_2"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListAnalyticsTransitions(ctx context.Context, arg ListAnalyticsTransitionsParams) ([]AnalyticsTransitionDaily, error) {
	rows, err := q.db.QueryContext(ctx, listAnalyticsTransitions, arg.Day, arg.Day_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsTransitionDaily{}
	for rows.Next() {
		var i AnalyticsTransitionDaily
		if err := rows.Scan(
			&i.Day,
			&i.FromResourceKey,
			&i.ToResourceKey,
			&i.FromPath,
			&i.ToPath,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumAnalyticsPageDaily = `-- name: SumAnalyticsPageDaily :one
SELECT
    CAST(COALESCE(SUM(views),0) AS INTEGER) AS total_views,
    CAST(COALESCE(SUM(human_views),0) AS INTEGER) AS total_human,
    CAST(COALESCE(SUM(crawler_views),0) AS INTEGER) AS total_crawler,
    CAST(COALESCE(SUM(direct_views),0) AS INTEGER) AS total_direct,
    CAST(COALESCE(SUM(internal_views),0) AS INTEGER) AS total_internal,
    CAST(COALESCE(SUM(organic_search_views),0) AS INTEGER) AS total_search,
    CAST(COALESCE(SUM(organic_social_views),0) AS INTEGER) AS total_social,
    CAST(COALESCE(SUM(ai_referral_views),0) AS INTEGER) AS total_ai,
    CAST(COALESCE(SUM(referral_views),0) AS INTEGER) AS total_referral,
    CAST(COALESCE(SUM(campaign_views),0) AS INTEGER) AS total_campaign
FROM analytics_page_daily
WHERE day >= ? AND day <= ?
`

type SumAnalyticsPageDailyParams struct {
	Day   string `json:"day"`
	Day_2 string `json:"day_2"`
}

type SumAnalyticsPageDailyRow struct {
	TotalViews    int64 `json:"total_views"`
	TotalHuman    int64 `json:"total_human"`
	TotalCrawler  int64 `json:"total_crawler"`
	TotalDirect   int64 `json:"total_direct"`
	TotalInternal int64 `json:"total_internal"`
	TotalSearch   int64 `json:"total_search"`
	TotalSocial   int64 `json:"total_social"`
	TotalAi       int64 `json:"total_ai"`
	TotalReferral int64 `json:"total_referral"`
	TotalCampaign int64 `json:"total_campaign"`
}

func (q *Queries) SumAnalyticsPageDaily(ctx context.Context, arg SumAnalyticsPageDailyParams) (SumAnalyticsPageDailyRow, error) {
	row := q.db.QueryRowContext(ctx, sumAnalyticsPageDaily, arg.Day, arg.Day_2)
	var i SumAnalyticsPageDailyRow
	err := row.Scan(
		&i.TotalViews,
		&i.TotalHuman,
		&i.TotalCrawler,
		&i.TotalDirect,
		&i.TotalInternal,
		&i.TotalSearch,
		&i.TotalSocial,
		&i.TotalAi,
		&i.TotalReferral,
		&i.TotalCampaign,
	)
	return i, err
}

const sumAnalyticsSiteHourly = `-- name: SumAnalyticsSiteHourly :one
SELECT
    CAST(COALESCE(SUM(requests),0) AS INTEGER) AS total_requests,
    CAST(COALESCE(SUM(views),0) AS INTEGER) AS total_views,
    CAST(COALESCE(SUM(human_views),0) AS INTEGER) AS total_human,
    CAST(COALESCE(SUM(crawler_views),0) AS INTEGER) AS total_crawler,
    CAST(COALESCE(SUM(speculative_requests),0) AS INTEGER) AS total_speculative,
    CAST(COALESCE(SUM(cache_hits),0) AS INTEGER) AS total_hits,
    CAST(COALESCE(SUM(cache_misses),0) AS INTEGER) AS total_misses,
    CAST(COALESCE(SUM(status_2xx),0) AS INTEGER) AS total_2xx,
    CAST(COALESCE(SUM(status_3xx),0) AS INTEGER) AS total_3xx,
    CAST(COALESCE(SUM(status_4xx),0) AS INTEGER) AS total_4xx,
    CAST(COALESCE(SUM(status_5xx),0) AS INTEGER) AS total_5xx,
    CAST(COALESCE(SUM(response_bytes),0) AS INTEGER) AS total_bytes,
    CAST(COALESCE(SUM(response_count),0) AS INTEGER) AS total_count,
    CAST(COALESCE(SUM(response_duration_sum),0) AS INTEGER) AS total_duration,
    CAST(COALESCE(SUM(latency_lt5),0) AS INTEGER) AS l_lt5,
    CAST(COALESCE(SUM(latency_lt20),0) AS INTEGER) AS l_lt20,
    CAST(COALESCE(SUM(latency_lt50),0) AS INTEGER) AS l_lt50,
    CAST(COALESCE(SUM(latency_lt100),0) AS INTEGER) AS l_lt100,
    CAST(COALESCE(SUM(latency_lt250),0) AS INTEGER) AS l_lt250,
    CAST(COALESCE(SUM(latency_lt1000),0) AS INTEGER) AS l_lt1000,
    CAST(COALESCE(SUM(latency_gte1000),0) AS INTEGER) AS l_gte1000
FROM analytics_site_hourly
WHERE hour >= ? AND hour <= ?
`

type SumAnalyticsSiteHourlyParams struct {
	Hour   int64 `json:"hour"`
	Hour_2 int64 `json:"hour_2"`
}

type SumAnalyticsSiteHourlyRow struct {
	TotalRequests    int64 `json:"total_requests"`
	TotalViews       int64 `json:"total_views"`
	TotalHuman       int64 `json:"total_human"`
	TotalCrawler     int64 `json:"total_crawler"`
	TotalSpeculative int64 `json:"total_speculative"`
	TotalHits        int64 `json:"total_hits"`
	TotalMisses      int64 `json:"total_misses"`
	Total2xx         int64 `json:"total_2xx"`
	Total3xx         int64 `json:"total_3xx"`
	Total4xx         int64 `json:"total_4xx"`
	Total5xx         int64 `json:"total_5xx"`
	TotalBytes       int64 `json:"total_bytes"`
	TotalCount       int64 `json:"total_count"`
	TotalDuration    int64 `json:"total_duration"`
	LLt5             int64 `json:"l_lt5"`
	LLt20            int64 `json:"l_lt20"`
	LLt50            int64 `json:"l_lt50"`
	LLt100           int64 `json:"l_lt100"`
	LLt250           int64 `json:"l_lt250"`
	LLt1000          int64 `json:"l_lt1000"`
	LGte1000         int64 `json:"l_gte1000"`
}

// Aggregates for overview: site hourly sum
func (q *Queries) SumAnalyticsSiteHourly(ctx context.Context, arg SumAnalyticsSiteHourlyParams) (SumAnalyticsSiteHourlyRow, error) {
	row := q.db.QueryRowContext(ctx, sumAnalyticsSiteHourly, arg.Hour, arg.Hour_2)
	var i SumAnalyticsSiteHourlyRow
	err := row.Scan(
		&i.TotalRequests,
		&i.TotalViews,
		&i.TotalHuman,
		&i.TotalCrawler,
		&i.TotalSpeculative,
		&i.TotalHits,
		&i.TotalMisses,
		&i.Total2xx,
		&i.Total3xx,
		&i.Total4xx,
		&i.Total5xx,
		&i.TotalBytes,
		&i.TotalCount,
		&i.TotalDuration,
		&i.LLt5,
		&i.LLt20,
		&i.LLt50,
		&i.LLt100,
		&i.LLt250,
		&i.LLt1000,
		&i.LGte1000,
	)
	return i, err
}

const upsertAnalyticsDimensionDaily = `-- name: UpsertAnalyticsDimensionDaily :exec
INSERT INTO analytics_dimension_daily (day, dimension, value, count)
VALUES (?, ?, ?, ?)
ON CONFLICT(day, dimension, value) DO UPDATE SET count = analytics_dimension_daily.count + excluded.count
`

type UpsertAnalyticsDimensionDailyParams struct {
	Day       string `json:"day"`
	Dimension string `json:"dimension"`
	Value     string `json:"value"`
	Count     int64  `json:"count"`
}

// Dimension upsert
func (q *Queries) UpsertAnalyticsDimensionDaily(ctx context.Context, arg UpsertAnalyticsDimensionDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnalyticsDimensionDaily,
		arg.Day,
		arg.Dimension,
		arg.Value,
		arg.Count,
	)
	return err
}

const upsertAnalyticsPageDaily = `-- name: UpsertAnalyticsPageDaily :exec
INSERT INTO analytics_page_daily (
    day, resource_key, path, route_type, entry_id, revision_id, content_type_id, taxonomy_id, term_id,
    views, human_views, crawler_views,
    direct_views, internal_views, organic_search_views, organic_social_views, ai_referral_views, referral_views, campaign_views,
    cache_hits, cache_misses, response_count, response_bytes, response_duration_sum,
    latency_lt5, latency_lt20, latency_lt50, latency_lt100, latency_lt250, latency_lt1000, latency_gte1000
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(day, resource_key) DO UPDATE SET
    path = excluded.path,
    route_type = excluded.route_type,
    entry_id = COALESCE(excluded.entry_id, analytics_page_daily.entry_id),
    revision_id = COALESCE(excluded.revision_id, analytics_page_daily.revision_id),
    content_type_id = COALESCE(excluded.content_type_id, analytics_page_daily.content_type_id),
    taxonomy_id = COALESCE(excluded.taxonomy_id, analytics_page_daily.taxonomy_id),
    term_id = COALESCE(excluded.term_id, analytics_page_daily.term_id),
    views = analytics_page_daily.views + excluded.views,
    human_views = analytics_page_daily.human_views + excluded.human_views,
    crawler_views = analytics_page_daily.crawler_views + excluded.crawler_views,
    direct_views = analytics_page_daily.direct_views + excluded.direct_views,
    internal_views = analytics_page_daily.internal_views + excluded.internal_views,
    organic_search_views = analytics_page_daily.organic_search_views + excluded.organic_search_views,
    organic_social_views = analytics_page_daily.organic_social_views + excluded.organic_social_views,
    ai_referral_views = analytics_page_daily.ai_referral_views + excluded.ai_referral_views,
    referral_views = analytics_page_daily.referral_views + excluded.referral_views,
    campaign_views = analytics_page_daily.campaign_views + excluded.campaign_views,
    cache_hits = analytics_page_daily.cache_hits + excluded.cache_hits,
    cache_misses = analytics_page_daily.cache_misses + excluded.cache_misses,
    response_count = analytics_page_daily.response_count + excluded.response_count,
    response_bytes = analytics_page_daily.response_bytes + excluded.response_bytes,
    response_duration_sum = analytics_page_daily.response_duration_sum + excluded.response_duration_sum,
    latency_lt5 = analytics_page_daily.latency_lt5 + excluded.latency_lt5,
    latency_lt20 = analytics_page_daily.latency_lt20 + excluded.latency_lt20,
    latency_lt50 = analytics_page_daily.latency_lt50 + excluded.latency_lt50,
    latency_lt100 = analytics_page_daily.latency_lt100 + excluded.latency_lt100,
    latency_lt250 = analytics_page_daily.latency_lt250 + excluded.latency_lt250,
    latency_lt1000 = analytics_page_daily.latency_lt1000 + excluded.latency_lt1000,
    latency_gte1000 = analytics_page_daily.latency_gte1000 + excluded.latency_gte1000
`

type UpsertAnalyticsPageDailyParams struct {
	Day                 string         `json:"day"`
	ResourceKey         string         `json:"resource_key"`
	Path                string         `json:"path"`
	RouteType           string         `json:"route_type"`
	EntryID             sql.NullString `json:"entry_id"`
	RevisionID          sql.NullString `json:"revision_id"`
	ContentTypeID       sql.NullString `json:"content_type_id"`
	TaxonomyID          sql.NullString `json:"taxonomy_id"`
	TermID              sql.NullString `json:"term_id"`
	Views               int64          `json:"views"`
	HumanViews          int64          `json:"human_views"`
	CrawlerViews        int64          `json:"crawler_views"`
	DirectViews         int64          `json:"direct_views"`
	InternalViews       int64          `json:"internal_views"`
	OrganicSearchViews  int64          `json:"organic_search_views"`
	OrganicSocialViews  int64          `json:"organic_social_views"`
	AiReferralViews     int64          `json:"ai_referral_views"`
	ReferralViews       int64          `json:"referral_views"`
	CampaignViews       int64          `json:"campaign_views"`
	CacheHits           int64          `json:"cache_hits"`
	CacheMisses         int64          `json:"cache_misses"`
	ResponseCount       int64          `json:"response_count"`
	ResponseBytes       int64          `json:"response_bytes"`
	ResponseDurationSum int64          `json:"response_duration_sum"`
	LatencyLt5          int64          `json:"latency_lt5"`
	LatencyLt20         int64          `json:"latency_lt20"`
	LatencyLt50         int64          `json:"latency_lt50"`
	LatencyLt100        int64          `json:"latency_lt100"`
	LatencyLt250        int64          `json:"latency_lt250"`
	LatencyLt1000       int64          `json:"latency_lt1000"`
	LatencyGte1000      int64          `json:"latency_gte1000"`
}

// Page daily upsert
func (q *Queries) UpsertAnalyticsPageDaily(ctx context.Context, arg UpsertAnalyticsPageDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnalyticsPageDaily,
		arg.Day,
		arg.ResourceKey,
		arg.Path,
		arg.RouteType,
		arg.EntryID,
		arg.RevisionID,
		arg.ContentTypeID,
		arg.TaxonomyID,
		arg.TermID,
		arg.Views,
		arg.HumanViews,
		arg.CrawlerViews,
		arg.DirectViews,
		arg.InternalViews,
		arg.OrganicSearchViews,
		arg.OrganicSocialViews,
		arg.AiReferralViews,
		arg.ReferralViews,
		arg.CampaignViews,
		arg.CacheHits,
		arg.CacheMisses,
		arg.ResponseCount,
		arg.ResponseBytes,
		arg.ResponseDurationSum,
		arg.LatencyLt5,
		arg.LatencyLt20,
		arg.LatencyLt50,
		arg.LatencyLt100,
		arg.LatencyLt250,
		arg.LatencyLt1000,
		arg.LatencyGte1000,
	)
	return err
}

const upsertAnalyticsSiteHourly = `-- name: UpsertAnalyticsSiteHourly :exec
INSERT INTO analytics_site_hourly (
    hour, requests, views, human_views, crawler_views, speculative_requests,
    cache_hits, cache_misses, status_2xx, status_3xx, status_4xx, status_5xx,
    response_bytes, response_count, response_duration_sum,
    latency_lt5, latency_lt20, latency_lt50, latency_lt100, latency_lt250, latency_lt1000, latency_gte1000
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(hour) DO UPDATE SET
    requests = analytics_site_hourly.requests + excluded.requests,
    views = analytics_site_hourly.views + excluded.views,
    human_views = analytics_site_hourly.human_views + excluded.human_views,
    crawler_views = analytics_site_hourly.crawler_views + excluded.crawler_views,
    speculative_requests = analytics_site_hourly.speculative_requests + excluded.speculative_requests,
    cache_hits = analytics_site_hourly.cache_hits + excluded.cache_hits,
    cache_misses = analytics_site_hourly.cache_misses + excluded.cache_misses,
    status_2xx = analytics_site_hourly.status_2xx + excluded.status_2xx,
    status_3xx = analytics_site_hourly.status_3xx + excluded.status_3xx,
    status_4xx = analytics_site_hourly.status_4xx + excluded.status_4xx,
    status_5xx = analytics_site_hourly.status_5xx + excluded.status_5xx,
    response_bytes = analytics_site_hourly.response_bytes + excluded.response_bytes,
    response_count = analytics_site_hourly.response_count + excluded.response_count,
    response_duration_sum = analytics_site_hourly.response_duration_sum + excluded.response_duration_sum,
    latency_lt5 = analytics_site_hourly.latency_lt5 + excluded.latency_lt5,
    latency_lt20 = analytics_site_hourly.latency_lt20 + excluded.latency_lt20,
    latency_lt50 = analytics_site_hourly.latency_lt50 + excluded.latency_lt50,
    latency_lt100 = analytics_site_hourly.latency_lt100 + excluded.latency_lt100,
    latency_lt250 = analytics_site_hourly.latency_lt250 + excluded.latency_lt250,
    latency_lt1000 = analytics_site_hourly.latency_lt1000 + excluded.latency_lt1000,
    latency_gte1000 = analytics_site_hourly.latency_gte1000 + excluded.latency_gte1000
`

type UpsertAnalyticsSiteHourlyParams struct {
	Hour                int64 `json:"hour"`
	Requests            int64 `json:"requests"`
	Views               int64 `json:"views"`
	HumanViews          int64 `json:"human_views"`
	CrawlerViews        int64 `json:"crawler_views"`
	SpeculativeRequests int64 `json:"speculative_requests"`
	CacheHits           int64 `json:"cache_hits"`
	CacheMisses         int64 `json:"cache_misses"`
	Status2xx           int64 `json:"status_2xx"`
	Status3xx           int64 `json:"status_3xx"`
	Status4xx           int64 `json:"status_4xx"`
	Status5xx           int64 `json:"status_5xx"`
	ResponseBytes       int64 `json:"response_bytes"`
	ResponseCount       int64 `json:"response_count"`
	ResponseDurationSum int64 `json:"response_duration_sum"`
	LatencyLt5          int64 `json:"latency_lt5"`
	LatencyLt20         int64 `json:"latency_lt20"`
	LatencyLt50         int64 `json:"latency_lt50"`
	LatencyLt100        int64 `json:"latency_lt100"`
	LatencyLt250        int64 `json:"latency_lt250"`
	LatencyLt1000       int64 `json:"latency_lt1000"`
	LatencyGte1000      int64 `json:"latency_gte1000"`
}

// Site hourly upsert
func (q *Queries) UpsertAnalyticsSiteHourly(ctx context.Context, arg UpsertAnalyticsSiteHourlyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnalyticsSiteHourly,
		arg.Hour,
		arg.Requests,
		arg.Views,
		arg.HumanViews,
		arg.CrawlerViews,
		arg.SpeculativeRequests,
		arg.CacheHits,
		arg.CacheMisses,
		arg.Status2xx,
		arg.Status3xx,
		arg.Status4xx,
		arg.Status5xx,
		arg.ResponseBytes,
		arg.ResponseCount,
		arg.ResponseDurationSum,
		arg.LatencyLt5,
		arg.LatencyLt20,
		arg.LatencyLt50,
		arg.LatencyLt100,
		arg.LatencyLt250,
		arg.LatencyLt1000,
		arg.LatencyGte1000,
	)
	return err
}

const upsertAnalyticsTransitionDaily = `-- name: UpsertAnalyticsTransitionDaily :exec
INSERT INTO analytics_transition_daily (day, from_resource_key, to_resource_key, from_path, to_path, count)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(day, from_resource_key, to_resource_key) DO UPDATE SET count = analytics_transition_daily.count + excluded.count, from_path = excluded.from_path, to_path = excluded.to_path
`

type UpsertAnalyticsTransitionDailyParams struct {
	Day             string `json:"day"`
	FromResourceKey string `json:"from_resource_key"`
	ToResourceKey   string `json:"to_resource_key"`
	FromPath        string `json:"from_path"`
	ToPath          string `json:"to_path"`
	Count           int64  `json:"count"`
}

// Transition upsert
func (q *Queries) UpsertAnalyticsTransitionDaily(ctx context.Context, arg UpsertAnalyticsTransitionDailyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnalyticsTransitionDaily,
		arg.Day,
		arg.FromResourceKey,
		arg.ToResourceKey,
		arg.FromPath,
		arg.ToPath,
		arg.Count,
	)
	return err
}
