// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (id, actor_kind, actor_id, transport, action, resource_type, resource_id, revision_id, metadata_json, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEventParams struct {
	ID           string         `json:"id"`
	ActorKind    string         `json:"actor_kind"`
	ActorID      sql.NullString `json:"actor_id"`
	Transport    string         `json:"transport"`
	Action       string         `json:"action"`
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	RevisionID   sql.NullString `json:"revision_id"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEvent,
		arg.ID,
		arg.ActorKind,
		arg.ActorID,
		arg.Transport,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.RevisionID,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, actor_kind, actor_id, transport, "action", resource_type, resource_id, revision_id, metadata_json, created_at FROM audit_events WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id string) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, getAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorKind,
		&i.ActorID,
		&i.Transport,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.RevisionID,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsByActor = `-- name: ListAuditEventsByActor :many
SELECT id, actor_kind, actor_id, transport, "action", resource_type, resource_id, revision_id, metadata_json, created_at FROM audit_events WHERE actor_kind = ? AND actor_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAuditEventsByActorParams struct {
	ActorKind string         `json:"actor_kind"`
	ActorID   sql.NullString `json:"actor_id"`
	Limit     int64          `json:"limit"`
	Offset    int64          `json:"offset"`
}

func (q *Queries) ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByActor,
		arg.ActorKind,
		arg.ActorID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorKind,
			&i.ActorID,
			&i.Transport,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RevisionID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByResource = `-- name: ListAuditEventsByResource :many
SELECT id, actor_kind, actor_id, transport, "action", resource_type, resource_id, revision_id, metadata_json, created_at FROM audit_events WHERE resource_type = ? AND resource_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAuditEventsByResourceParams struct {
	ResourceType string         `json:"resource_type"`
	ResourceID   sql.NullString `json:"resource_id"`
	Limit        int64          `json:"limit"`
	Offset       int64          `json:"offset"`
}

func (q *Queries) ListAuditEventsByResource(ctx context.Context, arg ListAuditEventsByResourceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByResource,
		arg.ResourceType,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorKind,
			&i.ActorID,
			&i.Transport,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RevisionID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsForRevision = `-- name: ListAuditEventsForRevision :many
SELECT id, actor_kind, actor_id, transport, "action", resource_type, resource_id, revision_id, metadata_json, created_at FROM audit_events WHERE revision_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAuditEventsForRevision(ctx context.Context, revisionID sql.NullString) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsForRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorKind,
			&i.ActorID,
			&i.Transport,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RevisionID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAuditEvents = `-- name: RecentAuditEvents :many
SELECT id, actor_kind, actor_id, transport, "action", resource_type, resource_id, revision_id, metadata_json, created_at FROM audit_events ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type RecentAuditEventsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) RecentAuditEvents(ctx context.Context, arg RecentAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, recentAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorKind,
			&i.ActorID,
			&i.Transport,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RevisionID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
