// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package db

import (
	"context"
	"database/sql"
)

const createBlockDefinition = `-- name: CreateBlockDefinition :exec
INSERT INTO block_definitions (
    id, namespace, name, version, display_name, description, schema_json,
    renderer_type, template, styles, source, enabled, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBlockDefinitionParams struct {
	ID           string         `json:"id"`
	Namespace    string         `json:"namespace"`
	Name         string         `json:"name"`
	Version      int64          `json:"version"`
	DisplayName  string         `json:"display_name"`
	Description  sql.NullString `json:"description"`
	SchemaJson   string         `json:"schema_json"`
	RendererType string         `json:"renderer_type"`
	Template     sql.NullString `json:"template"`
	Styles       sql.NullString `json:"styles"`
	Source       string         `json:"source"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateBlockDefinition(ctx context.Context, arg CreateBlockDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, createBlockDefinition,
		arg.ID,
		arg.Namespace,
		arg.Name,
		arg.Version,
		arg.DisplayName,
		arg.Description,
		arg.SchemaJson,
		arg.RendererType,
		arg.Template,
		arg.Styles,
		arg.Source,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const disableBlockDefinition = `-- name: DisableBlockDefinition :exec
UPDATE block_definitions
SET enabled = 0, updated_at = ?
WHERE id = ?
`

type DisableBlockDefinitionParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) DisableBlockDefinition(ctx context.Context, arg DisableBlockDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, disableBlockDefinition, arg.UpdatedAt, arg.ID)
	return err
}

const getBlockDefinition = `-- name: GetBlockDefinition :one
SELECT id, namespace, name, version, display_name, description, schema_json, renderer_type, template, styles, source, enabled, created_at, updated_at
FROM block_definitions
WHERE namespace = ?
  AND name = ?
  AND version = ?
LIMIT 1
`

type GetBlockDefinitionParams struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
	Version   int64  `json:"version"`
}

func (q *Queries) GetBlockDefinition(ctx context.Context, arg GetBlockDefinitionParams) (BlockDefinition, error) {
	row := q.db.QueryRowContext(ctx, getBlockDefinition, arg.Namespace, arg.Name, arg.Version)
	var i BlockDefinition
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Name,
		&i.Version,
		&i.DisplayName,
		&i.Description,
		&i.SchemaJson,
		&i.RendererType,
		&i.Template,
		&i.Styles,
		&i.Source,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlockDefinitions = `-- name: ListBlockDefinitions :many
SELECT id, namespace, name, version, display_name, description, schema_json, renderer_type, template, styles, source, enabled, created_at, updated_at
FROM block_definitions
ORDER BY namespace, name, version
`

func (q *Queries) ListBlockDefinitions(ctx context.Context) ([]BlockDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listBlockDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockDefinition{}
	for rows.Next() {
		var i BlockDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Name,
			&i.Version,
			&i.DisplayName,
			&i.Description,
			&i.SchemaJson,
			&i.RendererType,
			&i.Template,
			&i.Styles,
			&i.Source,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
