// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"database/sql"
)

const countAllComments = `-- name: CountAllComments :one
SELECT COUNT(*) FROM comments
`

func (q *Queries) CountAllComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovedCommentsByEntry = `-- name: CountApprovedCommentsByEntry :one
SELECT COUNT(*) FROM comments WHERE entry_id = ? AND status = 'approved'
`

func (q *Queries) CountApprovedCommentsByEntry(ctx context.Context, entryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApprovedCommentsByEntry, entryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsByStatus = `-- name: CountCommentsByStatus :many
SELECT status, COUNT(*) as count FROM comments GROUP BY status
`

type CountCommentsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountCommentsByStatus(ctx context.Context) ([]CountCommentsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countCommentsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCommentsByStatusRow{}
	for rows.Next() {
		var i CountCommentsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCommentsFiltered = `-- name: CountCommentsFiltered :one
SELECT COUNT(*) FROM comments
WHERE (?1 IS NULL OR status = ?1)
  AND (?2 IS NULL OR author_name LIKE '%' || ?2 || '%' OR author_email LIKE '%' || ?2 || '%' OR body LIKE '%' || ?2 || '%')
  AND (?3 IS NULL OR entry_id = ?3)
`

type CountCommentsFilteredParams struct {
	Status  interface{} `json:"status"`
	Search  interface{} `json:"search"`
	EntryID interface{} `json:"entry_id"`
}

func (q *Queries) CountCommentsFiltered(ctx context.Context, arg CountCommentsFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsFiltered, arg.Status, arg.Search, arg.EntryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (id, entry_id, parent_id, status, author_name, author_email, author_url, user_id, body, created_at, updated_at, imported_source, imported_external_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID                 string         `json:"id"`
	EntryID            string         `json:"entry_id"`
	ParentID           sql.NullString `json:"parent_id"`
	Status             string         `json:"status"`
	AuthorName         string         `json:"author_name"`
	AuthorEmail        string         `json:"author_email"`
	AuthorUrl          string         `json:"author_url"`
	UserID             sql.NullString `json:"user_id"`
	Body               string         `json:"body"`
	CreatedAt          int64          `json:"created_at"`
	UpdatedAt          int64          `json:"updated_at"`
	ImportedSource     sql.NullString `json:"imported_source"`
	ImportedExternalID sql.NullString `json:"imported_external_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.EntryID,
		arg.ParentID,
		arg.Status,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorUrl,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ImportedSource,
		arg.ImportedExternalID,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, entry_id, parent_id, status, author_name, author_email, author_url, user_id, body, created_at, updated_at, imported_source, imported_external_id FROM comments WHERE id = ? LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.ParentID,
		&i.Status,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportedSource,
		&i.ImportedExternalID,
	)
	return i, err
}

const getCommentByImportID = `-- name: GetCommentByImportID :one
SELECT id, entry_id, parent_id, status, author_name, author_email, author_url, user_id, body, created_at, updated_at, imported_source, imported_external_id FROM comments WHERE imported_source = ? AND imported_external_id = ? LIMIT 1
`

type GetCommentByImportIDParams struct {
	ImportedSource     sql.NullString `json:"imported_source"`
	ImportedExternalID sql.NullString `json:"imported_external_id"`
}

func (q *Queries) GetCommentByImportID(ctx context.Context, arg GetCommentByImportIDParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByImportID, arg.ImportedSource, arg.ImportedExternalID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.ParentID,
		&i.Status,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportedSource,
		&i.ImportedExternalID,
	)
	return i, err
}

const listApprovedCommentsByEntry = `-- name: ListApprovedCommentsByEntry :many
SELECT id, entry_id, parent_id, status, author_name, author_email, author_url, user_id, body, created_at, updated_at, imported_source, imported_external_id FROM comments WHERE entry_id = ? AND status = 'approved' ORDER BY created_at ASC, id ASC LIMIT ? OFFSET ?
`

type ListApprovedCommentsByEntryParams struct {
	EntryID string `json:"entry_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListApprovedCommentsByEntry(ctx context.Context, arg ListApprovedCommentsByEntryParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listApprovedCommentsByEntry, arg.EntryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.ParentID,
			&i.Status,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportedSource,
			&i.ImportedExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByEntry = `-- name: ListCommentsByEntry :many
SELECT id, entry_id, parent_id, status, author_name, author_email, author_url, user_id, body, created_at, updated_at, imported_source, imported_external_id FROM comments WHERE entry_id = ? ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListCommentsByEntry(ctx context.Context, entryID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.ParentID,
			&i.Status,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportedSource,
			&i.ImportedExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsFiltered = `-- name: ListCommentsFiltered :many
SELECT id, entry_id, parent_id, status, author_name, author_email, author_url, user_id, body, created_at, updated_at, imported_source, imported_external_id FROM comments
WHERE (?1 IS NULL OR status = ?1)
  AND (?2 IS NULL OR author_name LIKE '%' || ?2 || '%' OR author_email LIKE '%' || ?2 || '%' OR body LIKE '%' || ?2 || '%')
  AND (?3 IS NULL OR entry_id = ?3)
ORDER BY created_at DESC, id DESC
LIMIT ?5 OFFSET ?4
`

type ListCommentsFilteredParams struct {
	Status  interface{} `json:"status"`
	Search  interface{} `json:"search"`
	EntryID interface{} `json:"entry_id"`
	Offset  int64       `json:"offset"`
	Limit   int64       `json:"limit"`
}

func (q *Queries) ListCommentsFiltered(ctx context.Context, arg ListCommentsFilteredParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsFiltered,
		arg.Status,
		arg.Search,
		arg.EntryID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.ParentID,
			&i.Status,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportedSource,
			&i.ImportedExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentFeaturedMedia = `-- name: SetCommentFeaturedMedia :exec
UPDATE entry_revisions SET featured_media_id = ? WHERE id = ?
`

type SetCommentFeaturedMediaParams struct {
	FeaturedMediaID sql.NullString `json:"featured_media_id"`
	ID              string         `json:"id"`
}

func (q *Queries) SetCommentFeaturedMedia(ctx context.Context, arg SetCommentFeaturedMediaParams) error {
	_, err := q.db.ExecContext(ctx, setCommentFeaturedMedia, arg.FeaturedMediaID, arg.ID)
	return err
}

const updateCommentParent = `-- name: UpdateCommentParent :exec
UPDATE comments SET parent_id = ?, updated_at = ? WHERE id = ?
`

type UpdateCommentParentParams struct {
	ParentID  sql.NullString `json:"parent_id"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateCommentParent(ctx context.Context, arg UpdateCommentParentParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const updateCommentStatus = `-- name: UpdateCommentStatus :exec
UPDATE comments SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateCommentStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
