// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_types.sql

package db

import (
	"context"
)

const createContentType = `-- name: CreateContentType :exec
INSERT INTO content_types (
    id, display_name, plural_name, hierarchical, public, config_json, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContentTypeParams struct {
	ID           string `json:"id"`
	DisplayName  string `json:"display_name"`
	PluralName   string `json:"plural_name"`
	Hierarchical int64  `json:"hierarchical"`
	Public       int64  `json:"public"`
	ConfigJson   string `json:"config_json"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateContentType(ctx context.Context, arg CreateContentTypeParams) error {
	_, err := q.db.ExecContext(ctx, createContentType,
		arg.ID,
		arg.DisplayName,
		arg.PluralName,
		arg.Hierarchical,
		arg.Public,
		arg.ConfigJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteContentType = `-- name: DeleteContentType :exec
DELETE FROM content_types
WHERE id = ?
`

func (q *Queries) DeleteContentType(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContentType, id)
	return err
}

const getContentType = `-- name: GetContentType :one
SELECT id, display_name, plural_name, hierarchical, public, config_json, created_at, updated_at, default_layout_template_id
FROM content_types
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetContentType(ctx context.Context, id string) (ContentType, error) {
	row := q.db.QueryRowContext(ctx, getContentType, id)
	var i ContentType
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PluralName,
		&i.Hierarchical,
		&i.Public,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLayoutTemplateID,
	)
	return i, err
}

const listContentTypes = `-- name: ListContentTypes :many
SELECT id, display_name, plural_name, hierarchical, public, config_json, created_at, updated_at, default_layout_template_id
FROM content_types
ORDER BY display_name
`

func (q *Queries) ListContentTypes(ctx context.Context) ([]ContentType, error) {
	rows, err := q.db.QueryContext(ctx, listContentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentType{}
	for rows.Next() {
		var i ContentType
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PluralName,
			&i.Hierarchical,
			&i.Public,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultLayoutTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentType = `-- name: UpdateContentType :exec
UPDATE content_types
SET display_name = ?, plural_name = ?, hierarchical = ?, public = ?, config_json = ?, updated_at = ?
WHERE id = ?
`

type UpdateContentTypeParams struct {
	DisplayName  string `json:"display_name"`
	PluralName   string `json:"plural_name"`
	Hierarchical int64  `json:"hierarchical"`
	Public       int64  `json:"public"`
	ConfigJson   string `json:"config_json"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateContentType,
		arg.DisplayName,
		arg.PluralName,
		arg.Hierarchical,
		arg.Public,
		arg.ConfigJson,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
