// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (
    id, content_type_id, slug, status, author_id, created_at, updated_at, published_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryParams struct {
	ID            string         `json:"id"`
	ContentTypeID string         `json:"content_type_id"`
	Slug          string         `json:"slug"`
	Status        string         `json:"status"`
	AuthorID      sql.NullString `json:"author_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	PublishedAt   sql.NullInt64  `json:"published_at"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.ID,
		arg.ContentTypeID,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at
FROM entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getEntryBySlug = `-- name: GetEntryBySlug :one
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at
FROM entries
WHERE content_type_id = ?
  AND slug = ?
LIMIT 1
`

type GetEntryBySlugParams struct {
	ContentTypeID string `json:"content_type_id"`
	Slug          string `json:"slug"`
}

func (q *Queries) GetEntryBySlug(ctx context.Context, arg GetEntryBySlugParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryBySlug, arg.ContentTypeID, arg.Slug)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listEntriesByContentType = `-- name: ListEntriesByContentType :many
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at
FROM entries
WHERE content_type_id = ?
  AND status = ?
ORDER BY published_at DESC, created_at DESC
LIMIT ? OFFSET ?
`

type ListEntriesByContentTypeParams struct {
	ContentTypeID string `json:"content_type_id"`
	Status        string `json:"status"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

func (q *Queries) ListEntriesByContentType(ctx context.Context, arg ListEntriesByContentTypeParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByContentType,
		arg.ContentTypeID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.Slug,
			&i.Status,
			&i.AuthorID,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPublishedRevision = `-- name: SetPublishedRevision :exec
UPDATE entries
SET published_revision_id = ?, status = 'active', published_at = ?, updated_at = ?
WHERE id = ?
`

type SetPublishedRevisionParams struct {
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	PublishedAt         sql.NullInt64  `json:"published_at"`
	UpdatedAt           int64          `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setPublishedRevision,
		arg.PublishedRevisionID,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET slug = ?, status = ?, author_id = ?, updated_at = ?, published_at = ?
WHERE id = ?
`

type UpdateEntryParams struct {
	Slug        string         `json:"slug"`
	Status      string         `json:"status"`
	AuthorID    sql.NullString `json:"author_id"`
	UpdatedAt   int64          `json:"updated_at"`
	PublishedAt sql.NullInt64  `json:"published_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}
