// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_revisions.sql

package db

import (
	"context"
	"database/sql"
)

const createEntryRevision = `-- name: CreateEntryRevision :exec
INSERT INTO entry_revisions (
    id, entry_id, revision_number, title, excerpt, document_json,
    seo_title, seo_description, canonical_url, featured_media_id, social_media_id,
    seo_robots_index, seo_robots_follow, schema_mode, layout_template_id, parent_entry_id, menu_order, created_by, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryRevisionParams struct {
	ID               string         `json:"id"`
	EntryID          string         `json:"entry_id"`
	RevisionNumber   int64          `json:"revision_number"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	DocumentJson     string         `json:"document_json"`
	SeoTitle         sql.NullString `json:"seo_title"`
	SeoDescription   sql.NullString `json:"seo_description"`
	CanonicalUrl     sql.NullString `json:"canonical_url"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	SocialMediaID    sql.NullString `json:"social_media_id"`
	SeoRobotsIndex   sql.NullInt64  `json:"seo_robots_index"`
	SeoRobotsFollow  sql.NullInt64  `json:"seo_robots_follow"`
	SchemaMode       string         `json:"schema_mode"`
	LayoutTemplateID sql.NullString `json:"layout_template_id"`
	ParentEntryID    sql.NullString `json:"parent_entry_id"`
	MenuOrder        int64          `json:"menu_order"`
	CreatedBy        sql.NullString `json:"created_by"`
	CreatedAt        int64          `json:"created_at"`
}

func (q *Queries) CreateEntryRevision(ctx context.Context, arg CreateEntryRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createEntryRevision,
		arg.ID,
		arg.EntryID,
		arg.RevisionNumber,
		arg.Title,
		arg.Excerpt,
		arg.DocumentJson,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.CanonicalUrl,
		arg.FeaturedMediaID,
		arg.SocialMediaID,
		arg.SeoRobotsIndex,
		arg.SeoRobotsFollow,
		arg.SchemaMode,
		arg.LayoutTemplateID,
		arg.ParentEntryID,
		arg.MenuOrder,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const getEntryRevision = `-- name: GetEntryRevision :one
SELECT id, entry_id, revision_number, title, excerpt, document_json, seo_title, seo_description, created_by, created_at, canonical_url, featured_media_id, social_media_id, seo_robots_index, seo_robots_follow, schema_mode, layout_template_id, parent_entry_id, menu_order
FROM entry_revisions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEntryRevision(ctx context.Context, id string) (EntryRevision, error) {
	row := q.db.QueryRowContext(ctx, getEntryRevision, id)
	var i EntryRevision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RevisionNumber,
		&i.Title,
		&i.Excerpt,
		&i.DocumentJson,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CanonicalUrl,
		&i.FeaturedMediaID,
		&i.SocialMediaID,
		&i.SeoRobotsIndex,
		&i.SeoRobotsFollow,
		&i.SchemaMode,
		&i.LayoutTemplateID,
		&i.ParentEntryID,
		&i.MenuOrder,
	)
	return i, err
}

const getLatestEntryRevision = `-- name: GetLatestEntryRevision :one
SELECT id, entry_id, revision_number, title, excerpt, document_json, seo_title, seo_description, created_by, created_at, canonical_url, featured_media_id, social_media_id, seo_robots_index, seo_robots_follow, schema_mode, layout_template_id, parent_entry_id, menu_order
FROM entry_revisions
WHERE entry_id = ?
ORDER BY revision_number DESC
LIMIT 1
`

func (q *Queries) GetLatestEntryRevision(ctx context.Context, entryID string) (EntryRevision, error) {
	row := q.db.QueryRowContext(ctx, getLatestEntryRevision, entryID)
	var i EntryRevision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RevisionNumber,
		&i.Title,
		&i.Excerpt,
		&i.DocumentJson,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CanonicalUrl,
		&i.FeaturedMediaID,
		&i.SocialMediaID,
		&i.SeoRobotsIndex,
		&i.SeoRobotsFollow,
		&i.SchemaMode,
		&i.LayoutTemplateID,
		&i.ParentEntryID,
		&i.MenuOrder,
	)
	return i, err
}

const listEntryRevisions = `-- name: ListEntryRevisions :many
SELECT id, entry_id, revision_number, title, excerpt, document_json, seo_title, seo_description, created_by, created_at, canonical_url, featured_media_id, social_media_id, seo_robots_index, seo_robots_follow, schema_mode, layout_template_id, parent_entry_id, menu_order
FROM entry_revisions
WHERE entry_id = ?
ORDER BY revision_number DESC
`

func (q *Queries) ListEntryRevisions(ctx context.Context, entryID string) ([]EntryRevision, error) {
	rows, err := q.db.QueryContext(ctx, listEntryRevisions, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryRevision{}
	for rows.Next() {
		var i EntryRevision
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.RevisionNumber,
			&i.Title,
			&i.Excerpt,
			&i.DocumentJson,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CanonicalUrl,
			&i.FeaturedMediaID,
			&i.SocialMediaID,
			&i.SeoRobotsIndex,
			&i.SeoRobotsFollow,
			&i.SchemaMode,
			&i.LayoutTemplateID,
			&i.ParentEntryID,
			&i.MenuOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestHierarchyForContentType = `-- name: ListLatestHierarchyForContentType :many
SELECT e.id AS entry_id, e.content_type_id, e.slug, e.status, r.title,
       r.parent_entry_id, r.menu_order
FROM entries e
JOIN entry_revisions r ON r.id = (
    SELECT latest.id FROM entry_revisions latest
    WHERE latest.entry_id = e.id
    ORDER BY latest.revision_number DESC
    LIMIT 1
)
WHERE e.content_type_id = ?
ORDER BY r.menu_order, r.title, e.id
`

type ListLatestHierarchyForContentTypeRow struct {
	EntryID       string         `json:"entry_id"`
	ContentTypeID string         `json:"content_type_id"`
	Slug          string         `json:"slug"`
	Status        string         `json:"status"`
	Title         string         `json:"title"`
	ParentEntryID sql.NullString `json:"parent_entry_id"`
	MenuOrder     int64          `json:"menu_order"`
}

func (q *Queries) ListLatestHierarchyForContentType(ctx context.Context, contentTypeID string) ([]ListLatestHierarchyForContentTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestHierarchyForContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestHierarchyForContentTypeRow{}
	for rows.Next() {
		var i ListLatestHierarchyForContentTypeRow
		if err := rows.Scan(
			&i.EntryID,
			&i.ContentTypeID,
			&i.Slug,
			&i.Status,
			&i.Title,
			&i.ParentEntryID,
			&i.MenuOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedHierarchyForContentType = `-- name: ListPublishedHierarchyForContentType :many
SELECT e.id AS entry_id, e.content_type_id, e.slug, e.status, r.title,
       r.parent_entry_id, r.menu_order
FROM entries e
JOIN entry_revisions r ON r.id = e.published_revision_id
WHERE e.content_type_id = ? AND e.status = 'active' AND e.published_revision_id IS NOT NULL
ORDER BY r.menu_order, r.title, e.id
`

type ListPublishedHierarchyForContentTypeRow struct {
	EntryID       string         `json:"entry_id"`
	ContentTypeID string         `json:"content_type_id"`
	Slug          string         `json:"slug"`
	Status        string         `json:"status"`
	Title         string         `json:"title"`
	ParentEntryID sql.NullString `json:"parent_entry_id"`
	MenuOrder     int64          `json:"menu_order"`
}

func (q *Queries) ListPublishedHierarchyForContentType(ctx context.Context, contentTypeID string) ([]ListPublishedHierarchyForContentTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedHierarchyForContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedHierarchyForContentTypeRow{}
	for rows.Next() {
		var i ListPublishedHierarchyForContentTypeRow
		if err := rows.Scan(
			&i.EntryID,
			&i.ContentTypeID,
			&i.Slug,
			&i.Status,
			&i.Title,
			&i.ParentEntryID,
			&i.MenuOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
