// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (
    id, content_type_id, slug, status, author_id, created_at, updated_at, published_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryParams struct {
	ID            string         `json:"id"`
	ContentTypeID string         `json:"content_type_id"`
	Slug          string         `json:"slug"`
	Status        string         `json:"status"`
	AuthorID      sql.NullString `json:"author_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	PublishedAt   sql.NullInt64  `json:"published_at"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.ID,
		arg.ContentTypeID,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at, featured_media_id, first_published_at
FROM entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.FeaturedMediaID,
		&i.FirstPublishedAt,
	)
	return i, err
}

const getEntryBySlug = `-- name: GetEntryBySlug :one
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at, featured_media_id, first_published_at
FROM entries
WHERE content_type_id = ?
  AND slug = ?
LIMIT 1
`

type GetEntryBySlugParams struct {
	ContentTypeID string `json:"content_type_id"`
	Slug          string `json:"slug"`
}

func (q *Queries) GetEntryBySlug(ctx context.Context, arg GetEntryBySlugParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryBySlug, arg.ContentTypeID, arg.Slug)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.FeaturedMediaID,
		&i.FirstPublishedAt,
	)
	return i, err
}

const listEntriesByContentType = `-- name: ListEntriesByContentType :many
SELECT
    entries.id,
    entries.slug,
    entries.status,
    entries.updated_at,
    entries.published_revision_id,
    latest_revision.title,
    public_route.path AS public_path
FROM entries
LEFT JOIN entry_revisions AS latest_revision
    ON latest_revision.entry_id = entries.id
    AND latest_revision.revision_number = (
        SELECT MAX(revision_number)
        FROM entry_revisions
        WHERE entry_id = entries.id
    )
LEFT JOIN routes AS public_route
    ON public_route.id = (
        SELECT id
        FROM routes
        WHERE entry_id = entries.id
          AND route_type = 'entry'
        ORDER BY path
        LIMIT 1
    )
WHERE entries.content_type_id = ?
ORDER BY entries.updated_at DESC, entries.created_at DESC
`

type ListEntriesByContentTypeRow struct {
	ID                  string         `json:"id"`
	Slug                string         `json:"slug"`
	Status              string         `json:"status"`
	UpdatedAt           int64          `json:"updated_at"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	Title               sql.NullString `json:"title"`
	PublicPath          sql.NullString `json:"public_path"`
}

func (q *Queries) ListEntriesByContentType(ctx context.Context, contentTypeID string) ([]ListEntriesByContentTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesByContentTypeRow{}
	for rows.Next() {
		var i ListEntriesByContentTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Status,
			&i.UpdatedAt,
			&i.PublishedRevisionID,
			&i.Title,
			&i.PublicPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFirstPublishedAtIfNull = `-- name: SetFirstPublishedAtIfNull :exec
UPDATE entries
SET first_published_at = ?
WHERE id = ?
  AND first_published_at IS NULL
`

type SetFirstPublishedAtIfNullParams struct {
	FirstPublishedAt sql.NullInt64 `json:"first_published_at"`
	ID               string        `json:"id"`
}

// Records the FIRST publication of an Entry. Later re-publishes must never
// move it: structured data uses it as the stable datePublished.
func (q *Queries) SetFirstPublishedAtIfNull(ctx context.Context, arg SetFirstPublishedAtIfNullParams) error {
	_, err := q.db.ExecContext(ctx, setFirstPublishedAtIfNull, arg.FirstPublishedAt, arg.ID)
	return err
}

const setPublishedRevision = `-- name: SetPublishedRevision :exec
UPDATE entries
SET published_revision_id = ?, status = 'active', published_at = ?, updated_at = ?
WHERE id = ?
`

type SetPublishedRevisionParams struct {
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	PublishedAt         sql.NullInt64  `json:"published_at"`
	UpdatedAt           int64          `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setPublishedRevision,
		arg.PublishedRevisionID,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET slug = ?, status = ?, author_id = ?, updated_at = ?, published_at = ?
WHERE id = ?
`

type UpdateEntryParams struct {
	Slug        string         `json:"slug"`
	Status      string         `json:"status"`
	AuthorID    sql.NullString `json:"author_id"`
	UpdatedAt   int64          `json:"updated_at"`
	PublishedAt sql.NullInt64  `json:"published_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}
