// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry_revision_terms.sql

package db

import (
	"context"
	"database/sql"
)

const countPublishedEntriesByTerm = `-- name: CountPublishedEntriesByTerm :one
SELECT COUNT(*) FROM entries
INNER JOIN entry_revision_terms ON entry_revision_terms.revision_id = entries.published_revision_id
WHERE entry_revision_terms.term_id = ?
`

func (q *Queries) CountPublishedEntriesByTerm(ctx context.Context, termID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedEntriesByTerm, termID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTermsForRevision = `-- name: DeleteTermsForRevision :exec
DELETE FROM entry_revision_terms WHERE revision_id = ?
`

func (q *Queries) DeleteTermsForRevision(ctx context.Context, revisionID string) error {
	_, err := q.db.ExecContext(ctx, deleteTermsForRevision, revisionID)
	return err
}

const listPublishedEntriesByTerm = `-- name: ListPublishedEntriesByTerm :many
SELECT entries.id, entries.slug, entries.content_type_id, latest_revision.title, latest_revision.excerpt, entries.featured_media_id, routes.path AS route_path, entries.published_at, entries.first_published_at, COALESCE(entries.published_revision_id, '') AS revision_id
FROM entries
INNER JOIN entry_revision_terms ON entry_revision_terms.revision_id = entries.published_revision_id
INNER JOIN entry_revisions AS latest_revision ON latest_revision.id = entries.published_revision_id
INNER JOIN routes ON routes.entry_id = entries.id AND routes.route_type = 'entry'
WHERE entry_revision_terms.term_id = ? AND entries.content_type_id = ? AND entries.status = 'active' AND entries.published_revision_id IS NOT NULL
ORDER BY entries.published_at DESC, entries.id DESC
LIMIT ? OFFSET ?
`

type ListPublishedEntriesByTermParams struct {
	TermID        string `json:"term_id"`
	ContentTypeID string `json:"content_type_id"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

type ListPublishedEntriesByTermRow struct {
	ID               string         `json:"id"`
	Slug             string         `json:"slug"`
	ContentTypeID    string         `json:"content_type_id"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	RoutePath        string         `json:"route_path"`
	PublishedAt      sql.NullInt64  `json:"published_at"`
	FirstPublishedAt sql.NullInt64  `json:"first_published_at"`
	RevisionID       string         `json:"revision_id"`
}

func (q *Queries) ListPublishedEntriesByTerm(ctx context.Context, arg ListPublishedEntriesByTermParams) ([]ListPublishedEntriesByTermRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEntriesByTerm,
		arg.TermID,
		arg.ContentTypeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEntriesByTermRow{}
	for rows.Next() {
		var i ListPublishedEntriesByTermRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ContentTypeID,
			&i.Title,
			&i.Excerpt,
			&i.FeaturedMediaID,
			&i.RoutePath,
			&i.PublishedAt,
			&i.FirstPublishedAt,
			&i.RevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEntriesByTermAsc = `-- name: ListPublishedEntriesByTermAsc :many
SELECT entries.id, entries.slug, entries.content_type_id, latest_revision.title, latest_revision.excerpt, entries.featured_media_id, routes.path AS route_path, entries.published_at, entries.first_published_at, COALESCE(entries.published_revision_id, '') AS revision_id
FROM entries
INNER JOIN entry_revision_terms ON entry_revision_terms.revision_id = entries.published_revision_id
INNER JOIN entry_revisions AS latest_revision ON latest_revision.id = entries.published_revision_id
INNER JOIN routes ON routes.entry_id = entries.id AND routes.route_type = 'entry'
WHERE entry_revision_terms.term_id = ? AND entries.content_type_id = ? AND entries.status = 'active' AND entries.published_revision_id IS NOT NULL
ORDER BY entries.published_at ASC, entries.id ASC
LIMIT ? OFFSET ?
`

type ListPublishedEntriesByTermAscParams struct {
	TermID        string `json:"term_id"`
	ContentTypeID string `json:"content_type_id"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

type ListPublishedEntriesByTermAscRow struct {
	ID               string         `json:"id"`
	Slug             string         `json:"slug"`
	ContentTypeID    string         `json:"content_type_id"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	RoutePath        string         `json:"route_path"`
	PublishedAt      sql.NullInt64  `json:"published_at"`
	FirstPublishedAt sql.NullInt64  `json:"first_published_at"`
	RevisionID       string         `json:"revision_id"`
}

func (q *Queries) ListPublishedEntriesByTermAsc(ctx context.Context, arg ListPublishedEntriesByTermAscParams) ([]ListPublishedEntriesByTermAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEntriesByTermAsc,
		arg.TermID,
		arg.ContentTypeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEntriesByTermAscRow{}
	for rows.Next() {
		var i ListPublishedEntriesByTermAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.ContentTypeID,
			&i.Title,
			&i.Excerpt,
			&i.FeaturedMediaID,
			&i.RoutePath,
			&i.PublishedAt,
			&i.FirstPublishedAt,
			&i.RevisionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEntriesByTermCount = `-- name: ListPublishedEntriesByTermCount :one
SELECT COUNT(*) FROM entries
INNER JOIN entry_revision_terms ON entry_revision_terms.revision_id = entries.published_revision_id
WHERE entry_revision_terms.term_id = ? AND entries.content_type_id = ? AND entries.status = 'active' AND entries.published_revision_id IS NOT NULL
`

type ListPublishedEntriesByTermCountParams struct {
	TermID        string `json:"term_id"`
	ContentTypeID string `json:"content_type_id"`
}

func (q *Queries) ListPublishedEntriesByTermCount(ctx context.Context, arg ListPublishedEntriesByTermCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, listPublishedEntriesByTermCount, arg.TermID, arg.ContentTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTermIDsForRevision = `-- name: ListTermIDsForRevision :many
SELECT term_id FROM entry_revision_terms WHERE revision_id = ?
`

func (q *Queries) ListTermIDsForRevision(ctx context.Context, revisionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTermIDsForRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var term_id string
		if err := rows.Scan(&term_id); err != nil {
			return nil, err
		}
		items = append(items, term_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTermsForRevision = `-- name: ListTermsForRevision :many
SELECT terms.id, terms.taxonomy_id, terms.parent_id, terms.name, terms.slug, terms.description, terms.created_at, terms.updated_at FROM terms INNER JOIN entry_revision_terms ON entry_revision_terms.term_id = terms.id WHERE entry_revision_terms.revision_id = ? ORDER BY terms.name
`

func (q *Queries) ListTermsForRevision(ctx context.Context, revisionID string) ([]Term, error) {
	rows, err := q.db.QueryContext(ctx, listTermsForRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.TaxonomyID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTermsForRevision = `-- name: SetTermsForRevision :exec
INSERT INTO entry_revision_terms (revision_id, term_id) VALUES (?, ?) ON CONFLICT(revision_id, term_id) DO NOTHING
`

type SetTermsForRevisionParams struct {
	RevisionID string `json:"revision_id"`
	TermID     string `json:"term_id"`
}

func (q *Queries) SetTermsForRevision(ctx context.Context, arg SetTermsForRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setTermsForRevision, arg.RevisionID, arg.TermID)
	return err
}
