// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const clearPublishedRevision = `-- name: ClearPublishedRevision :exec
UPDATE entries
SET published_revision_id = NULL, published_at = NULL, updated_at = ?
WHERE id = ?
`

type ClearPublishedRevisionParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearPublishedRevision(ctx context.Context, arg ClearPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, clearPublishedRevision, arg.UpdatedAt, arg.ID)
	return err
}

const countEntriesAdmin = `-- name: CountEntriesAdmin :one
SELECT COUNT(*)
FROM entries
LEFT JOIN entry_revisions AS latest_revision
    ON latest_revision.entry_id = entries.id
    AND latest_revision.revision_number = (
        SELECT MAX(revision_number)
        FROM entry_revisions
        WHERE entry_id = entries.id
    )
WHERE entries.content_type_id = ?1
	AND (?2 IS NULL OR entries.author_id = ?2)
   AND (
      ?3 = ''
      OR (
          ?3 = 'published' AND entries.status = 'active' AND entries.published_revision_id IS NOT NULL
      )
      OR (
          ?3 = 'draft' AND entries.status = 'active' AND entries.published_revision_id IS NULL
      )
      OR (
          ?3 = 'private' AND entries.status = 'private'
      )
      OR (
          ?3 = 'trash' AND entries.status = 'trash'
      )
      OR (
          ?3 = 'all' AND entries.status != 'trash'
      )
  )
  AND (
      ?4 = ''
      OR latest_revision.title LIKE '%' || ?4 || '%'
       OR COALESCE(NULLIF(latest_revision.slug, ''), entries.slug) LIKE '%' || ?4 || '%'
  )
`

type CountEntriesAdminParams struct {
	ContentTypeID string      `json:"content_type_id"`
	AuthorID      interface{} `json:"author_id"`
	StatusFilter  interface{} `json:"status_filter"`
	Search        interface{} `json:"search"`
}

func (q *Queries) CountEntriesAdmin(ctx context.Context, arg CountEntriesAdminParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntriesAdmin,
		arg.ContentTypeID,
		arg.AuthorID,
		arg.StatusFilter,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesByAdminStatus = `-- name: CountEntriesByAdminStatus :one
SELECT
    SUM(CASE WHEN status != 'trash' THEN 1 ELSE 0 END) AS all_count,
    SUM(CASE WHEN status = 'active' AND published_revision_id IS NOT NULL THEN 1 ELSE 0 END) AS published_count,
    SUM(CASE WHEN status = 'active' AND published_revision_id IS NULL THEN 1 ELSE 0 END) AS draft_count,
    SUM(CASE WHEN status = 'private' THEN 1 ELSE 0 END) AS private_count,
    SUM(CASE WHEN status = 'trash' THEN 1 ELSE 0 END) AS trash_count
FROM entries
WHERE content_type_id = ?1
  AND (?2 IS NULL OR author_id = ?2)
`

type CountEntriesByAdminStatusParams struct {
	ContentTypeID string      `json:"content_type_id"`
	AuthorID      interface{} `json:"author_id"`
}

type CountEntriesByAdminStatusRow struct {
	AllCount       sql.NullFloat64 `json:"all_count"`
	PublishedCount sql.NullFloat64 `json:"published_count"`
	DraftCount     sql.NullFloat64 `json:"draft_count"`
	PrivateCount   sql.NullFloat64 `json:"private_count"`
	TrashCount     sql.NullFloat64 `json:"trash_count"`
}

func (q *Queries) CountEntriesByAdminStatus(ctx context.Context, arg CountEntriesByAdminStatusParams) (CountEntriesByAdminStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countEntriesByAdminStatus, arg.ContentTypeID, arg.AuthorID)
	var i CountEntriesByAdminStatusRow
	err := row.Scan(
		&i.AllCount,
		&i.PublishedCount,
		&i.DraftCount,
		&i.PrivateCount,
		&i.TrashCount,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :exec
INSERT INTO entries (
    id, content_type_id, slug, status, author_id, created_at, updated_at, published_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryParams struct {
	ID            string         `json:"id"`
	ContentTypeID string         `json:"content_type_id"`
	Slug          string         `json:"slug"`
	Status        string         `json:"status"`
	AuthorID      sql.NullString `json:"author_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	PublishedAt   sql.NullInt64  `json:"published_at"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.ID,
		arg.ContentTypeID,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const deleteRoutesByEntryID = `-- name: DeleteRoutesByEntryID :exec
DELETE FROM routes
WHERE entry_id = ?
`

func (q *Queries) DeleteRoutesByEntryID(ctx context.Context, entryID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteRoutesByEntryID, entryID)
	return err
}

const getEntriesByIDs = `-- name: GetEntriesByIDs :many
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at, featured_media_id, first_published_at, status_before_trash, trashed_at
FROM entries
WHERE id IN (/*SLICE:ids*/?)
  AND content_type_id = ?2
`

type GetEntriesByIDsParams struct {
	Ids           []string `json:"ids"`
	ContentTypeID string   `json:"content_type_id"`
}

func (q *Queries) GetEntriesByIDs(ctx context.Context, arg GetEntriesByIDsParams) ([]Entry, error) {
	query := getEntriesByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.ContentTypeID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.Slug,
			&i.Status,
			&i.AuthorID,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.FeaturedMediaID,
			&i.FirstPublishedAt,
			&i.StatusBeforeTrash,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at, featured_media_id, first_published_at, status_before_trash, trashed_at
FROM entries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.FeaturedMediaID,
		&i.FirstPublishedAt,
		&i.StatusBeforeTrash,
		&i.TrashedAt,
	)
	return i, err
}

const getEntryBySlug = `-- name: GetEntryBySlug :one
SELECT id, content_type_id, slug, status, author_id, published_revision_id, created_at, updated_at, published_at, featured_media_id, first_published_at, status_before_trash, trashed_at
FROM entries
WHERE content_type_id = ?
  AND slug = ?
LIMIT 1
`

type GetEntryBySlugParams struct {
	ContentTypeID string `json:"content_type_id"`
	Slug          string `json:"slug"`
}

func (q *Queries) GetEntryBySlug(ctx context.Context, arg GetEntryBySlugParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryBySlug, arg.ContentTypeID, arg.Slug)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.AuthorID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.FeaturedMediaID,
		&i.FirstPublishedAt,
		&i.StatusBeforeTrash,
		&i.TrashedAt,
	)
	return i, err
}

const listEntriesAdmin = `-- name: ListEntriesAdmin :many
SELECT
    entries.id,
    COALESCE(NULLIF(latest_revision.slug, ''), entries.slug) AS slug,
    entries.status,
    entries.updated_at,
    entries.published_revision_id,
    latest_revision.title,
    public_route.path AS public_path
FROM entries
LEFT JOIN entry_revisions AS latest_revision
    ON latest_revision.entry_id = entries.id
    AND latest_revision.revision_number = (
        SELECT MAX(revision_number)
        FROM entry_revisions
        WHERE entry_id = entries.id
    )
LEFT JOIN routes AS public_route
    ON public_route.id = (
        SELECT id
        FROM routes
        WHERE entry_id = entries.id
          AND route_type = 'entry'
        ORDER BY path
        LIMIT 1
    )
WHERE entries.content_type_id = ?1
	AND (?2 IS NULL OR entries.author_id = ?2)
   AND (
      ?3 = ''
      OR (
          ?3 = 'published' AND entries.status = 'active' AND entries.published_revision_id IS NOT NULL
      )
      OR (
          ?3 = 'draft' AND entries.status = 'active' AND entries.published_revision_id IS NULL
      )
      OR (
          ?3 = 'private' AND entries.status = 'private'
      )
      OR (
          ?3 = 'trash' AND entries.status = 'trash'
      )
      OR (
          ?3 = 'all' AND entries.status != 'trash'
      )
  )
  AND (
      ?4 = ''
      OR latest_revision.title LIKE '%' || ?4 || '%'
       OR COALESCE(NULLIF(latest_revision.slug, ''), entries.slug) LIKE '%' || ?4 || '%'
  )
ORDER BY entries.updated_at DESC, entries.id DESC
LIMIT ?6 OFFSET ?5
`

type ListEntriesAdminParams struct {
	ContentTypeID string      `json:"content_type_id"`
	AuthorID      interface{} `json:"author_id"`
	StatusFilter  interface{} `json:"status_filter"`
	Search        interface{} `json:"search"`
	Offset        int64       `json:"offset"`
	Limit         int64       `json:"limit"`
}

type ListEntriesAdminRow struct {
	ID                  string         `json:"id"`
	Slug                string         `json:"slug"`
	Status              string         `json:"status"`
	UpdatedAt           int64          `json:"updated_at"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	Title               sql.NullString `json:"title"`
	PublicPath          sql.NullString `json:"public_path"`
}

func (q *Queries) ListEntriesAdmin(ctx context.Context, arg ListEntriesAdminParams) ([]ListEntriesAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesAdmin,
		arg.ContentTypeID,
		arg.AuthorID,
		arg.StatusFilter,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesAdminRow{}
	for rows.Next() {
		var i ListEntriesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Status,
			&i.UpdatedAt,
			&i.PublishedRevisionID,
			&i.Title,
			&i.PublicPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByContentType = `-- name: ListEntriesByContentType :many
SELECT
    entries.id,
    COALESCE(NULLIF(latest_revision.slug, ''), entries.slug) AS slug,
    entries.status,
    entries.updated_at,
    entries.published_revision_id,
    latest_revision.title,
    public_route.path AS public_path
FROM entries
LEFT JOIN entry_revisions AS latest_revision
    ON latest_revision.entry_id = entries.id
    AND latest_revision.revision_number = (
        SELECT MAX(revision_number)
        FROM entry_revisions
        WHERE entry_id = entries.id
    )
LEFT JOIN routes AS public_route
    ON public_route.id = (
        SELECT id
        FROM routes
        WHERE entry_id = entries.id
          AND route_type = 'entry'
        ORDER BY path
        LIMIT 1
    )
WHERE entries.content_type_id = ?
ORDER BY entries.updated_at DESC, entries.created_at DESC
`

type ListEntriesByContentTypeRow struct {
	ID                  string         `json:"id"`
	Slug                string         `json:"slug"`
	Status              string         `json:"status"`
	UpdatedAt           int64          `json:"updated_at"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	Title               sql.NullString `json:"title"`
	PublicPath          sql.NullString `json:"public_path"`
}

func (q *Queries) ListEntriesByContentType(ctx context.Context, contentTypeID string) ([]ListEntriesByContentTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesByContentTypeRow{}
	for rows.Next() {
		var i ListEntriesByContentTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Status,
			&i.UpdatedAt,
			&i.PublishedRevisionID,
			&i.Title,
			&i.PublicPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveEntryToTrash = `-- name: MoveEntryToTrash :exec
UPDATE entries
SET status = 'trash',
    status_before_trash = CASE WHEN status IN ('active', 'private') THEN status ELSE 'active' END,
    trashed_at = ?,
    updated_at = ?
WHERE id = ?
  AND status != 'trash'
`

type MoveEntryToTrashParams struct {
	TrashedAt sql.NullInt64 `json:"trashed_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) MoveEntryToTrash(ctx context.Context, arg MoveEntryToTrashParams) error {
	_, err := q.db.ExecContext(ctx, moveEntryToTrash, arg.TrashedAt, arg.UpdatedAt, arg.ID)
	return err
}

const restoreEntryFromTrash = `-- name: RestoreEntryFromTrash :exec
UPDATE entries
SET status = COALESCE(status_before_trash, 'active'),
    status_before_trash = NULL,
    trashed_at = NULL,
    updated_at = ?
WHERE id = ?
  AND status = 'trash'
`

type RestoreEntryFromTrashParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RestoreEntryFromTrash(ctx context.Context, arg RestoreEntryFromTrashParams) error {
	_, err := q.db.ExecContext(ctx, restoreEntryFromTrash, arg.UpdatedAt, arg.ID)
	return err
}

const setFirstPublishedAtIfNull = `-- name: SetFirstPublishedAtIfNull :exec
UPDATE entries
SET first_published_at = ?
WHERE id = ?
  AND first_published_at IS NULL
`

type SetFirstPublishedAtIfNullParams struct {
	FirstPublishedAt sql.NullInt64 `json:"first_published_at"`
	ID               string        `json:"id"`
}

// Records the FIRST publication of an Entry. Later re-publishes must never
// move it: structured data uses it as the stable datePublished.
func (q *Queries) SetFirstPublishedAtIfNull(ctx context.Context, arg SetFirstPublishedAtIfNullParams) error {
	_, err := q.db.ExecContext(ctx, setFirstPublishedAtIfNull, arg.FirstPublishedAt, arg.ID)
	return err
}

const setPublishedRevision = `-- name: SetPublishedRevision :exec
UPDATE entries
SET published_revision_id = ?, status = 'active', published_at = ?, updated_at = ?
WHERE id = ?
`

type SetPublishedRevisionParams struct {
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	PublishedAt         sql.NullInt64  `json:"published_at"`
	UpdatedAt           int64          `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setPublishedRevision,
		arg.PublishedRevisionID,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET slug = ?, status = ?, author_id = ?, updated_at = ?, published_at = ?
WHERE id = ?
`

type UpdateEntryParams struct {
	Slug        string         `json:"slug"`
	Status      string         `json:"status"`
	AuthorID    sql.NullString `json:"author_id"`
	UpdatedAt   int64          `json:"updated_at"`
	PublishedAt sql.NullInt64  `json:"published_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.Slug,
		arg.Status,
		arg.AuthorID,
		arg.UpdatedAt,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}
