// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package db

import (
	"context"
)

const countFormSubmissions = `-- name: CountFormSubmissions :one
SELECT COUNT(*) FROM form_submissions WHERE form_id = ?
`

func (q *Queries) CountFormSubmissions(ctx context.Context, formID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFormSubmissions, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForm = `-- name: CreateForm :exec
INSERT INTO forms (id, name, schema_version, definition_json, active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFormParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	SchemaVersion  int64  `json:"schema_version"`
	DefinitionJson string `json:"definition_json"`
	Active         int64  `json:"active"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) error {
	_, err := q.db.ExecContext(ctx, createForm,
		arg.ID,
		arg.Name,
		arg.SchemaVersion,
		arg.DefinitionJson,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createFormSubmission = `-- name: CreateFormSubmission :exec
INSERT INTO form_submissions (id, form_id, status, values_json, schema_snapshot_json, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateFormSubmissionParams struct {
	ID                 string `json:"id"`
	FormID             string `json:"form_id"`
	Status             string `json:"status"`
	ValuesJson         string `json:"values_json"`
	SchemaSnapshotJson string `json:"schema_snapshot_json"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) error {
	_, err := q.db.ExecContext(ctx, createFormSubmission,
		arg.ID,
		arg.FormID,
		arg.Status,
		arg.ValuesJson,
		arg.SchemaSnapshotJson,
		arg.CreatedAt,
	)
	return err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms WHERE id = ?
`

func (q *Queries) DeleteForm(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteForm, id)
	return err
}

const deleteFormSubmission = `-- name: DeleteFormSubmission :exec
DELETE FROM form_submissions WHERE id = ?
`

func (q *Queries) DeleteFormSubmission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFormSubmission, id)
	return err
}

const getForm = `-- name: GetForm :one
SELECT id, name, schema_version, definition_json, active, created_at, updated_at FROM forms WHERE id = ? LIMIT 1
`

func (q *Queries) GetForm(ctx context.Context, id string) (Form, error) {
	row := q.db.QueryRowContext(ctx, getForm, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaVersion,
		&i.DefinitionJson,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFormSubmission = `-- name: GetFormSubmission :one
SELECT id, form_id, status, values_json, schema_snapshot_json, created_at FROM form_submissions WHERE id = ? LIMIT 1
`

func (q *Queries) GetFormSubmission(ctx context.Context, id string) (FormSubmission, error) {
	row := q.db.QueryRowContext(ctx, getFormSubmission, id)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Status,
		&i.ValuesJson,
		&i.SchemaSnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveForms = `-- name: ListActiveForms :many
SELECT id, name, schema_version, definition_json, active, created_at, updated_at FROM forms WHERE active = 1 ORDER BY name, id
`

func (q *Queries) ListActiveForms(ctx context.Context) ([]Form, error) {
	rows, err := q.db.QueryContext(ctx, listActiveForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Form{}
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaVersion,
			&i.DefinitionJson,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllFormSubmissions = `-- name: ListAllFormSubmissions :many
SELECT id, form_id, status, values_json, schema_snapshot_json, created_at
FROM form_submissions WHERE form_id = ? ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAllFormSubmissions(ctx context.Context, formID string) ([]FormSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listAllFormSubmissions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormSubmission{}
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Status,
			&i.ValuesJson,
			&i.SchemaSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForFormReferenceScan = `-- name: ListDocumentsForFormReferenceScan :many
SELECT document_json FROM entry_revisions
WHERE id IN (SELECT id FROM entry_revisions WHERE (entry_id, revision_number) IN (SELECT entry_id, MAX(revision_number) FROM entry_revisions GROUP BY entry_id))
   OR id IN (SELECT published_revision_id FROM entries WHERE published_revision_id IS NOT NULL)
UNION
SELECT document_json FROM layout_template_revisions
WHERE id IN (SELECT id FROM layout_template_revisions WHERE (layout_template_id, revision_number) IN (SELECT layout_template_id, MAX(revision_number) FROM layout_template_revisions GROUP BY layout_template_id))
   OR id IN (SELECT published_revision_id FROM layout_templates WHERE published_revision_id IS NOT NULL)
UNION
SELECT document_json FROM site_part_revisions
WHERE id IN (SELECT id FROM site_part_revisions WHERE (site_part_id, revision_number) IN (SELECT site_part_id, MAX(revision_number) FROM site_part_revisions GROUP BY site_part_id))
   OR id IN (SELECT published_revision_id FROM site_parts WHERE published_revision_id IS NOT NULL)
`

func (q *Queries) ListDocumentsForFormReferenceScan(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsForFormReferenceScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var document_json string
		if err := rows.Scan(&document_json); err != nil {
			return nil, err
		}
		items = append(items, document_json)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormSubmissions = `-- name: ListFormSubmissions :many
SELECT id, form_id, status, values_json, schema_snapshot_json, created_at
FROM form_submissions WHERE form_id = ? ORDER BY created_at DESC, id DESC LIMIT ? OFFSET ?
`

type ListFormSubmissionsParams struct {
	FormID string `json:"form_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListFormSubmissions(ctx context.Context, arg ListFormSubmissionsParams) ([]FormSubmission, error) {
	rows, err := q.db.QueryContext(ctx, listFormSubmissions, arg.FormID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormSubmission{}
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Status,
			&i.ValuesJson,
			&i.SchemaSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForms = `-- name: ListForms :many
SELECT f.id, f.name, f.schema_version, f.definition_json, f.active, f.created_at, f.updated_at,
       COUNT(s.id) AS submission_count,
       CAST(COALESCE(SUM(CASE WHEN s.status = 'new' THEN 1 ELSE 0 END), 0) AS INTEGER) AS new_count
FROM forms f LEFT JOIN form_submissions s ON s.form_id = f.id
GROUP BY f.id ORDER BY f.name, f.id
`

type ListFormsRow struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	SchemaVersion   int64  `json:"schema_version"`
	DefinitionJson  string `json:"definition_json"`
	Active          int64  `json:"active"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
	SubmissionCount int64  `json:"submission_count"`
	NewCount        int64  `json:"new_count"`
}

func (q *Queries) ListForms(ctx context.Context) ([]ListFormsRow, error) {
	rows, err := q.db.QueryContext(ctx, listForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormsRow{}
	for rows.Next() {
		var i ListFormsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaVersion,
			&i.DefinitionJson,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmissionCount,
			&i.NewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :exec
UPDATE forms SET name = ?, schema_version = ?, definition_json = ?, active = ?, updated_at = ? WHERE id = ?
`

type UpdateFormParams struct {
	Name           string `json:"name"`
	SchemaVersion  int64  `json:"schema_version"`
	DefinitionJson string `json:"definition_json"`
	Active         int64  `json:"active"`
	UpdatedAt      int64  `json:"updated_at"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) error {
	_, err := q.db.ExecContext(ctx, updateForm,
		arg.Name,
		arg.SchemaVersion,
		arg.DefinitionJson,
		arg.Active,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateFormSubmissionStatus = `-- name: UpdateFormSubmissionStatus :exec
UPDATE form_submissions SET status = ? WHERE id = ?
`

type UpdateFormSubmissionStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateFormSubmissionStatus(ctx context.Context, arg UpdateFormSubmissionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFormSubmissionStatus, arg.Status, arg.ID)
	return err
}
