// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"
	"database/sql"
)

const completeImportRun = `-- name: CompleteImportRun :exec
UPDATE import_runs SET completed_at = ? WHERE id = ?
`

type CompleteImportRunParams struct {
	CompletedAt sql.NullInt64 `json:"completed_at"`
	ID          string        `json:"id"`
}

func (q *Queries) CompleteImportRun(ctx context.Context, arg CompleteImportRunParams) error {
	_, err := q.db.ExecContext(ctx, completeImportRun, arg.CompletedAt, arg.ID)
	return err
}

const createImportMapping = `-- name: CreateImportMapping :exec
INSERT INTO import_mappings (source, object_type, external_id, internal_id, run_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateImportMappingParams struct {
	Source     string `json:"source"`
	ObjectType string `json:"object_type"`
	ExternalID string `json:"external_id"`
	InternalID string `json:"internal_id"`
	RunID      string `json:"run_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) CreateImportMapping(ctx context.Context, arg CreateImportMappingParams) error {
	_, err := q.db.ExecContext(ctx, createImportMapping,
		arg.Source,
		arg.ObjectType,
		arg.ExternalID,
		arg.InternalID,
		arg.RunID,
		arg.CreatedAt,
	)
	return err
}

const createImportRun = `-- name: CreateImportRun :exec
INSERT INTO import_runs (id, source, created_at) VALUES (?, ?, ?)
`

type CreateImportRunParams struct {
	ID        string `json:"id"`
	Source    string `json:"source"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) error {
	_, err := q.db.ExecContext(ctx, createImportRun, arg.ID, arg.Source, arg.CreatedAt)
	return err
}

const getImportMapping = `-- name: GetImportMapping :one
SELECT internal_id FROM import_mappings WHERE source = ? AND object_type = ? AND external_id = ?
`

type GetImportMappingParams struct {
	Source     string `json:"source"`
	ObjectType string `json:"object_type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetImportMapping(ctx context.Context, arg GetImportMappingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getImportMapping, arg.Source, arg.ObjectType, arg.ExternalID)
	var internal_id string
	err := row.Scan(&internal_id)
	return internal_id, err
}
