// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: layout_templates.sql

package db

import (
	"context"
	"database/sql"
)

const clearContentTypeDefaultLayoutTemplate = `-- name: ClearContentTypeDefaultLayoutTemplate :exec
UPDATE content_types
SET default_layout_template_id = NULL, updated_at = ?
WHERE id = ?
`

type ClearContentTypeDefaultLayoutTemplateParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearContentTypeDefaultLayoutTemplate(ctx context.Context, arg ClearContentTypeDefaultLayoutTemplateParams) error {
	_, err := q.db.ExecContext(ctx, clearContentTypeDefaultLayoutTemplate, arg.UpdatedAt, arg.ID)
	return err
}

const clearLayoutTemplateParent = `-- name: ClearLayoutTemplateParent :exec
UPDATE layout_templates
SET parent_template_id = NULL, updated_at = ?
WHERE id = ?
`

type ClearLayoutTemplateParentParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearLayoutTemplateParent(ctx context.Context, arg ClearLayoutTemplateParentParams) error {
	_, err := q.db.ExecContext(ctx, clearLayoutTemplateParent, arg.UpdatedAt, arg.ID)
	return err
}

const clearLayoutTemplatePublishedRevision = `-- name: ClearLayoutTemplatePublishedRevision :exec
UPDATE layout_templates
SET published_revision_id = NULL, updated_at = ?
WHERE id = ?
`

type ClearLayoutTemplatePublishedRevisionParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearLayoutTemplatePublishedRevision(ctx context.Context, arg ClearLayoutTemplatePublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, clearLayoutTemplatePublishedRevision, arg.UpdatedAt, arg.ID)
	return err
}

const createLayoutTemplate = `-- name: CreateLayoutTemplate :exec
INSERT INTO layout_templates (id, name, content_type_id, published_revision_id, parent_template_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLayoutTemplateParams struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	ContentTypeID       string         `json:"content_type_id"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	ParentTemplateID    sql.NullString `json:"parent_template_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
}

func (q *Queries) CreateLayoutTemplate(ctx context.Context, arg CreateLayoutTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createLayoutTemplate,
		arg.ID,
		arg.Name,
		arg.ContentTypeID,
		arg.PublishedRevisionID,
		arg.ParentTemplateID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createLayoutTemplateRevision = `-- name: CreateLayoutTemplateRevision :exec
INSERT INTO layout_template_revisions (id, template_id, revision_number, document_json, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateLayoutTemplateRevisionParams struct {
	ID             string         `json:"id"`
	TemplateID     string         `json:"template_id"`
	RevisionNumber int64          `json:"revision_number"`
	DocumentJson   string         `json:"document_json"`
	CreatedBy      sql.NullString `json:"created_by"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) CreateLayoutTemplateRevision(ctx context.Context, arg CreateLayoutTemplateRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createLayoutTemplateRevision,
		arg.ID,
		arg.TemplateID,
		arg.RevisionNumber,
		arg.DocumentJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const getContentTypeWithDefault = `-- name: GetContentTypeWithDefault :one
SELECT id, display_name, plural_name, hierarchical, public, config_json, created_at, updated_at, default_layout_template_id
FROM content_types
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetContentTypeWithDefault(ctx context.Context, id string) (ContentType, error) {
	row := q.db.QueryRowContext(ctx, getContentTypeWithDefault, id)
	var i ContentType
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.PluralName,
		&i.Hierarchical,
		&i.Public,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultLayoutTemplateID,
	)
	return i, err
}

const getLatestLayoutTemplateRevision = `-- name: GetLatestLayoutTemplateRevision :one
SELECT id, template_id, revision_number, document_json, created_by, created_at
FROM layout_template_revisions
WHERE template_id = ?
ORDER BY revision_number DESC
LIMIT 1
`

func (q *Queries) GetLatestLayoutTemplateRevision(ctx context.Context, templateID string) (LayoutTemplateRevision, error) {
	row := q.db.QueryRowContext(ctx, getLatestLayoutTemplateRevision, templateID)
	var i LayoutTemplateRevision
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.RevisionNumber,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLayoutTemplate = `-- name: GetLayoutTemplate :one
SELECT id, name, content_type_id, published_revision_id, created_at, updated_at, parent_template_id
FROM layout_templates
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetLayoutTemplate(ctx context.Context, id string) (LayoutTemplate, error) {
	row := q.db.QueryRowContext(ctx, getLayoutTemplate, id)
	var i LayoutTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContentTypeID,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentTemplateID,
	)
	return i, err
}

const getLayoutTemplateChain = `-- name: GetLayoutTemplateChain :many
SELECT
    t.id,
    t.name,
    t.content_type_id,
    t.published_revision_id,
    t.parent_template_id,
    t.created_at,
    t.updated_at,
    r.id AS revision_id,
    r.document_json
FROM layout_templates t
JOIN layout_template_revisions r ON r.id = t.published_revision_id
WHERE t.id = ?
LIMIT 1
`

type GetLayoutTemplateChainRow struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	ContentTypeID       string         `json:"content_type_id"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	ParentTemplateID    sql.NullString `json:"parent_template_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	RevisionID          string         `json:"revision_id"`
	DocumentJson        string         `json:"document_json"`
}

func (q *Queries) GetLayoutTemplateChain(ctx context.Context, id string) ([]GetLayoutTemplateChainRow, error) {
	rows, err := q.db.QueryContext(ctx, getLayoutTemplateChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLayoutTemplateChainRow{}
	for rows.Next() {
		var i GetLayoutTemplateChainRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentTypeID,
			&i.PublishedRevisionID,
			&i.ParentTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevisionID,
			&i.DocumentJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLayoutTemplateRevision = `-- name: GetLayoutTemplateRevision :one
SELECT id, template_id, revision_number, document_json, created_by, created_at
FROM layout_template_revisions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetLayoutTemplateRevision(ctx context.Context, id string) (LayoutTemplateRevision, error) {
	row := q.db.QueryRowContext(ctx, getLayoutTemplateRevision, id)
	var i LayoutTemplateRevision
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.RevisionNumber,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLayoutTemplateWithPublishedRevision = `-- name: GetLayoutTemplateWithPublishedRevision :one
SELECT
    t.id,
    t.name,
    t.content_type_id,
    t.published_revision_id,
    t.parent_template_id,
    t.created_at,
    t.updated_at,
    r.id AS revision_id,
    r.document_json
FROM layout_templates t
JOIN layout_template_revisions r ON r.id = t.published_revision_id
WHERE t.id = ?
LIMIT 1
`

type GetLayoutTemplateWithPublishedRevisionRow struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	ContentTypeID       string         `json:"content_type_id"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	ParentTemplateID    sql.NullString `json:"parent_template_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	RevisionID          string         `json:"revision_id"`
	DocumentJson        string         `json:"document_json"`
}

func (q *Queries) GetLayoutTemplateWithPublishedRevision(ctx context.Context, id string) (GetLayoutTemplateWithPublishedRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getLayoutTemplateWithPublishedRevision, id)
	var i GetLayoutTemplateWithPublishedRevisionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContentTypeID,
		&i.PublishedRevisionID,
		&i.ParentTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionID,
		&i.DocumentJson,
	)
	return i, err
}

const getPublishedLayoutTemplateRevision = `-- name: GetPublishedLayoutTemplateRevision :one
SELECT r.id, r.template_id, r.revision_number, r.document_json, r.created_by, r.created_at
FROM layout_templates t
JOIN layout_template_revisions r ON r.id = t.published_revision_id
WHERE t.id = ?
LIMIT 1
`

func (q *Queries) GetPublishedLayoutTemplateRevision(ctx context.Context, id string) (LayoutTemplateRevision, error) {
	row := q.db.QueryRowContext(ctx, getPublishedLayoutTemplateRevision, id)
	var i LayoutTemplateRevision
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.RevisionNumber,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestLayoutRevisions = `-- name: ListLatestLayoutRevisions :many
SELECT id, template_id, revision_number, document_json, created_by, created_at
FROM layout_template_revisions
WHERE id IN (
    SELECT id FROM layout_template_revisions
    WHERE (template_id, revision_number) IN (
        SELECT template_id, MAX(revision_number) FROM layout_template_revisions GROUP BY template_id
    )
)
`

func (q *Queries) ListLatestLayoutRevisions(ctx context.Context) ([]LayoutTemplateRevision, error) {
	rows, err := q.db.QueryContext(ctx, listLatestLayoutRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutTemplateRevision{}
	for rows.Next() {
		var i LayoutTemplateRevision
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.RevisionNumber,
			&i.DocumentJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLayoutTemplateRevisions = `-- name: ListLayoutTemplateRevisions :many
SELECT id, template_id, revision_number, document_json, created_by, created_at
FROM layout_template_revisions
WHERE template_id = ?
ORDER BY revision_number DESC
`

func (q *Queries) ListLayoutTemplateRevisions(ctx context.Context, templateID string) ([]LayoutTemplateRevision, error) {
	rows, err := q.db.QueryContext(ctx, listLayoutTemplateRevisions, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutTemplateRevision{}
	for rows.Next() {
		var i LayoutTemplateRevision
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.RevisionNumber,
			&i.DocumentJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLayoutTemplates = `-- name: ListLayoutTemplates :many
SELECT id, name, content_type_id, published_revision_id, created_at, updated_at, parent_template_id
FROM layout_templates
ORDER BY
    CASE WHEN published_revision_id IS NULL THEN 1 ELSE 0 END,
    name,
    id
`

func (q *Queries) ListLayoutTemplates(ctx context.Context) ([]LayoutTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listLayoutTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutTemplate{}
	for rows.Next() {
		var i LayoutTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentTypeID,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLayoutTemplatesByContentType = `-- name: ListLayoutTemplatesByContentType :many
SELECT id, name, content_type_id, published_revision_id, created_at, updated_at, parent_template_id
FROM layout_templates
WHERE content_type_id = ?
ORDER BY name, id
`

func (q *Queries) ListLayoutTemplatesByContentType(ctx context.Context, contentTypeID string) ([]LayoutTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listLayoutTemplatesByContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutTemplate{}
	for rows.Next() {
		var i LayoutTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentTypeID,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedLayoutTemplatesByContentType = `-- name: ListPublishedLayoutTemplatesByContentType :many
SELECT id, name, content_type_id, published_revision_id, created_at, updated_at, parent_template_id
FROM layout_templates
WHERE content_type_id = ?
  AND published_revision_id IS NOT NULL
ORDER BY name, id
`

func (q *Queries) ListPublishedLayoutTemplatesByContentType(ctx context.Context, contentTypeID string) ([]LayoutTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedLayoutTemplatesByContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LayoutTemplate{}
	for rows.Next() {
		var i LayoutTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentTypeID,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentTemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContentTypeDefaultLayoutTemplate = `-- name: SetContentTypeDefaultLayoutTemplate :exec
UPDATE content_types
SET default_layout_template_id = ?, updated_at = ?
WHERE id = ?
`

type SetContentTypeDefaultLayoutTemplateParams struct {
	DefaultLayoutTemplateID sql.NullString `json:"default_layout_template_id"`
	UpdatedAt               int64          `json:"updated_at"`
	ID                      string         `json:"id"`
}

func (q *Queries) SetContentTypeDefaultLayoutTemplate(ctx context.Context, arg SetContentTypeDefaultLayoutTemplateParams) error {
	_, err := q.db.ExecContext(ctx, setContentTypeDefaultLayoutTemplate, arg.DefaultLayoutTemplateID, arg.UpdatedAt, arg.ID)
	return err
}

const setLayoutTemplatePublishedRevision = `-- name: SetLayoutTemplatePublishedRevision :exec
UPDATE layout_templates
SET published_revision_id = ?, updated_at = ?
WHERE id = ?
`

type SetLayoutTemplatePublishedRevisionParams struct {
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	UpdatedAt           int64          `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) SetLayoutTemplatePublishedRevision(ctx context.Context, arg SetLayoutTemplatePublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setLayoutTemplatePublishedRevision, arg.PublishedRevisionID, arg.UpdatedAt, arg.ID)
	return err
}

const updateLayoutTemplate = `-- name: UpdateLayoutTemplate :exec
UPDATE layout_templates
SET name = ?, updated_at = ?
WHERE id = ?
`

type UpdateLayoutTemplateParams struct {
	Name      string `json:"name"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateLayoutTemplate(ctx context.Context, arg UpdateLayoutTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateLayoutTemplate, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const updateLayoutTemplateParent = `-- name: UpdateLayoutTemplateParent :exec
UPDATE layout_templates
SET parent_template_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateLayoutTemplateParentParams struct {
	ParentTemplateID sql.NullString `json:"parent_template_id"`
	UpdatedAt        int64          `json:"updated_at"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateLayoutTemplateParent(ctx context.Context, arg UpdateLayoutTemplateParentParams) error {
	_, err := q.db.ExecContext(ctx, updateLayoutTemplateParent, arg.ParentTemplateID, arg.UpdatedAt, arg.ID)
	return err
}
