// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"database/sql"
)

const countMedia = `-- name: CountMedia :one
SELECT COUNT(*) FROM media
`

func (q *Queries) CountMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaUsage = `-- name: CountMediaUsage :one
SELECT
    (
        SELECT COUNT(*) FROM entry_revisions
        WHERE document_json LIKE '%"mediaId":"' || ?1 || '"%'
    )
    + (
        SELECT COUNT(*) FROM site_settings
        WHERE site_icon_media_id = ?1
    )
    + (
        SELECT COUNT(*) FROM entries
        WHERE featured_media_id = ?1
    )
AS usage_count
`

func (q *Queries) CountMediaUsage(ctx context.Context, id sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaUsage, id)
	var usage_count int64
	err := row.Scan(&usage_count)
	return usage_count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    id, original_filename, storage_key, mime_type, asset_type, file_size,
    width, height, alt_text, title, caption, description, author_id,
    created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, original_filename, storage_key, mime_type, asset_type, file_size, width, height, alt_text, title, caption, description, author_id, created_at, updated_at
`

type CreateMediaParams struct {
	ID               string         `json:"id"`
	OriginalFilename string         `json:"original_filename"`
	StorageKey       string         `json:"storage_key"`
	MimeType         string         `json:"mime_type"`
	AssetType        string         `json:"asset_type"`
	FileSize         int64          `json:"file_size"`
	Width            sql.NullInt64  `json:"width"`
	Height           sql.NullInt64  `json:"height"`
	AltText          string         `json:"alt_text"`
	Title            string         `json:"title"`
	Caption          string         `json:"caption"`
	Description      string         `json:"description"`
	AuthorID         sql.NullString `json:"author_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.ID,
		arg.OriginalFilename,
		arg.StorageKey,
		arg.MimeType,
		arg.AssetType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.AltText,
		arg.Title,
		arg.Caption,
		arg.Description,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.MimeType,
		&i.AssetType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.AltText,
		&i.Title,
		&i.Caption,
		&i.Description,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaVariant = `-- name: CreateMediaVariant :one
INSERT INTO media_variants (
    id, media_id, kind, storage_key, mime_type, width, height, file_size, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, media_id, kind, storage_key, mime_type, width, height, file_size, created_at
`

type CreateMediaVariantParams struct {
	ID         string        `json:"id"`
	MediaID    string        `json:"media_id"`
	Kind       string        `json:"kind"`
	StorageKey string        `json:"storage_key"`
	MimeType   string        `json:"mime_type"`
	Width      sql.NullInt64 `json:"width"`
	Height     sql.NullInt64 `json:"height"`
	FileSize   int64         `json:"file_size"`
	CreatedAt  int64         `json:"created_at"`
}

func (q *Queries) CreateMediaVariant(ctx context.Context, arg CreateMediaVariantParams) (MediaVariant, error) {
	row := q.db.QueryRowContext(ctx, createMediaVariant,
		arg.ID,
		arg.MediaID,
		arg.Kind,
		arg.StorageKey,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.FileSize,
		arg.CreatedAt,
	)
	var i MediaVariant
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Kind,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const deleteMediaVariant = `-- name: DeleteMediaVariant :exec
DELETE FROM media_variants WHERE id = ?
`

func (q *Queries) DeleteMediaVariant(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaVariant, id)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, original_filename, storage_key, mime_type, asset_type, file_size, width, height, alt_text, title, caption, description, author_id, created_at, updated_at FROM media WHERE id = ?
`

func (q *Queries) GetMedia(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.MimeType,
		&i.AssetType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.AltText,
		&i.Title,
		&i.Caption,
		&i.Description,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaVariant = `-- name: GetMediaVariant :one
SELECT id, media_id, kind, storage_key, mime_type, width, height, file_size, created_at FROM media_variants WHERE media_id = ? AND kind = ?
`

type GetMediaVariantParams struct {
	MediaID string `json:"media_id"`
	Kind    string `json:"kind"`
}

func (q *Queries) GetMediaVariant(ctx context.Context, arg GetMediaVariantParams) (MediaVariant, error) {
	row := q.db.QueryRowContext(ctx, getMediaVariant, arg.MediaID, arg.Kind)
	var i MediaVariant
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Kind,
		&i.StorageKey,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteIconMediaID = `-- name: GetSiteIconMediaID :one
SELECT site_icon_media_id FROM site_settings WHERE id = 1
`

func (q *Queries) GetSiteIconMediaID(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSiteIconMediaID)
	var site_icon_media_id sql.NullString
	err := row.Scan(&site_icon_media_id)
	return site_icon_media_id, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, original_filename, storage_key, mime_type, asset_type, file_size, width, height, alt_text, title, caption, description, author_id, created_at, updated_at FROM media ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListMediaParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.StorageKey,
			&i.MimeType,
			&i.AssetType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.AltText,
			&i.Title,
			&i.Caption,
			&i.Description,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaVariants = `-- name: ListMediaVariants :many
SELECT id, media_id, kind, storage_key, mime_type, width, height, file_size, created_at FROM media_variants WHERE media_id = ? ORDER BY kind
`

func (q *Queries) ListMediaVariants(ctx context.Context, mediaID string) ([]MediaVariant, error) {
	rows, err := q.db.QueryContext(ctx, listMediaVariants, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaVariant{}
	for rows.Next() {
		var i MediaVariant
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Kind,
			&i.StorageKey,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaMetadata = `-- name: UpdateMediaMetadata :exec
UPDATE media
SET alt_text = ?,
    title = ?,
    caption = ?,
    description = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateMediaMetadataParams struct {
	AltText     string `json:"alt_text"`
	Title       string `json:"title"`
	Caption     string `json:"caption"`
	Description string `json:"description"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaMetadata,
		arg.AltText,
		arg.Title,
		arg.Caption,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSiteIconMediaID = `-- name: UpdateSiteIconMediaID :exec
UPDATE site_settings
SET site_icon_media_id = ?, updated_at = unixepoch()
WHERE id = 1
`

func (q *Queries) UpdateSiteIconMediaID(ctx context.Context, siteIconMediaID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateSiteIconMediaID, siteIconMediaID)
	return err
}
