// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type BlockDefinition struct {
	ID           string         `json:"id"`
	Namespace    string         `json:"namespace"`
	Name         string         `json:"name"`
	Version      int64          `json:"version"`
	DisplayName  string         `json:"display_name"`
	Description  sql.NullString `json:"description"`
	SchemaJson   string         `json:"schema_json"`
	RendererType string         `json:"renderer_type"`
	Template     sql.NullString `json:"template"`
	Styles       sql.NullString `json:"styles"`
	Source       string         `json:"source"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type ContentType struct {
	ID                      string         `json:"id"`
	DisplayName             string         `json:"display_name"`
	PluralName              string         `json:"plural_name"`
	Hierarchical            int64          `json:"hierarchical"`
	Public                  int64          `json:"public"`
	ConfigJson              string         `json:"config_json"`
	CreatedAt               int64          `json:"created_at"`
	UpdatedAt               int64          `json:"updated_at"`
	DefaultLayoutTemplateID sql.NullString `json:"default_layout_template_id"`
}

type Entry struct {
	ID                  string         `json:"id"`
	ContentTypeID       string         `json:"content_type_id"`
	Slug                string         `json:"slug"`
	Status              string         `json:"status"`
	AuthorID            sql.NullString `json:"author_id"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	PublishedAt         sql.NullInt64  `json:"published_at"`
	FeaturedMediaID     sql.NullString `json:"featured_media_id"`
	FirstPublishedAt    sql.NullInt64  `json:"first_published_at"`
	StatusBeforeTrash   sql.NullString `json:"status_before_trash"`
	TrashedAt           sql.NullInt64  `json:"trashed_at"`
}

type EntryRevision struct {
	ID               string         `json:"id"`
	EntryID          string         `json:"entry_id"`
	RevisionNumber   int64          `json:"revision_number"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	DocumentJson     string         `json:"document_json"`
	SeoTitle         sql.NullString `json:"seo_title"`
	SeoDescription   sql.NullString `json:"seo_description"`
	CreatedBy        sql.NullString `json:"created_by"`
	CreatedAt        int64          `json:"created_at"`
	CanonicalUrl     sql.NullString `json:"canonical_url"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	SocialMediaID    sql.NullString `json:"social_media_id"`
	SeoRobotsIndex   sql.NullInt64  `json:"seo_robots_index"`
	SeoRobotsFollow  sql.NullInt64  `json:"seo_robots_follow"`
	SchemaMode       string         `json:"schema_mode"`
	LayoutTemplateID sql.NullString `json:"layout_template_id"`
	ParentEntryID    sql.NullString `json:"parent_entry_id"`
	MenuOrder        int64          `json:"menu_order"`
	Slug             string         `json:"slug"`
	FieldsJson       string         `json:"fields_json"`
	Visibility       string         `json:"visibility"`
	PasswordHash     sql.NullString `json:"password_hash"`
	Sticky           int64          `json:"sticky"`
	ReviewState      string         `json:"review_state"`
}

type EntryRevisionTerm struct {
	RevisionID string `json:"revision_id"`
	TermID     string `json:"term_id"`
}

type LayoutTemplate struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	ContentTypeID       string         `json:"content_type_id"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
}

type LayoutTemplateRevision struct {
	ID             string         `json:"id"`
	TemplateID     string         `json:"template_id"`
	RevisionNumber int64          `json:"revision_number"`
	DocumentJson   string         `json:"document_json"`
	CreatedBy      sql.NullString `json:"created_by"`
	CreatedAt      int64          `json:"created_at"`
}

type MediaVariant struct {
	ID          string        `json:"id"`
	MediaID     string        `json:"media_id"`
	Kind        string        `json:"kind"`
	StorageKey  string        `json:"storage_key"`
	MimeType    string        `json:"mime_type"`
	Width       sql.NullInt64 `json:"width"`
	Height      sql.NullInt64 `json:"height"`
	FileSize    int64         `json:"file_size"`
	CreatedAt   int64         `json:"created_at"`
	ContentHash string        `json:"content_hash"`
}

type Medium struct {
	ID               string         `json:"id"`
	OriginalFilename string         `json:"original_filename"`
	StorageKey       string         `json:"storage_key"`
	MimeType         string         `json:"mime_type"`
	AssetType        string         `json:"asset_type"`
	FileSize         int64          `json:"file_size"`
	Width            sql.NullInt64  `json:"width"`
	Height           sql.NullInt64  `json:"height"`
	AltText          string         `json:"alt_text"`
	Title            string         `json:"title"`
	Caption          string         `json:"caption"`
	Description      string         `json:"description"`
	AuthorID         sql.NullString `json:"author_id"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type NavigationItem struct {
	ID         string         `json:"id"`
	MenuID     string         `json:"menu_id"`
	ParentID   sql.NullString `json:"parent_id"`
	Position   int64          `json:"position"`
	Label      string         `json:"label"`
	TargetType string         `json:"target_type"`
	EntryID    sql.NullString `json:"entry_id"`
	Url        sql.NullString `json:"url"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

type NavigationLocation struct {
	Location string `json:"location"`
	MenuID   string `json:"menu_id"`
}

type NavigationMenu struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type PublicationJob struct {
	ID          string         `json:"id"`
	EntryID     string         `json:"entry_id"`
	RevisionID  string         `json:"revision_id"`
	ScheduledAt int64          `json:"scheduled_at"`
	Status      string         `json:"status"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	LastError   sql.NullString `json:"last_error"`
}

type Route struct {
	ID             string         `json:"id"`
	Path           string         `json:"path"`
	EntryID        sql.NullString `json:"entry_id"`
	RouteType      string         `json:"route_type"`
	RedirectTo     sql.NullString `json:"redirect_to"`
	RedirectStatus sql.NullInt64  `json:"redirect_status"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	ContentTypeID  sql.NullString `json:"content_type_id"`
	TaxonomyID     sql.NullString `json:"taxonomy_id"`
	TermID         sql.NullString `json:"term_id"`
}

type Session struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
}

type SiteSetting struct {
	ID                   int64          `json:"id"`
	SiteTitle            string         `json:"site_title"`
	SiteTagline          string         `json:"site_tagline"`
	HomepageMode         string         `json:"homepage_mode"`
	HomepageEntryID      sql.NullString `json:"homepage_entry_id"`
	PostsPageEntryID     sql.NullString `json:"posts_page_entry_id"`
	PostsPerPage         int64          `json:"posts_per_page"`
	Language             string         `json:"language"`
	Timezone             string         `json:"timezone"`
	ActiveTheme          string         `json:"active_theme"`
	IndexingEnabled      int64          `json:"indexing_enabled"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
	SiteUrl              string         `json:"site_url"`
	SitemapEnabled       int64          `json:"sitemap_enabled"`
	RobotsMode           string         `json:"robots_mode"`
	RobotsCustom         string         `json:"robots_custom"`
	SpeculationMode      string         `json:"speculation_mode"`
	SpeculationEagerness string         `json:"speculation_eagerness"`
	TitleSeparator       string         `json:"title_separator"`
	SiteIconMediaID      sql.NullString `json:"site_icon_media_id"`
	SiteLogoMediaID      sql.NullString `json:"site_logo_media_id"`
	SocialLinks          sql.NullString `json:"social_links"`
	SiteSocialMediaID    sql.NullString `json:"site_social_media_id"`
	TwitterSite          string         `json:"twitter_site"`
	SiteRepresents       string         `json:"site_represents"`
	PostsBasePath        string         `json:"posts_base_path"`
}

type Taxonomy struct {
	ID            string         `json:"id"`
	ContentTypeID string         `json:"content_type_id"`
	SingularName  string         `json:"singular_name"`
	PluralName    string         `json:"plural_name"`
	Hierarchical  int64          `json:"hierarchical"`
	Public        int64          `json:"public"`
	RouteBase     sql.NullString `json:"route_base"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type Term struct {
	ID          string         `json:"id"`
	TaxonomyID  string         `json:"taxonomy_id"`
	ParentID    sql.NullString `json:"parent_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type ThemeCustomization struct {
	ThemeID      string `json:"theme_id"`
	ThemeVersion int64  `json:"theme_version"`
	SettingsJson string `json:"settings_json"`
	CustomCss    string `json:"custom_css"`
	UpdatedAt    int64  `json:"updated_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
	Status       string `json:"status"`
}
