// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type BlockDefinition struct {
	ID           string         `json:"id"`
	Namespace    string         `json:"namespace"`
	Name         string         `json:"name"`
	Version      int64          `json:"version"`
	DisplayName  string         `json:"display_name"`
	Description  sql.NullString `json:"description"`
	SchemaJson   string         `json:"schema_json"`
	RendererType string         `json:"renderer_type"`
	Template     sql.NullString `json:"template"`
	Styles       sql.NullString `json:"styles"`
	Source       string         `json:"source"`
	Enabled      int64          `json:"enabled"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type ContentType struct {
	ID           string `json:"id"`
	DisplayName  string `json:"display_name"`
	PluralName   string `json:"plural_name"`
	Hierarchical int64  `json:"hierarchical"`
	Public       int64  `json:"public"`
	ConfigJson   string `json:"config_json"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Entry struct {
	ID                  string         `json:"id"`
	ContentTypeID       string         `json:"content_type_id"`
	Slug                string         `json:"slug"`
	Status              string         `json:"status"`
	AuthorID            sql.NullString `json:"author_id"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	PublishedAt         sql.NullInt64  `json:"published_at"`
}

type EntryRevision struct {
	ID             string         `json:"id"`
	EntryID        string         `json:"entry_id"`
	RevisionNumber int64          `json:"revision_number"`
	Title          string         `json:"title"`
	Excerpt        sql.NullString `json:"excerpt"`
	DocumentJson   string         `json:"document_json"`
	SeoTitle       sql.NullString `json:"seo_title"`
	SeoDescription sql.NullString `json:"seo_description"`
	CreatedBy      sql.NullString `json:"created_by"`
	CreatedAt      int64          `json:"created_at"`
}

type Route struct {
	ID             string         `json:"id"`
	Path           string         `json:"path"`
	EntryID        sql.NullString `json:"entry_id"`
	RouteType      string         `json:"route_type"`
	RedirectTo     sql.NullString `json:"redirect_to"`
	RedirectStatus sql.NullInt64  `json:"redirect_status"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type Session struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
}

type SiteSetting struct {
	ID               int64          `json:"id"`
	SiteTitle        string         `json:"site_title"`
	SiteTagline      string         `json:"site_tagline"`
	HomepageMode     string         `json:"homepage_mode"`
	HomepageEntryID  sql.NullString `json:"homepage_entry_id"`
	PostsPageEntryID sql.NullString `json:"posts_page_entry_id"`
	PostsPerPage     int64          `json:"posts_per_page"`
	Language         string         `json:"language"`
	Timezone         string         `json:"timezone"`
	ActiveTheme      string         `json:"active_theme"`
	IndexingEnabled  int64          `json:"indexing_enabled"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}
