// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: navigation.sql

package db

import (
	"context"
	"database/sql"
)

const createNavigationItem = `-- name: CreateNavigationItem :exec
INSERT INTO navigation_items (
    id, menu_id, parent_id, position, label, target_type,
    entry_id, url, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNavigationItemParams struct {
	ID         string         `json:"id"`
	MenuID     string         `json:"menu_id"`
	ParentID   sql.NullString `json:"parent_id"`
	Position   int64          `json:"position"`
	Label      string         `json:"label"`
	TargetType string         `json:"target_type"`
	EntryID    sql.NullString `json:"entry_id"`
	Url        sql.NullString `json:"url"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) CreateNavigationItem(ctx context.Context, arg CreateNavigationItemParams) error {
	_, err := q.db.ExecContext(ctx, createNavigationItem,
		arg.ID,
		arg.MenuID,
		arg.ParentID,
		arg.Position,
		arg.Label,
		arg.TargetType,
		arg.EntryID,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createNavigationMenu = `-- name: CreateNavigationMenu :exec
INSERT INTO navigation_menus (id, name, slug, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateNavigationMenuParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateNavigationMenu(ctx context.Context, arg CreateNavigationMenuParams) error {
	_, err := q.db.ExecContext(ctx, createNavigationMenu,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteNavigationItemsByMenu = `-- name: DeleteNavigationItemsByMenu :exec
DELETE FROM navigation_items WHERE menu_id = ?
`

func (q *Queries) DeleteNavigationItemsByMenu(ctx context.Context, menuID string) error {
	_, err := q.db.ExecContext(ctx, deleteNavigationItemsByMenu, menuID)
	return err
}

const deleteNavigationLocationsForMenu = `-- name: DeleteNavigationLocationsForMenu :exec
DELETE FROM navigation_locations WHERE menu_id = ?
`

func (q *Queries) DeleteNavigationLocationsForMenu(ctx context.Context, menuID string) error {
	_, err := q.db.ExecContext(ctx, deleteNavigationLocationsForMenu, menuID)
	return err
}

const deleteNavigationMenu = `-- name: DeleteNavigationMenu :exec
DELETE FROM navigation_menus WHERE id = ?
`

func (q *Queries) DeleteNavigationMenu(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNavigationMenu, id)
	return err
}

const getNavigationMenu = `-- name: GetNavigationMenu :one
SELECT id, name, slug, created_at, updated_at FROM navigation_menus WHERE id = ? LIMIT 1
`

func (q *Queries) GetNavigationMenu(ctx context.Context, id string) (NavigationMenu, error) {
	row := q.db.QueryRowContext(ctx, getNavigationMenu, id)
	var i NavigationMenu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNavigationMenuBySlug = `-- name: GetNavigationMenuBySlug :one
SELECT id, name, slug, created_at, updated_at FROM navigation_menus WHERE slug = ? LIMIT 1
`

func (q *Queries) GetNavigationMenuBySlug(ctx context.Context, slug string) (NavigationMenu, error) {
	row := q.db.QueryRowContext(ctx, getNavigationMenuBySlug, slug)
	var i NavigationMenu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNavigationItemsByMenu = `-- name: ListNavigationItemsByMenu :many
SELECT
    ni.id, ni.menu_id, ni.parent_id, ni.position, ni.label, ni.target_type, ni.entry_id, ni.url, ni.created_at, ni.updated_at,
    e.status AS entry_status,
    e.content_type_id AS entry_content_type,
    e.published_revision_id AS entry_published_revision_id,
    latest_revision.title AS entry_title,
    rt.path AS entry_path
FROM navigation_items ni
LEFT JOIN entries e ON e.id = ni.entry_id
LEFT JOIN entry_revisions latest_revision
    ON latest_revision.entry_id = e.id
    AND latest_revision.revision_number = (
        SELECT MAX(revision_number) FROM entry_revisions WHERE entry_id = e.id
    )
LEFT JOIN routes rt ON rt.id = (
    SELECT id FROM routes
    WHERE entry_id = ni.entry_id AND route_type = 'entry'
    ORDER BY path LIMIT 1
)
WHERE ni.menu_id = ?
ORDER BY COALESCE(ni.parent_id, ''), ni.position, ni.id
`

type ListNavigationItemsByMenuRow struct {
	ID                       string         `json:"id"`
	MenuID                   string         `json:"menu_id"`
	ParentID                 sql.NullString `json:"parent_id"`
	Position                 int64          `json:"position"`
	Label                    string         `json:"label"`
	TargetType               string         `json:"target_type"`
	EntryID                  sql.NullString `json:"entry_id"`
	Url                      sql.NullString `json:"url"`
	CreatedAt                int64          `json:"created_at"`
	UpdatedAt                int64          `json:"updated_at"`
	EntryStatus              sql.NullString `json:"entry_status"`
	EntryContentType         sql.NullString `json:"entry_content_type"`
	EntryPublishedRevisionID sql.NullString `json:"entry_published_revision_id"`
	EntryTitle               sql.NullString `json:"entry_title"`
	EntryPath                sql.NullString `json:"entry_path"`
}

func (q *Queries) ListNavigationItemsByMenu(ctx context.Context, menuID string) ([]ListNavigationItemsByMenuRow, error) {
	rows, err := q.db.QueryContext(ctx, listNavigationItemsByMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNavigationItemsByMenuRow{}
	for rows.Next() {
		var i ListNavigationItemsByMenuRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Position,
			&i.Label,
			&i.TargetType,
			&i.EntryID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryStatus,
			&i.EntryContentType,
			&i.EntryPublishedRevisionID,
			&i.EntryTitle,
			&i.EntryPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavigationLocations = `-- name: ListNavigationLocations :many
SELECT location, menu_id FROM navigation_locations ORDER BY location
`

func (q *Queries) ListNavigationLocations(ctx context.Context) ([]NavigationLocation, error) {
	rows, err := q.db.QueryContext(ctx, listNavigationLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NavigationLocation{}
	for rows.Next() {
		var i NavigationLocation
		if err := rows.Scan(&i.Location, &i.MenuID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavigationLocationsForMenu = `-- name: ListNavigationLocationsForMenu :many
SELECT location FROM navigation_locations WHERE menu_id = ? ORDER BY location
`

func (q *Queries) ListNavigationLocationsForMenu(ctx context.Context, menuID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNavigationLocationsForMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var location string
		if err := rows.Scan(&location); err != nil {
			return nil, err
		}
		items = append(items, location)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavigationMenus = `-- name: ListNavigationMenus :many
SELECT id, name, slug, created_at, updated_at FROM navigation_menus ORDER BY name, id
`

func (q *Queries) ListNavigationMenus(ctx context.Context) ([]NavigationMenu, error) {
	rows, err := q.db.QueryContext(ctx, listNavigationMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NavigationMenu{}
	for rows.Next() {
		var i NavigationMenu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPagesForNavigation = `-- name: ListPublishedPagesForNavigation :many
SELECT e.id, r.title, rt.path
FROM entries e
JOIN entry_revisions r ON r.id = e.published_revision_id
JOIN routes rt ON rt.id = (
    SELECT id FROM routes
    WHERE entry_id = e.id AND route_type = 'entry'
    ORDER BY path LIMIT 1
)
WHERE e.content_type_id = 'page' AND e.status = 'active'
ORDER BY r.title, e.id
`

type ListPublishedPagesForNavigationRow struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Path  string `json:"path"`
}

func (q *Queries) ListPublishedPagesForNavigation(ctx context.Context) ([]ListPublishedPagesForNavigationRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPagesForNavigation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPagesForNavigationRow{}
	for rows.Next() {
		var i ListPublishedPagesForNavigationRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNavigationMenu = `-- name: UpdateNavigationMenu :exec
UPDATE navigation_menus SET name = ?, slug = ?, updated_at = ? WHERE id = ?
`

type UpdateNavigationMenuParams struct {
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateNavigationMenu(ctx context.Context, arg UpdateNavigationMenuParams) error {
	_, err := q.db.ExecContext(ctx, updateNavigationMenu,
		arg.Name,
		arg.Slug,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertNavigationLocation = `-- name: UpsertNavigationLocation :exec
INSERT INTO navigation_locations (location, menu_id) VALUES (?, ?)
ON CONFLICT(location) DO UPDATE SET menu_id = excluded.menu_id
`

type UpsertNavigationLocationParams struct {
	Location string `json:"location"`
	MenuID   string `json:"menu_id"`
}

func (q *Queries) UpsertNavigationLocation(ctx context.Context, arg UpsertNavigationLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertNavigationLocation, arg.Location, arg.MenuID)
	return err
}
