// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package db

import (
	"context"
	"database/sql"
)

const countPublishedEntriesByContentType = `-- name: CountPublishedEntriesByContentType :one
SELECT COUNT(*)
FROM entries e
JOIN routes rt ON rt.entry_id = e.id
WHERE e.content_type_id = ?
  AND e.status = 'active'
  AND e.published_revision_id IS NOT NULL
  AND rt.route_type = 'entry'
`

func (q *Queries) CountPublishedEntriesByContentType(ctx context.Context, contentTypeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedEntriesByContentType, contentTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublishedEntryByID = `-- name: GetPublishedEntryByID :one
SELECT
    e.id,
    e.content_type_id,
    e.slug,
    e.status,
    e.published_at,
    e.first_published_at,
    r.id AS revision_id,
    r.title,
    r.excerpt,
    r.document_json,
    r.seo_title,
    r.seo_description,
    r.canonical_url,
    r.featured_media_id,
    r.social_media_id,
    r.seo_robots_index,
    r.seo_robots_follow,
    r.schema_mode,
    r.layout_template_id
FROM entries e
JOIN entry_revisions r
    ON r.id = e.published_revision_id
WHERE e.id = ?
  AND e.status = 'active'
  AND e.published_revision_id IS NOT NULL
LIMIT 1
`

type GetPublishedEntryByIDRow struct {
	ID               string         `json:"id"`
	ContentTypeID    string         `json:"content_type_id"`
	Slug             string         `json:"slug"`
	Status           string         `json:"status"`
	PublishedAt      sql.NullInt64  `json:"published_at"`
	FirstPublishedAt sql.NullInt64  `json:"first_published_at"`
	RevisionID       string         `json:"revision_id"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	DocumentJson     string         `json:"document_json"`
	SeoTitle         sql.NullString `json:"seo_title"`
	SeoDescription   sql.NullString `json:"seo_description"`
	CanonicalUrl     sql.NullString `json:"canonical_url"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	SocialMediaID    sql.NullString `json:"social_media_id"`
	SeoRobotsIndex   sql.NullInt64  `json:"seo_robots_index"`
	SeoRobotsFollow  sql.NullInt64  `json:"seo_robots_follow"`
	SchemaMode       string         `json:"schema_mode"`
	LayoutTemplateID sql.NullString `json:"layout_template_id"`
}

func (q *Queries) GetPublishedEntryByID(ctx context.Context, id string) (GetPublishedEntryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedEntryByID, id)
	var i GetPublishedEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.FirstPublishedAt,
		&i.RevisionID,
		&i.Title,
		&i.Excerpt,
		&i.DocumentJson,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CanonicalUrl,
		&i.FeaturedMediaID,
		&i.SocialMediaID,
		&i.SeoRobotsIndex,
		&i.SeoRobotsFollow,
		&i.SchemaMode,
		&i.LayoutTemplateID,
	)
	return i, err
}

const getPublishedEntryByPath = `-- name: GetPublishedEntryByPath :one
SELECT
    e.id,
    e.content_type_id,
    e.slug,
    e.status,
    e.published_at,
    e.first_published_at,

    r.id AS revision_id,
    r.title,
    r.excerpt,
    r.document_json,
    r.seo_title,
    r.seo_description,
    r.canonical_url,
    r.featured_media_id,
    r.social_media_id,
    r.seo_robots_index,
    r.seo_robots_follow,
    r.schema_mode,
    r.layout_template_id

FROM routes rt

JOIN entries e
    ON e.id = rt.entry_id

JOIN entry_revisions r
    ON r.id = e.published_revision_id

WHERE rt.path = ?
  AND rt.route_type = 'entry'
  AND e.status = 'active'

LIMIT 1
`

type GetPublishedEntryByPathRow struct {
	ID               string         `json:"id"`
	ContentTypeID    string         `json:"content_type_id"`
	Slug             string         `json:"slug"`
	Status           string         `json:"status"`
	PublishedAt      sql.NullInt64  `json:"published_at"`
	FirstPublishedAt sql.NullInt64  `json:"first_published_at"`
	RevisionID       string         `json:"revision_id"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	DocumentJson     string         `json:"document_json"`
	SeoTitle         sql.NullString `json:"seo_title"`
	SeoDescription   sql.NullString `json:"seo_description"`
	CanonicalUrl     sql.NullString `json:"canonical_url"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	SocialMediaID    sql.NullString `json:"social_media_id"`
	SeoRobotsIndex   sql.NullInt64  `json:"seo_robots_index"`
	SeoRobotsFollow  sql.NullInt64  `json:"seo_robots_follow"`
	SchemaMode       string         `json:"schema_mode"`
	LayoutTemplateID sql.NullString `json:"layout_template_id"`
}

func (q *Queries) GetPublishedEntryByPath(ctx context.Context, path string) (GetPublishedEntryByPathRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedEntryByPath, path)
	var i GetPublishedEntryByPathRow
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.Slug,
		&i.Status,
		&i.PublishedAt,
		&i.FirstPublishedAt,
		&i.RevisionID,
		&i.Title,
		&i.Excerpt,
		&i.DocumentJson,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CanonicalUrl,
		&i.FeaturedMediaID,
		&i.SocialMediaID,
		&i.SeoRobotsIndex,
		&i.SeoRobotsFollow,
		&i.SchemaMode,
		&i.LayoutTemplateID,
	)
	return i, err
}

const listPublishedEntriesByContentType = `-- name: ListPublishedEntriesByContentType :many
SELECT
    e.id,
    e.slug,
    e.first_published_at,
    e.published_at,
    r.id AS revision_id,
    r.title,
    r.excerpt,
    r.featured_media_id,
    rt.path AS route_path
FROM entries e
JOIN entry_revisions r ON r.id = e.published_revision_id
JOIN routes rt ON rt.entry_id = e.id AND rt.route_type = 'entry'
WHERE e.content_type_id = ?
  AND e.status = 'active'
  AND e.published_revision_id IS NOT NULL
ORDER BY
    COALESCE(e.first_published_at, e.published_at) DESC,
    e.published_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedEntriesByContentTypeParams struct {
	ContentTypeID string `json:"content_type_id"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

type ListPublishedEntriesByContentTypeRow struct {
	ID               string         `json:"id"`
	Slug             string         `json:"slug"`
	FirstPublishedAt sql.NullInt64  `json:"first_published_at"`
	PublishedAt      sql.NullInt64  `json:"published_at"`
	RevisionID       string         `json:"revision_id"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	RoutePath        string         `json:"route_path"`
}

func (q *Queries) ListPublishedEntriesByContentType(ctx context.Context, arg ListPublishedEntriesByContentTypeParams) ([]ListPublishedEntriesByContentTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEntriesByContentType, arg.ContentTypeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEntriesByContentTypeRow{}
	for rows.Next() {
		var i ListPublishedEntriesByContentTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.FirstPublishedAt,
			&i.PublishedAt,
			&i.RevisionID,
			&i.Title,
			&i.Excerpt,
			&i.FeaturedMediaID,
			&i.RoutePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEntriesByContentTypeAsc = `-- name: ListPublishedEntriesByContentTypeAsc :many
SELECT
    e.id,
    e.slug,
    e.first_published_at,
    e.published_at,
    r.id AS revision_id,
    r.title,
    r.excerpt,
    r.featured_media_id,
    rt.path AS route_path
FROM entries e
JOIN entry_revisions r ON r.id = e.published_revision_id
JOIN routes rt ON rt.entry_id = e.id AND rt.route_type = 'entry'
WHERE e.content_type_id = ?
  AND e.status = 'active'
  AND e.published_revision_id IS NOT NULL
ORDER BY
    COALESCE(e.first_published_at, e.published_at) ASC,
    e.published_at ASC
LIMIT ? OFFSET ?
`

type ListPublishedEntriesByContentTypeAscParams struct {
	ContentTypeID string `json:"content_type_id"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

type ListPublishedEntriesByContentTypeAscRow struct {
	ID               string         `json:"id"`
	Slug             string         `json:"slug"`
	FirstPublishedAt sql.NullInt64  `json:"first_published_at"`
	PublishedAt      sql.NullInt64  `json:"published_at"`
	RevisionID       string         `json:"revision_id"`
	Title            string         `json:"title"`
	Excerpt          sql.NullString `json:"excerpt"`
	FeaturedMediaID  sql.NullString `json:"featured_media_id"`
	RoutePath        string         `json:"route_path"`
}

func (q *Queries) ListPublishedEntriesByContentTypeAsc(ctx context.Context, arg ListPublishedEntriesByContentTypeAscParams) ([]ListPublishedEntriesByContentTypeAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEntriesByContentTypeAsc, arg.ContentTypeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEntriesByContentTypeAscRow{}
	for rows.Next() {
		var i ListPublishedEntriesByContentTypeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.FirstPublishedAt,
			&i.PublishedAt,
			&i.RevisionID,
			&i.Title,
			&i.Excerpt,
			&i.FeaturedMediaID,
			&i.RoutePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
