// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publication_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const cancelActivePublicationJobsForEntry = `-- name: CancelActivePublicationJobsForEntry :exec
UPDATE publication_jobs SET status = 'cancelled', updated_at = ?, last_error = ?3 WHERE entry_id = ? AND status = 'scheduled'
`

type CancelActivePublicationJobsForEntryParams struct {
	UpdatedAt int64          `json:"updated_at"`
	LastError sql.NullString `json:"last_error"`
	EntryID   string         `json:"entry_id"`
}

func (q *Queries) CancelActivePublicationJobsForEntry(ctx context.Context, arg CancelActivePublicationJobsForEntryParams) error {
	_, err := q.db.ExecContext(ctx, cancelActivePublicationJobsForEntry, arg.UpdatedAt, arg.LastError, arg.EntryID)
	return err
}

const createPublicationJob = `-- name: CreatePublicationJob :exec
INSERT INTO publication_jobs (id, entry_id, revision_id, scheduled_at, status, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, 'scheduled', ?, ?, ?)
`

type CreatePublicationJobParams struct {
	ID          string         `json:"id"`
	EntryID     string         `json:"entry_id"`
	RevisionID  string         `json:"revision_id"`
	ScheduledAt int64          `json:"scheduled_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreatePublicationJob(ctx context.Context, arg CreatePublicationJobParams) error {
	_, err := q.db.ExecContext(ctx, createPublicationJob,
		arg.ID,
		arg.EntryID,
		arg.RevisionID,
		arg.ScheduledAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePublicationJobsForEntry = `-- name: DeletePublicationJobsForEntry :exec
DELETE FROM publication_jobs WHERE entry_id = ?
`

func (q *Queries) DeletePublicationJobsForEntry(ctx context.Context, entryID string) error {
	_, err := q.db.ExecContext(ctx, deletePublicationJobsForEntry, entryID)
	return err
}

const getActivePublicationJobByEntry = `-- name: GetActivePublicationJobByEntry :one
SELECT id, entry_id, revision_id, scheduled_at, status, created_by, created_at, updated_at, last_error FROM publication_jobs WHERE entry_id = ? AND status = 'scheduled' LIMIT 1
`

func (q *Queries) GetActivePublicationJobByEntry(ctx context.Context, entryID string) (PublicationJob, error) {
	row := q.db.QueryRowContext(ctx, getActivePublicationJobByEntry, entryID)
	var i PublicationJob
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RevisionID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
	)
	return i, err
}

const getPublicationJob = `-- name: GetPublicationJob :one
SELECT id, entry_id, revision_id, scheduled_at, status, created_by, created_at, updated_at, last_error FROM publication_jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetPublicationJob(ctx context.Context, id string) (PublicationJob, error) {
	row := q.db.QueryRowContext(ctx, getPublicationJob, id)
	var i PublicationJob
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RevisionID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
	)
	return i, err
}

const getPublicationJobByEntryAndRevision = `-- name: GetPublicationJobByEntryAndRevision :one
SELECT id, entry_id, revision_id, scheduled_at, status, created_by, created_at, updated_at, last_error FROM publication_jobs WHERE entry_id = ? AND revision_id = ? AND status = 'scheduled' LIMIT 1
`

type GetPublicationJobByEntryAndRevisionParams struct {
	EntryID    string `json:"entry_id"`
	RevisionID string `json:"revision_id"`
}

func (q *Queries) GetPublicationJobByEntryAndRevision(ctx context.Context, arg GetPublicationJobByEntryAndRevisionParams) (PublicationJob, error) {
	row := q.db.QueryRowContext(ctx, getPublicationJobByEntryAndRevision, arg.EntryID, arg.RevisionID)
	var i PublicationJob
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.RevisionID,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastError,
	)
	return i, err
}

const listDuePublicationJobs = `-- name: ListDuePublicationJobs :many
SELECT id, entry_id, revision_id, scheduled_at, status, created_by, created_at, updated_at, last_error FROM publication_jobs
WHERE status = 'scheduled' AND scheduled_at <= ?
ORDER BY scheduled_at ASC
`

func (q *Queries) ListDuePublicationJobs(ctx context.Context, scheduledAt int64) ([]PublicationJob, error) {
	rows, err := q.db.QueryContext(ctx, listDuePublicationJobs, scheduledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicationJob{}
	for rows.Next() {
		var i PublicationJob
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.RevisionID,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationJobsForEntry = `-- name: ListPublicationJobsForEntry :many
SELECT id, entry_id, revision_id, scheduled_at, status, created_by, created_at, updated_at, last_error FROM publication_jobs WHERE entry_id = ? ORDER BY scheduled_at DESC
`

func (q *Queries) ListPublicationJobsForEntry(ctx context.Context, entryID string) ([]PublicationJob, error) {
	rows, err := q.db.QueryContext(ctx, listPublicationJobsForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicationJob{}
	for rows.Next() {
		var i PublicationJob
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.RevisionID,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublicationJobStatus = `-- name: UpdatePublicationJobStatus :exec
UPDATE publication_jobs SET status = ?, updated_at = ?, last_error = ?4 WHERE id = ?
`

type UpdatePublicationJobStatusParams struct {
	Status    string         `json:"status"`
	UpdatedAt int64          `json:"updated_at"`
	LastError sql.NullString `json:"last_error"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdatePublicationJobStatus(ctx context.Context, arg UpdatePublicationJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePublicationJobStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.LastError,
		arg.ID,
	)
	return err
}
