// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateBlockDefinition(ctx context.Context, arg CreateBlockDefinitionParams) error
	CreateContentType(ctx context.Context, arg CreateContentTypeParams) error
	CreateEntry(ctx context.Context, arg CreateEntryParams) error
	CreateEntryRevision(ctx context.Context, arg CreateEntryRevisionParams) error
	CreateRoute(ctx context.Context, arg CreateRouteParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteEntry(ctx context.Context, id string) error
	DeleteRoute(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DisableBlockDefinition(ctx context.Context, arg DisableBlockDefinitionParams) error
	GetBlockDefinition(ctx context.Context, arg GetBlockDefinitionParams) (BlockDefinition, error)
	GetContentType(ctx context.Context, id string) (ContentType, error)
	GetEntry(ctx context.Context, id string) (Entry, error)
	GetEntryBySlug(ctx context.Context, arg GetEntryBySlugParams) (Entry, error)
	GetEntryRevision(ctx context.Context, id string) (EntryRevision, error)
	GetEntryRoute(ctx context.Context, entryID sql.NullString) (Route, error)
	GetLatestEntryRevision(ctx context.Context, entryID string) (EntryRevision, error)
	GetPublishedEntryByPath(ctx context.Context, path string) (GetPublishedEntryByPathRow, error)
	GetRouteByPath(ctx context.Context, path string) (Route, error)
	GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error)
	GetSiteSettings(ctx context.Context) (SiteSetting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	HasAdmin(ctx context.Context) (bool, error)
	ListBlockDefinitions(ctx context.Context) ([]BlockDefinition, error)
	ListContentTypes(ctx context.Context) ([]ContentType, error)
	ListEntriesByContentType(ctx context.Context, contentTypeID string) ([]ListEntriesByContentTypeRow, error)
	ListEntryRevisions(ctx context.Context, entryID string) ([]EntryRevision, error)
	ListRoutesForEntry(ctx context.Context, entryID sql.NullString) ([]Route, error)
	SeedBlockDefinition(ctx context.Context, arg SeedBlockDefinitionParams) error
	SeedEntry(ctx context.Context, arg SeedEntryParams) error
	SeedEntryRevision(ctx context.Context, arg SeedEntryRevisionParams) error
	SeedPublishedRevision(ctx context.Context, arg SeedPublishedRevisionParams) error
	SeedRoute(ctx context.Context, arg SeedRouteParams) error
	SeedSiteSettings(ctx context.Context, arg SeedSiteSettingsParams) error
	SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error
	UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) error
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) error
	UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error
	UpdateSiteTitle(ctx context.Context, arg UpdateSiteTitleParams) error
}

var _ Querier = (*Queries)(nil)
