// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CancelActivePublicationJobsForEntry(ctx context.Context, arg CancelActivePublicationJobsForEntryParams) error
	ClearContentTypeDefaultLayoutTemplate(ctx context.Context, arg ClearContentTypeDefaultLayoutTemplateParams) error
	ClearLayoutTemplatePublishedRevision(ctx context.Context, arg ClearLayoutTemplatePublishedRevisionParams) error
	ClearPublishedRevision(ctx context.Context, arg ClearPublishedRevisionParams) error
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountEntries(ctx context.Context) (int64, error)
	CountEntriesAdmin(ctx context.Context, arg CountEntriesAdminParams) (int64, error)
	CountEntriesByAdminStatus(ctx context.Context, arg CountEntriesByAdminStatusParams) (CountEntriesByAdminStatusRow, error)
	CountMedia(ctx context.Context) (int64, error)
	CountMediaUsage(ctx context.Context, id sql.NullString) (int64, error)
	CountPublishedEntriesByContentType(ctx context.Context, contentTypeID string) (int64, error)
	CountPublishedEntriesByTerm(ctx context.Context, termID string) (int64, error)
	CountTermsByTaxonomy(ctx context.Context, taxonomyID string) (int64, error)
	CreateBlockDefinition(ctx context.Context, arg CreateBlockDefinitionParams) error
	CreateContentType(ctx context.Context, arg CreateContentTypeParams) error
	CreateEntry(ctx context.Context, arg CreateEntryParams) error
	CreateEntryRevision(ctx context.Context, arg CreateEntryRevisionParams) error
	CreateLayoutTemplate(ctx context.Context, arg CreateLayoutTemplateParams) error
	CreateLayoutTemplateRevision(ctx context.Context, arg CreateLayoutTemplateRevisionParams) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateMediaVariant(ctx context.Context, arg CreateMediaVariantParams) (MediaVariant, error)
	CreateNavigationItem(ctx context.Context, arg CreateNavigationItemParams) error
	CreateNavigationMenu(ctx context.Context, arg CreateNavigationMenuParams) error
	CreatePublicationJob(ctx context.Context, arg CreatePublicationJobParams) error
	CreateRoute(ctx context.Context, arg CreateRouteParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTaxonomy(ctx context.Context, arg CreateTaxonomyParams) error
	CreateTerm(ctx context.Context, arg CreateTermParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteEntry(ctx context.Context, id string) error
	DeleteMedia(ctx context.Context, id string) error
	DeleteMediaVariant(ctx context.Context, id string) error
	DeleteNavigationItemsByMenu(ctx context.Context, menuID string) error
	DeleteNavigationLocationsForMenu(ctx context.Context, menuID string) error
	DeleteNavigationMenu(ctx context.Context, id string) error
	DeletePublicationJobsForEntry(ctx context.Context, entryID string) error
	DeleteRoute(ctx context.Context, id string) error
	DeleteRoutesByEntryID(ctx context.Context, entryID sql.NullString) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteSessionsForUser(ctx context.Context, userID string) error
	DeleteTaxonomy(ctx context.Context, id string) error
	DeleteTerm(ctx context.Context, id string) error
	DeleteTermsForRevision(ctx context.Context, revisionID string) error
	DisableBlockDefinition(ctx context.Context, arg DisableBlockDefinitionParams) error
	GetActivePublicationJobByEntry(ctx context.Context, entryID string) (PublicationJob, error)
	GetArchiveRouteByContentType(ctx context.Context, contentTypeID sql.NullString) (Route, error)
	GetBlockDefinition(ctx context.Context, arg GetBlockDefinitionParams) (BlockDefinition, error)
	GetContentType(ctx context.Context, id string) (ContentType, error)
	GetContentTypeWithDefault(ctx context.Context, id string) (ContentType, error)
	GetEntriesByIDs(ctx context.Context, arg GetEntriesByIDsParams) ([]Entry, error)
	GetEntry(ctx context.Context, id string) (Entry, error)
	GetEntryRevision(ctx context.Context, id string) (EntryRevision, error)
	GetEntryRoute(ctx context.Context, entryID sql.NullString) (Route, error)
	// NOTE: MUST NOT be used for hierarchical content types (e.g. page).
	// Public Page lookup must use routes (Route path -> Entry). This helper exists only
	// for flat content-type tests and non-hierarchical lookups; prefer route-based lookup in production.
	GetFlatEntryBySlug(ctx context.Context, arg GetFlatEntryBySlugParams) (Entry, error)
	GetLatestEntryRevision(ctx context.Context, entryID string) (EntryRevision, error)
	GetLatestLayoutTemplateRevision(ctx context.Context, templateID string) (LayoutTemplateRevision, error)
	GetLayoutTemplate(ctx context.Context, id string) (LayoutTemplate, error)
	GetLayoutTemplateRevision(ctx context.Context, id string) (LayoutTemplateRevision, error)
	GetLayoutTemplateWithPublishedRevision(ctx context.Context, id string) (GetLayoutTemplateWithPublishedRevisionRow, error)
	GetMedia(ctx context.Context, id string) (Medium, error)
	GetMediaVariant(ctx context.Context, arg GetMediaVariantParams) (MediaVariant, error)
	GetNavigationMenu(ctx context.Context, id string) (NavigationMenu, error)
	GetNavigationMenuBySlug(ctx context.Context, slug string) (NavigationMenu, error)
	GetPublicationJob(ctx context.Context, id string) (PublicationJob, error)
	GetPublicationJobByEntryAndRevision(ctx context.Context, arg GetPublicationJobByEntryAndRevisionParams) (PublicationJob, error)
	GetPublishedEntryByID(ctx context.Context, id string) (GetPublishedEntryByIDRow, error)
	GetPublishedEntryByPath(ctx context.Context, path string) (GetPublishedEntryByPathRow, error)
	GetPublishedLayoutTemplateRevision(ctx context.Context, id string) (LayoutTemplateRevision, error)
	GetRouteByPath(ctx context.Context, path string) (Route, error)
	GetRouteByPathAndType(ctx context.Context, arg GetRouteByPathAndTypeParams) (Route, error)
	GetRouteByTaxonomyTerm(ctx context.Context, arg GetRouteByTaxonomyTermParams) (Route, error)
	GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error)
	GetSiteIconMediaID(ctx context.Context) (sql.NullString, error)
	GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error)
	GetSiteSocialMediaID(ctx context.Context) (sql.NullString, error)
	GetTaxonomy(ctx context.Context, id string) (Taxonomy, error)
	GetTerm(ctx context.Context, id string) (Term, error)
	GetTermArchiveRoute(ctx context.Context, arg GetTermArchiveRouteParams) (Route, error)
	GetTermBySlug(ctx context.Context, arg GetTermBySlugParams) (Term, error)
	GetTermByTaxonomyAndSlug(ctx context.Context, arg GetTermByTaxonomyAndSlugParams) (Term, error)
	GetThemeCustomization(ctx context.Context, themeID string) (ThemeCustomization, error)
	GetTwitterSite(ctx context.Context) (string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	HasAdmin(ctx context.Context) (bool, error)
	ListArchiveRoutes(ctx context.Context) ([]Route, error)
	ListBlockDefinitions(ctx context.Context) ([]BlockDefinition, error)
	ListChildTerms(ctx context.Context, parentID sql.NullString) ([]Term, error)
	ListContentTypes(ctx context.Context) ([]ContentType, error)
	ListDuePublicationJobs(ctx context.Context, scheduledAt int64) ([]PublicationJob, error)
	ListEntriesAdmin(ctx context.Context, arg ListEntriesAdminParams) ([]ListEntriesAdminRow, error)
	ListEntriesByContentType(ctx context.Context, contentTypeID string) ([]ListEntriesByContentTypeRow, error)
	ListEntryRevisions(ctx context.Context, entryID string) ([]EntryRevision, error)
	ListEntryRouteVisibilities(ctx context.Context) ([]ListEntryRouteVisibilitiesRow, error)
	ListLatestHierarchyForContentType(ctx context.Context, contentTypeID string) ([]ListLatestHierarchyForContentTypeRow, error)
	ListLatestLayoutRevisions(ctx context.Context) ([]LayoutTemplateRevision, error)
	ListLayoutTemplateRevisions(ctx context.Context, templateID string) ([]LayoutTemplateRevision, error)
	ListLayoutTemplates(ctx context.Context) ([]LayoutTemplate, error)
	ListLayoutTemplatesByContentType(ctx context.Context, contentTypeID string) ([]LayoutTemplate, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	ListMediaVariants(ctx context.Context, mediaID string) ([]MediaVariant, error)
	ListNavigationItemsByMenu(ctx context.Context, menuID string) ([]ListNavigationItemsByMenuRow, error)
	ListNavigationLocations(ctx context.Context) ([]NavigationLocation, error)
	ListNavigationLocationsForMenu(ctx context.Context, menuID string) ([]string, error)
	ListNavigationMenus(ctx context.Context) ([]NavigationMenu, error)
	ListPublicationJobsForEntry(ctx context.Context, entryID string) ([]PublicationJob, error)
	ListPublishedEntriesByContentType(ctx context.Context, arg ListPublishedEntriesByContentTypeParams) ([]ListPublishedEntriesByContentTypeRow, error)
	ListPublishedEntriesByContentTypeAsc(ctx context.Context, arg ListPublishedEntriesByContentTypeAscParams) ([]ListPublishedEntriesByContentTypeAscRow, error)
	ListPublishedEntriesByTerm(ctx context.Context, arg ListPublishedEntriesByTermParams) ([]ListPublishedEntriesByTermRow, error)
	ListPublishedEntriesByTermAsc(ctx context.Context, arg ListPublishedEntriesByTermAscParams) ([]ListPublishedEntriesByTermAscRow, error)
	ListPublishedEntriesByTermCount(ctx context.Context, arg ListPublishedEntriesByTermCountParams) (int64, error)
	ListPublishedEntriesForNavigation(ctx context.Context) ([]ListPublishedEntriesForNavigationRow, error)
	ListPublishedHierarchyForContentType(ctx context.Context, contentTypeID string) ([]ListPublishedHierarchyForContentTypeRow, error)
	ListPublishedLayoutTemplatesByContentType(ctx context.Context, contentTypeID string) ([]LayoutTemplate, error)
	ListPublishedPagesForNavigation(ctx context.Context) ([]ListPublishedPagesForNavigationRow, error)
	// Every redirect route whose target is the given path. Slug changes use this to
	// flatten redirect chains: when /a -> /b exists and /b moves to /c, this query
	// finds /a so it can be retargeted straight to /c.
	ListRedirectsToTarget(ctx context.Context, redirectTo sql.NullString) ([]Route, error)
	ListRoutes(ctx context.Context) ([]Route, error)
	ListRoutesForEntry(ctx context.Context, entryID sql.NullString) ([]Route, error)
	ListSitemapArchiveRoutes(ctx context.Context) ([]string, error)
	// Returns every URL that belongs in the sitemap: published and active entries
	// of public content types that own an entry-type route and resolve as
	// indexable. Drafts (no published revision), private/trash entries,
	// private/password visibility, non-public content types, redirect/system routes,
	// admin/preview URLs and noindex revisions are all excluded by the joins and filters below.
	// <lastmod> comes from the published revision timestamp, so a newer draft
	// never changes the sitemap.
	ListSitemapEntries(ctx context.Context) ([]ListSitemapEntriesRow, error)
	ListTaxonomies(ctx context.Context) ([]Taxonomy, error)
	ListTaxonomiesByContentType(ctx context.Context, contentTypeID string) ([]Taxonomy, error)
	ListTaxonomyArchiveRoutes(ctx context.Context) ([]Route, error)
	ListTermIDsForRevision(ctx context.Context, revisionID string) ([]string, error)
	ListTermsByTaxonomy(ctx context.Context, taxonomyID string) ([]Term, error)
	ListTermsByTaxonomyWithCounts(ctx context.Context, taxonomyID string) ([]ListTermsByTaxonomyWithCountsRow, error)
	ListTermsForRevision(ctx context.Context, revisionID string) ([]Term, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MoveEntryToTrash(ctx context.Context, arg MoveEntryToTrashParams) error
	RestoreEntryFromTrash(ctx context.Context, arg RestoreEntryFromTrashParams) error
	SearchTermsByTaxonomy(ctx context.Context, arg SearchTermsByTaxonomyParams) ([]Term, error)
	SeedArchiveRoute(ctx context.Context, arg SeedArchiveRouteParams) error
	SeedEntry(ctx context.Context, arg SeedEntryParams) error
	SeedEntryRevision(ctx context.Context, arg SeedEntryRevisionParams) error
	SeedEntryWithLayout(ctx context.Context, arg SeedEntryWithLayoutParams) error
	SeedNavigationItem(ctx context.Context, arg SeedNavigationItemParams) error
	SeedNavigationLocation(ctx context.Context, arg SeedNavigationLocationParams) error
	SeedNavigationMenu(ctx context.Context, arg SeedNavigationMenuParams) error
	SeedPublishedRevision(ctx context.Context, arg SeedPublishedRevisionParams) error
	SeedRoute(ctx context.Context, arg SeedRouteParams) error
	SeedSiteSettings(ctx context.Context, arg SeedSiteSettingsParams) error
	SetContentTypeDefaultLayoutTemplate(ctx context.Context, arg SetContentTypeDefaultLayoutTemplateParams) error
	// Records the FIRST publication of an Entry. Later re-publishes must never
	// move it: structured data uses it as the stable datePublished.
	SetFirstPublishedAtIfNull(ctx context.Context, arg SetFirstPublishedAtIfNullParams) error
	SetLayoutTemplatePublishedRevision(ctx context.Context, arg SetLayoutTemplatePublishedRevisionParams) error
	SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error
	SetTermsForRevision(ctx context.Context, arg SetTermsForRevisionParams) error
	UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) error
	UpdateEntryProjection(ctx context.Context, arg UpdateEntryProjectionParams) error
	UpdateGeneralSettings(ctx context.Context, arg UpdateGeneralSettingsParams) error
	UpdateLayoutTemplate(ctx context.Context, arg UpdateLayoutTemplateParams) error
	UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) error
	UpdateNavigationMenu(ctx context.Context, arg UpdateNavigationMenuParams) error
	UpdatePerformanceSettings(ctx context.Context, arg UpdatePerformanceSettingsParams) error
	UpdatePublicationJobStatus(ctx context.Context, arg UpdatePublicationJobStatusParams) error
	UpdateReadingSettings(ctx context.Context, arg UpdateReadingSettingsParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) error
	UpdateSEOSettings(ctx context.Context, arg UpdateSEOSettingsParams) error
	UpdateSiteIconMediaID(ctx context.Context, siteIconMediaID sql.NullString) error
	UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error
	UpdateSiteSocialMediaID(ctx context.Context, siteSocialMediaID sql.NullString) error
	UpdateSiteTitle(ctx context.Context, arg UpdateSiteTitleParams) error
	UpdateTaxonomy(ctx context.Context, arg UpdateTaxonomyParams) error
	UpdateTerm(ctx context.Context, arg UpdateTermParams) error
	UpdateTwitterSite(ctx context.Context, twitterSite string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpsertNavigationLocation(ctx context.Context, arg UpsertNavigationLocationParams) error
	UpsertThemeCustomization(ctx context.Context, arg UpsertThemeCustomizationParams) error
}

var _ Querier = (*Queries)(nil)
