// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountMedia(ctx context.Context) (int64, error)
	CountMediaUsage(ctx context.Context, id sql.NullString) (int64, error)
	CountPublishedEntriesByContentType(ctx context.Context, contentTypeID string) (int64, error)
	CreateBlockDefinition(ctx context.Context, arg CreateBlockDefinitionParams) error
	CreateContentType(ctx context.Context, arg CreateContentTypeParams) error
	CreateEntry(ctx context.Context, arg CreateEntryParams) error
	CreateEntryRevision(ctx context.Context, arg CreateEntryRevisionParams) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateMediaVariant(ctx context.Context, arg CreateMediaVariantParams) (MediaVariant, error)
	CreateNavigationItem(ctx context.Context, arg CreateNavigationItemParams) error
	CreateNavigationMenu(ctx context.Context, arg CreateNavigationMenuParams) error
	CreateRoute(ctx context.Context, arg CreateRouteParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteEntry(ctx context.Context, id string) error
	DeleteMedia(ctx context.Context, id string) error
	DeleteMediaVariant(ctx context.Context, id string) error
	DeleteNavigationItemsByMenu(ctx context.Context, menuID string) error
	DeleteNavigationLocationsForMenu(ctx context.Context, menuID string) error
	DeleteNavigationMenu(ctx context.Context, id string) error
	DeleteRoute(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DisableBlockDefinition(ctx context.Context, arg DisableBlockDefinitionParams) error
	GetBlockDefinition(ctx context.Context, arg GetBlockDefinitionParams) (BlockDefinition, error)
	GetContentType(ctx context.Context, id string) (ContentType, error)
	GetEntry(ctx context.Context, id string) (Entry, error)
	GetEntryBySlug(ctx context.Context, arg GetEntryBySlugParams) (Entry, error)
	GetEntryRevision(ctx context.Context, id string) (EntryRevision, error)
	GetEntryRoute(ctx context.Context, entryID sql.NullString) (Route, error)
	GetLatestEntryRevision(ctx context.Context, entryID string) (EntryRevision, error)
	GetMedia(ctx context.Context, id string) (Medium, error)
	GetMediaVariant(ctx context.Context, arg GetMediaVariantParams) (MediaVariant, error)
	GetNavigationMenu(ctx context.Context, id string) (NavigationMenu, error)
	GetNavigationMenuBySlug(ctx context.Context, slug string) (NavigationMenu, error)
	GetPublishedEntryByPath(ctx context.Context, path string) (GetPublishedEntryByPathRow, error)
	GetRouteByPath(ctx context.Context, path string) (Route, error)
	GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error)
	GetSiteIconMediaID(ctx context.Context) (sql.NullString, error)
	GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error)
	GetSiteSocialMediaID(ctx context.Context) (sql.NullString, error)
	GetThemeCustomization(ctx context.Context, themeID string) (ThemeCustomization, error)
	GetTwitterSite(ctx context.Context) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	HasAdmin(ctx context.Context) (bool, error)
	ListBlockDefinitions(ctx context.Context) ([]BlockDefinition, error)
	ListContentTypes(ctx context.Context) ([]ContentType, error)
	ListEntriesByContentType(ctx context.Context, contentTypeID string) ([]ListEntriesByContentTypeRow, error)
	ListEntryRevisions(ctx context.Context, entryID string) ([]EntryRevision, error)
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	ListMediaVariants(ctx context.Context, mediaID string) ([]MediaVariant, error)
	ListNavigationItemsByMenu(ctx context.Context, menuID string) ([]ListNavigationItemsByMenuRow, error)
	ListNavigationLocations(ctx context.Context) ([]NavigationLocation, error)
	ListNavigationLocationsForMenu(ctx context.Context, menuID string) ([]string, error)
	ListNavigationMenus(ctx context.Context) ([]NavigationMenu, error)
	ListPublishedEntriesByContentType(ctx context.Context, arg ListPublishedEntriesByContentTypeParams) ([]ListPublishedEntriesByContentTypeRow, error)
	ListPublishedPagesForNavigation(ctx context.Context) ([]ListPublishedPagesForNavigationRow, error)
	// Every redirect route whose target is the given path. Slug changes use this to
	// flatten redirect chains: when /a -> /b exists and /b moves to /c, this query
	// finds /a so it can be retargeted straight to /c.
	ListRedirectsToTarget(ctx context.Context, redirectTo sql.NullString) ([]Route, error)
	ListRoutesForEntry(ctx context.Context, entryID sql.NullString) ([]Route, error)
	// Returns every URL that belongs in the sitemap: published and active entries
	// of public content types that own an entry-type route and resolve as
	// indexable. Drafts (no published revision), private/trash entries,
	// non-public content types, redirect/system routes, admin/preview URLs and
	// noindex revisions are all excluded by the joins and filters below.
	// <lastmod> comes from the published revision timestamp, so a newer draft
	// never changes the sitemap.
	ListSitemapEntries(ctx context.Context) ([]ListSitemapEntriesRow, error)
	SeedEntry(ctx context.Context, arg SeedEntryParams) error
	SeedEntryRevision(ctx context.Context, arg SeedEntryRevisionParams) error
	SeedPublishedRevision(ctx context.Context, arg SeedPublishedRevisionParams) error
	SeedRoute(ctx context.Context, arg SeedRouteParams) error
	SeedSiteSettings(ctx context.Context, arg SeedSiteSettingsParams) error
	// Records the FIRST publication of an Entry. Later re-publishes must never
	// move it: structured data uses it as the stable datePublished.
	SetFirstPublishedAtIfNull(ctx context.Context, arg SetFirstPublishedAtIfNullParams) error
	SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error
	UpdateContentType(ctx context.Context, arg UpdateContentTypeParams) error
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) error
	UpdateMediaMetadata(ctx context.Context, arg UpdateMediaMetadataParams) error
	UpdateNavigationMenu(ctx context.Context, arg UpdateNavigationMenuParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) error
	UpdateSiteIconMediaID(ctx context.Context, siteIconMediaID sql.NullString) error
	UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error
	UpdateSiteSocialMediaID(ctx context.Context, siteSocialMediaID sql.NullString) error
	UpdateSiteTitle(ctx context.Context, arg UpdateSiteTitleParams) error
	UpdateTwitterSite(ctx context.Context, twitterSite string) error
	UpsertNavigationLocation(ctx context.Context, arg UpsertNavigationLocationParams) error
	UpsertThemeCustomization(ctx context.Context, arg UpsertThemeCustomizationParams) error
}

var _ Querier = (*Queries)(nil)
