// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
	"database/sql"
)

const createRoute = `-- name: CreateRoute :exec
INSERT INTO routes (
    id, path, entry_id, route_type, content_type_id, taxonomy_id, term_id, redirect_to, redirect_status, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRouteParams struct {
	ID             string         `json:"id"`
	Path           string         `json:"path"`
	EntryID        sql.NullString `json:"entry_id"`
	RouteType      string         `json:"route_type"`
	ContentTypeID  sql.NullString `json:"content_type_id"`
	TaxonomyID     sql.NullString `json:"taxonomy_id"`
	TermID         sql.NullString `json:"term_id"`
	RedirectTo     sql.NullString `json:"redirect_to"`
	RedirectStatus sql.NullInt64  `json:"redirect_status"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) error {
	_, err := q.db.ExecContext(ctx, createRoute,
		arg.ID,
		arg.Path,
		arg.EntryID,
		arg.RouteType,
		arg.ContentTypeID,
		arg.TaxonomyID,
		arg.TermID,
		arg.RedirectTo,
		arg.RedirectStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, id)
	return err
}

const getArchiveRouteByContentType = `-- name: GetArchiveRouteByContentType :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE route_type = 'archive' AND content_type_id = ?
LIMIT 1
`

func (q *Queries) GetArchiveRouteByContentType(ctx context.Context, contentTypeID sql.NullString) (Route, error) {
	row := q.db.QueryRowContext(ctx, getArchiveRouteByContentType, contentTypeID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
	)
	return i, err
}

const getEntryRoute = `-- name: GetEntryRoute :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE entry_id = ?
  AND route_type = 'entry'
ORDER BY path
LIMIT 1
`

func (q *Queries) GetEntryRoute(ctx context.Context, entryID sql.NullString) (Route, error) {
	row := q.db.QueryRowContext(ctx, getEntryRoute, entryID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
	)
	return i, err
}

const getRouteByPath = `-- name: GetRouteByPath :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE path = ?
LIMIT 1
`

func (q *Queries) GetRouteByPath(ctx context.Context, path string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByPath, path)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
	)
	return i, err
}

const getRouteByPathAndType = `-- name: GetRouteByPathAndType :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE path = ? AND route_type = ?
LIMIT 1
`

type GetRouteByPathAndTypeParams struct {
	Path      string `json:"path"`
	RouteType string `json:"route_type"`
}

func (q *Queries) GetRouteByPathAndType(ctx context.Context, arg GetRouteByPathAndTypeParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByPathAndType, arg.Path, arg.RouteType)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
	)
	return i, err
}

const getRouteByTaxonomyTerm = `-- name: GetRouteByTaxonomyTerm :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id FROM routes WHERE taxonomy_id = ? AND term_id = ? LIMIT 1
`

type GetRouteByTaxonomyTermParams struct {
	TaxonomyID sql.NullString `json:"taxonomy_id"`
	TermID     sql.NullString `json:"term_id"`
}

func (q *Queries) GetRouteByTaxonomyTerm(ctx context.Context, arg GetRouteByTaxonomyTermParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByTaxonomyTerm, arg.TaxonomyID, arg.TermID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
	)
	return i, err
}

const getTermArchiveRoute = `-- name: GetTermArchiveRoute :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id FROM routes WHERE taxonomy_id = ? AND term_id = ? AND route_type = 'archive' LIMIT 1
`

type GetTermArchiveRouteParams struct {
	TaxonomyID sql.NullString `json:"taxonomy_id"`
	TermID     sql.NullString `json:"term_id"`
}

func (q *Queries) GetTermArchiveRoute(ctx context.Context, arg GetTermArchiveRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, getTermArchiveRoute, arg.TaxonomyID, arg.TermID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTypeID,
		&i.TaxonomyID,
		&i.TermID,
	)
	return i, err
}

const listArchiveRoutes = `-- name: ListArchiveRoutes :many
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE route_type = 'archive'
ORDER BY path
`

func (q *Queries) ListArchiveRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.EntryID,
			&i.RouteType,
			&i.RedirectTo,
			&i.RedirectStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryRouteVisibilities = `-- name: ListEntryRouteVisibilities :many
SELECT entries.id AS entry_id, entry_revisions.visibility AS visibility, entries.published_revision_id AS published_revision_id
FROM entries
JOIN entry_revisions ON entry_revisions.id = entries.published_revision_id
WHERE entries.published_revision_id IS NOT NULL
`

type ListEntryRouteVisibilitiesRow struct {
	EntryID             string         `json:"entry_id"`
	Visibility          string         `json:"visibility"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
}

func (q *Queries) ListEntryRouteVisibilities(ctx context.Context) ([]ListEntryRouteVisibilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntryRouteVisibilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntryRouteVisibilitiesRow{}
	for rows.Next() {
		var i ListEntryRouteVisibilitiesRow
		if err := rows.Scan(&i.EntryID, &i.Visibility, &i.PublishedRevisionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedirectsToTarget = `-- name: ListRedirectsToTarget :many
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE route_type = 'redirect'
  AND redirect_to = ?
`

// Every redirect route whose target is the given path. Slug changes use this to
// flatten redirect chains: when /a -> /b exists and /b moves to /c, this query
// finds /a so it can be retargeted straight to /c.
func (q *Queries) ListRedirectsToTarget(ctx context.Context, redirectTo sql.NullString) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRedirectsToTarget, redirectTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.EntryID,
			&i.RouteType,
			&i.RedirectTo,
			&i.RedirectStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id FROM routes ORDER BY path
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.EntryID,
			&i.RouteType,
			&i.RedirectTo,
			&i.RedirectStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesForEntry = `-- name: ListRoutesForEntry :many
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id
FROM routes
WHERE entry_id = ?
ORDER BY path
`

func (q *Queries) ListRoutesForEntry(ctx context.Context, entryID sql.NullString) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutesForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.EntryID,
			&i.RouteType,
			&i.RedirectTo,
			&i.RedirectStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxonomyArchiveRoutes = `-- name: ListTaxonomyArchiveRoutes :many
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at, content_type_id, taxonomy_id, term_id FROM routes WHERE route_type = 'archive' AND taxonomy_id IS NOT NULL ORDER BY path
`

func (q *Queries) ListTaxonomyArchiveRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listTaxonomyArchiveRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.EntryID,
			&i.RouteType,
			&i.RedirectTo,
			&i.RedirectStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentTypeID,
			&i.TaxonomyID,
			&i.TermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :exec
UPDATE routes
SET path = ?, entry_id = ?, route_type = ?, content_type_id = ?, taxonomy_id = ?, term_id = ?, redirect_to = ?, redirect_status = ?, updated_at = ?
WHERE id = ?
`

type UpdateRouteParams struct {
	Path           string         `json:"path"`
	EntryID        sql.NullString `json:"entry_id"`
	RouteType      string         `json:"route_type"`
	ContentTypeID  sql.NullString `json:"content_type_id"`
	TaxonomyID     sql.NullString `json:"taxonomy_id"`
	TermID         sql.NullString `json:"term_id"`
	RedirectTo     sql.NullString `json:"redirect_to"`
	RedirectStatus sql.NullInt64  `json:"redirect_status"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateRoute,
		arg.Path,
		arg.EntryID,
		arg.RouteType,
		arg.ContentTypeID,
		arg.TaxonomyID,
		arg.TermID,
		arg.RedirectTo,
		arg.RedirectStatus,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
