// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
	"database/sql"
)

const createRoute = `-- name: CreateRoute :exec
INSERT INTO routes (
    id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRouteParams struct {
	ID             string         `json:"id"`
	Path           string         `json:"path"`
	EntryID        sql.NullString `json:"entry_id"`
	RouteType      string         `json:"route_type"`
	RedirectTo     sql.NullString `json:"redirect_to"`
	RedirectStatus sql.NullInt64  `json:"redirect_status"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) error {
	_, err := q.db.ExecContext(ctx, createRoute,
		arg.ID,
		arg.Path,
		arg.EntryID,
		arg.RouteType,
		arg.RedirectTo,
		arg.RedirectStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, id)
	return err
}

const getRouteByPath = `-- name: GetRouteByPath :one
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at
FROM routes
WHERE path = ?
LIMIT 1
`

func (q *Queries) GetRouteByPath(ctx context.Context, path string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByPath, path)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.EntryID,
		&i.RouteType,
		&i.RedirectTo,
		&i.RedirectStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutesForEntry = `-- name: ListRoutesForEntry :many
SELECT id, path, entry_id, route_type, redirect_to, redirect_status, created_at, updated_at
FROM routes
WHERE entry_id = ?
ORDER BY path
`

func (q *Queries) ListRoutesForEntry(ctx context.Context, entryID sql.NullString) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutesForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.EntryID,
			&i.RouteType,
			&i.RedirectTo,
			&i.RedirectStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :exec
UPDATE routes
SET path = ?, entry_id = ?, route_type = ?, redirect_to = ?, redirect_status = ?, updated_at = ?
WHERE id = ?
`

type UpdateRouteParams struct {
	Path           string         `json:"path"`
	EntryID        sql.NullString `json:"entry_id"`
	RouteType      string         `json:"route_type"`
	RedirectTo     sql.NullString `json:"redirect_to"`
	RedirectStatus sql.NullInt64  `json:"redirect_status"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateRoute,
		arg.Path,
		arg.EntryID,
		arg.RouteType,
		arg.RedirectTo,
		arg.RedirectStatus,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
