// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package db

import (
	"context"
	"database/sql"
)

const countEntries = `-- name: CountEntries :one
SELECT COUNT(*) FROM entries
`

func (q *Queries) CountEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const seedArchiveRoute = `-- name: SeedArchiveRoute :exec
INSERT INTO routes (id, path, entry_id, route_type, content_type_id, created_at, updated_at)
VALUES (?, ?, ?, 'archive', ?, ?, ?)
ON CONFLICT(path) DO NOTHING
`

type SeedArchiveRouteParams struct {
	ID            string         `json:"id"`
	Path          string         `json:"path"`
	EntryID       sql.NullString `json:"entry_id"`
	ContentTypeID sql.NullString `json:"content_type_id"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) SeedArchiveRoute(ctx context.Context, arg SeedArchiveRouteParams) error {
	_, err := q.db.ExecContext(ctx, seedArchiveRoute,
		arg.ID,
		arg.Path,
		arg.EntryID,
		arg.ContentTypeID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedEntry = `-- name: SeedEntry :exec
INSERT INTO entries (
    id, content_type_id, slug, status, created_at, updated_at, published_at
)
VALUES (?, ?, ?, 'active', ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type SeedEntryParams struct {
	ID            string        `json:"id"`
	ContentTypeID string        `json:"content_type_id"`
	Slug          string        `json:"slug"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
	PublishedAt   sql.NullInt64 `json:"published_at"`
}

func (q *Queries) SeedEntry(ctx context.Context, arg SeedEntryParams) error {
	_, err := q.db.ExecContext(ctx, seedEntry,
		arg.ID,
		arg.ContentTypeID,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	return err
}

const seedEntryRevision = `-- name: SeedEntryRevision :exec
INSERT INTO entry_revisions (
    id, entry_id, revision_number, title, excerpt, document_json,
    seo_title, seo_description, created_at
)
VALUES (?, ?, 1, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type SeedEntryRevisionParams struct {
	ID             string         `json:"id"`
	EntryID        string         `json:"entry_id"`
	Title          string         `json:"title"`
	Excerpt        sql.NullString `json:"excerpt"`
	DocumentJson   string         `json:"document_json"`
	SeoTitle       sql.NullString `json:"seo_title"`
	SeoDescription sql.NullString `json:"seo_description"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) SeedEntryRevision(ctx context.Context, arg SeedEntryRevisionParams) error {
	_, err := q.db.ExecContext(ctx, seedEntryRevision,
		arg.ID,
		arg.EntryID,
		arg.Title,
		arg.Excerpt,
		arg.DocumentJson,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.CreatedAt,
	)
	return err
}

const seedEntryWithLayout = `-- name: SeedEntryWithLayout :exec
INSERT INTO entries (id, content_type_id, slug, status, created_at, updated_at, published_at)
VALUES (?, ?, ?, 'active', ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type SeedEntryWithLayoutParams struct {
	ID            string        `json:"id"`
	ContentTypeID string        `json:"content_type_id"`
	Slug          string        `json:"slug"`
	CreatedAt     int64         `json:"created_at"`
	UpdatedAt     int64         `json:"updated_at"`
	PublishedAt   sql.NullInt64 `json:"published_at"`
}

func (q *Queries) SeedEntryWithLayout(ctx context.Context, arg SeedEntryWithLayoutParams) error {
	_, err := q.db.ExecContext(ctx, seedEntryWithLayout,
		arg.ID,
		arg.ContentTypeID,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PublishedAt,
	)
	return err
}

const seedNavigationItem = `-- name: SeedNavigationItem :exec
INSERT INTO navigation_items (id, menu_id, parent_id, position, label, target_type, entry_id, url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type SeedNavigationItemParams struct {
	ID         string         `json:"id"`
	MenuID     string         `json:"menu_id"`
	ParentID   sql.NullString `json:"parent_id"`
	Position   int64          `json:"position"`
	Label      string         `json:"label"`
	TargetType string         `json:"target_type"`
	EntryID    sql.NullString `json:"entry_id"`
	Url        sql.NullString `json:"url"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) SeedNavigationItem(ctx context.Context, arg SeedNavigationItemParams) error {
	_, err := q.db.ExecContext(ctx, seedNavigationItem,
		arg.ID,
		arg.MenuID,
		arg.ParentID,
		arg.Position,
		arg.Label,
		arg.TargetType,
		arg.EntryID,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedNavigationLocation = `-- name: SeedNavigationLocation :exec
INSERT INTO navigation_locations (location, menu_id)
VALUES (?, ?)
ON CONFLICT(location) DO NOTHING
`

type SeedNavigationLocationParams struct {
	Location string `json:"location"`
	MenuID   string `json:"menu_id"`
}

func (q *Queries) SeedNavigationLocation(ctx context.Context, arg SeedNavigationLocationParams) error {
	_, err := q.db.ExecContext(ctx, seedNavigationLocation, arg.Location, arg.MenuID)
	return err
}

const seedNavigationMenu = `-- name: SeedNavigationMenu :exec
INSERT INTO navigation_menus (id, name, slug, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type SeedNavigationMenuParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SeedNavigationMenu(ctx context.Context, arg SeedNavigationMenuParams) error {
	_, err := q.db.ExecContext(ctx, seedNavigationMenu,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedPublishedRevision = `-- name: SeedPublishedRevision :exec
UPDATE entries
SET published_revision_id = ?, published_at = ?, first_published_at = ?, updated_at = ?
WHERE id = ?
  AND published_revision_id IS NULL
`

type SeedPublishedRevisionParams struct {
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	PublishedAt         sql.NullInt64  `json:"published_at"`
	FirstPublishedAt    sql.NullInt64  `json:"first_published_at"`
	UpdatedAt           int64          `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) SeedPublishedRevision(ctx context.Context, arg SeedPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, seedPublishedRevision,
		arg.PublishedRevisionID,
		arg.PublishedAt,
		arg.FirstPublishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const seedRoute = `-- name: SeedRoute :exec
INSERT INTO routes (
    id, path, entry_id, route_type, created_at, updated_at
)
VALUES (?, ?, ?, 'entry', ?, ?)
ON CONFLICT(path) DO NOTHING
`

type SeedRouteParams struct {
	ID        string         `json:"id"`
	Path      string         `json:"path"`
	EntryID   sql.NullString `json:"entry_id"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

func (q *Queries) SeedRoute(ctx context.Context, arg SeedRouteParams) error {
	_, err := q.db.ExecContext(ctx, seedRoute,
		arg.ID,
		arg.Path,
		arg.EntryID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedSiteSettings = `-- name: SeedSiteSettings :exec
UPDATE site_settings
SET
    site_title = 'StratumCMS',
    site_tagline = 'A modern self-hosted CMS',
    homepage_mode = 'page',
    homepage_entry_id = ?,
    posts_page_entry_id = ?,
    posts_base_path = ?,
    updated_at = ?
WHERE id = 1
  AND homepage_entry_id IS NULL
`

type SeedSiteSettingsParams struct {
	HomepageEntryID  sql.NullString `json:"homepage_entry_id"`
	PostsPageEntryID sql.NullString `json:"posts_page_entry_id"`
	PostsBasePath    string         `json:"posts_base_path"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) SeedSiteSettings(ctx context.Context, arg SeedSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, seedSiteSettings,
		arg.HomepageEntryID,
		arg.PostsPageEntryID,
		arg.PostsBasePath,
		arg.UpdatedAt,
	)
	return err
}
