// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_settings.sql

package db

import (
	"context"
	"database/sql"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, site_title, site_tagline, homepage_mode, homepage_entry_id, posts_page_entry_id, posts_per_page, language, timezone, active_theme, indexing_enabled, created_at, updated_at
FROM site_settings
WHERE id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.SiteTitle,
		&i.SiteTagline,
		&i.HomepageMode,
		&i.HomepageEntryID,
		&i.PostsPageEntryID,
		&i.PostsPerPage,
		&i.Language,
		&i.Timezone,
		&i.ActiveTheme,
		&i.IndexingEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteSettings = `-- name: UpdateSiteSettings :exec
UPDATE site_settings
SET
    site_title = ?,
    site_tagline = ?,
    homepage_mode = ?,
    homepage_entry_id = ?,
    posts_page_entry_id = ?,
    posts_per_page = ?,
    language = ?,
    timezone = ?,
    active_theme = ?,
    indexing_enabled = ?,
    updated_at = ?
WHERE id = 1
`

type UpdateSiteSettingsParams struct {
	SiteTitle        string         `json:"site_title"`
	SiteTagline      string         `json:"site_tagline"`
	HomepageMode     string         `json:"homepage_mode"`
	HomepageEntryID  sql.NullString `json:"homepage_entry_id"`
	PostsPageEntryID sql.NullString `json:"posts_page_entry_id"`
	PostsPerPage     int64          `json:"posts_per_page"`
	Language         string         `json:"language"`
	Timezone         string         `json:"timezone"`
	ActiveTheme      string         `json:"active_theme"`
	IndexingEnabled  int64          `json:"indexing_enabled"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteSettings,
		arg.SiteTitle,
		arg.SiteTagline,
		arg.HomepageMode,
		arg.HomepageEntryID,
		arg.PostsPageEntryID,
		arg.PostsPerPage,
		arg.Language,
		arg.Timezone,
		arg.ActiveTheme,
		arg.IndexingEnabled,
		arg.UpdatedAt,
	)
	return err
}
