// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_parts.sql

package db

import (
	"context"
	"database/sql"
)

const clearSitePartLocation = `-- name: ClearSitePartLocation :exec
DELETE FROM site_part_locations
WHERE location = ?
`

func (q *Queries) ClearSitePartLocation(ctx context.Context, location string) error {
	_, err := q.db.ExecContext(ctx, clearSitePartLocation, location)
	return err
}

const clearSitePartPublishedRevision = `-- name: ClearSitePartPublishedRevision :exec
UPDATE site_parts
SET published_revision_id = NULL, updated_at = ?
WHERE id = ?
`

type ClearSitePartPublishedRevisionParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearSitePartPublishedRevision(ctx context.Context, arg ClearSitePartPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, clearSitePartPublishedRevision, arg.UpdatedAt, arg.ID)
	return err
}

const createSitePart = `-- name: CreateSitePart :exec
INSERT INTO site_parts (id, name, published_revision_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSitePartParams struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
}

func (q *Queries) CreateSitePart(ctx context.Context, arg CreateSitePartParams) error {
	_, err := q.db.ExecContext(ctx, createSitePart,
		arg.ID,
		arg.Name,
		arg.PublishedRevisionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSitePartRevision = `-- name: CreateSitePartRevision :exec
INSERT INTO site_part_revisions (id, site_part_id, revision_number, document_json, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateSitePartRevisionParams struct {
	ID             string         `json:"id"`
	SitePartID     string         `json:"site_part_id"`
	RevisionNumber int64          `json:"revision_number"`
	DocumentJson   string         `json:"document_json"`
	CreatedBy      sql.NullString `json:"created_by"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) CreateSitePartRevision(ctx context.Context, arg CreateSitePartRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createSitePartRevision,
		arg.ID,
		arg.SitePartID,
		arg.RevisionNumber,
		arg.DocumentJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteSitePart = `-- name: DeleteSitePart :exec
DELETE FROM site_parts
WHERE id = ?
`

func (q *Queries) DeleteSitePart(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSitePart, id)
	return err
}

const getLatestSitePartRevision = `-- name: GetLatestSitePartRevision :one
SELECT id, site_part_id, revision_number, document_json, created_by, created_at
FROM site_part_revisions
WHERE site_part_id = ?
ORDER BY revision_number DESC
LIMIT 1
`

func (q *Queries) GetLatestSitePartRevision(ctx context.Context, sitePartID string) (SitePartRevision, error) {
	row := q.db.QueryRowContext(ctx, getLatestSitePartRevision, sitePartID)
	var i SitePartRevision
	err := row.Scan(
		&i.ID,
		&i.SitePartID,
		&i.RevisionNumber,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPublishedSitePartRevision = `-- name: GetPublishedSitePartRevision :one
SELECT r.id, r.site_part_id, r.revision_number, r.document_json, r.created_by, r.created_at
FROM site_parts p
JOIN site_part_revisions r ON r.id = p.published_revision_id
WHERE p.id = ?
LIMIT 1
`

func (q *Queries) GetPublishedSitePartRevision(ctx context.Context, id string) (SitePartRevision, error) {
	row := q.db.QueryRowContext(ctx, getPublishedSitePartRevision, id)
	var i SitePartRevision
	err := row.Scan(
		&i.ID,
		&i.SitePartID,
		&i.RevisionNumber,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSitePart = `-- name: GetSitePart :one
SELECT id, name, published_revision_id, created_at, updated_at
FROM site_parts
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSitePart(ctx context.Context, id string) (SitePart, error) {
	row := q.db.QueryRowContext(ctx, getSitePart, id)
	var i SitePart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSitePartLocation = `-- name: GetSitePartLocation :one
SELECT location, site_part_id, updated_at
FROM site_part_locations
WHERE location = ?
LIMIT 1
`

func (q *Queries) GetSitePartLocation(ctx context.Context, location string) (SitePartLocation, error) {
	row := q.db.QueryRowContext(ctx, getSitePartLocation, location)
	var i SitePartLocation
	err := row.Scan(&i.Location, &i.SitePartID, &i.UpdatedAt)
	return i, err
}

const getSitePartRevision = `-- name: GetSitePartRevision :one
SELECT id, site_part_id, revision_number, document_json, created_by, created_at
FROM site_part_revisions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSitePartRevision(ctx context.Context, id string) (SitePartRevision, error) {
	row := q.db.QueryRowContext(ctx, getSitePartRevision, id)
	var i SitePartRevision
	err := row.Scan(
		&i.ID,
		&i.SitePartID,
		&i.RevisionNumber,
		&i.DocumentJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSitePartWithPublishedRevision = `-- name: GetSitePartWithPublishedRevision :one
SELECT
    p.id,
    p.name,
    p.published_revision_id,
    p.created_at,
    p.updated_at,
    r.id AS revision_id,
    r.document_json
FROM site_parts p
JOIN site_part_revisions r ON r.id = p.published_revision_id
WHERE p.id = ?
LIMIT 1
`

type GetSitePartWithPublishedRevisionRow struct {
	ID                  string         `json:"id"`
	Name                string         `json:"name"`
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	RevisionID          string         `json:"revision_id"`
	DocumentJson        string         `json:"document_json"`
}

func (q *Queries) GetSitePartWithPublishedRevision(ctx context.Context, id string) (GetSitePartWithPublishedRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getSitePartWithPublishedRevision, id)
	var i GetSitePartWithPublishedRevisionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PublishedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevisionID,
		&i.DocumentJson,
	)
	return i, err
}

const getSitePartsByPublishedID = `-- name: GetSitePartsByPublishedID :many
SELECT id, name, published_revision_id, created_at, updated_at
FROM site_parts
WHERE published_revision_id IS NOT NULL
`

func (q *Queries) GetSitePartsByPublishedID(ctx context.Context) ([]SitePart, error) {
	rows, err := q.db.QueryContext(ctx, getSitePartsByPublishedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitePart{}
	for rows.Next() {
		var i SitePart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestSitePartRevisions = `-- name: ListLatestSitePartRevisions :many
SELECT id, site_part_id, revision_number, document_json, created_by, created_at
FROM site_part_revisions
WHERE id IN (
    SELECT id FROM site_part_revisions
    WHERE (site_part_id, revision_number) IN (
        SELECT site_part_id, MAX(revision_number) FROM site_part_revisions GROUP BY site_part_id
    )
)
`

func (q *Queries) ListLatestSitePartRevisions(ctx context.Context) ([]SitePartRevision, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSitePartRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitePartRevision{}
	for rows.Next() {
		var i SitePartRevision
		if err := rows.Scan(
			&i.ID,
			&i.SitePartID,
			&i.RevisionNumber,
			&i.DocumentJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitePartLocations = `-- name: ListSitePartLocations :many
SELECT location, site_part_id, updated_at
FROM site_part_locations
`

func (q *Queries) ListSitePartLocations(ctx context.Context) ([]SitePartLocation, error) {
	rows, err := q.db.QueryContext(ctx, listSitePartLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitePartLocation{}
	for rows.Next() {
		var i SitePartLocation
		if err := rows.Scan(&i.Location, &i.SitePartID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitePartRevisions = `-- name: ListSitePartRevisions :many
SELECT id, site_part_id, revision_number, document_json, created_by, created_at
FROM site_part_revisions
WHERE site_part_id = ?
ORDER BY revision_number DESC
`

func (q *Queries) ListSitePartRevisions(ctx context.Context, sitePartID string) ([]SitePartRevision, error) {
	rows, err := q.db.QueryContext(ctx, listSitePartRevisions, sitePartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitePartRevision{}
	for rows.Next() {
		var i SitePartRevision
		if err := rows.Scan(
			&i.ID,
			&i.SitePartID,
			&i.RevisionNumber,
			&i.DocumentJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteParts = `-- name: ListSiteParts :many
SELECT id, name, published_revision_id, created_at, updated_at
FROM site_parts
ORDER BY
    CASE WHEN published_revision_id IS NULL THEN 1 ELSE 0 END,
    name,
    id
`

func (q *Queries) ListSiteParts(ctx context.Context) ([]SitePart, error) {
	rows, err := q.db.QueryContext(ctx, listSiteParts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SitePart{}
	for rows.Next() {
		var i SitePart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PublishedRevisionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSitePartLocation = `-- name: SetSitePartLocation :exec
INSERT INTO site_part_locations (location, site_part_id, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(location) DO UPDATE SET site_part_id = excluded.site_part_id, updated_at = excluded.updated_at
`

type SetSitePartLocationParams struct {
	Location   string         `json:"location"`
	SitePartID sql.NullString `json:"site_part_id"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) SetSitePartLocation(ctx context.Context, arg SetSitePartLocationParams) error {
	_, err := q.db.ExecContext(ctx, setSitePartLocation, arg.Location, arg.SitePartID, arg.UpdatedAt)
	return err
}

const setSitePartPublishedRevision = `-- name: SetSitePartPublishedRevision :exec
UPDATE site_parts
SET published_revision_id = ?, updated_at = ?
WHERE id = ?
`

type SetSitePartPublishedRevisionParams struct {
	PublishedRevisionID sql.NullString `json:"published_revision_id"`
	UpdatedAt           int64          `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) SetSitePartPublishedRevision(ctx context.Context, arg SetSitePartPublishedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setSitePartPublishedRevision, arg.PublishedRevisionID, arg.UpdatedAt, arg.ID)
	return err
}

const updateSitePart = `-- name: UpdateSitePart :exec
UPDATE site_parts
SET name = ?, updated_at = ?
WHERE id = ?
`

type UpdateSitePartParams struct {
	Name      string `json:"name"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSitePart(ctx context.Context, arg UpdateSitePartParams) error {
	_, err := q.db.ExecContext(ctx, updateSitePart, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
