// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sitemap.sql

package db

import (
	"context"
)

const listSitemapEntries = `-- name: ListSitemapEntries :many
SELECT
    rt.path AS route_path,
    e.content_type_id AS content_type,
    r.created_at AS lastmod
FROM routes rt
JOIN entries e
    ON e.id = rt.entry_id
JOIN entry_revisions r
    ON r.id = e.published_revision_id
JOIN content_types ct
    ON ct.id = e.content_type_id
WHERE rt.route_type = 'entry'
  AND e.status = 'active'
  AND e.published_revision_id IS NOT NULL
  AND ct.public = 1
  AND (r.seo_robots_index IS NULL OR r.seo_robots_index != 0)
ORDER BY rt.path
`

type ListSitemapEntriesRow struct {
	RoutePath   string `json:"route_path"`
	ContentType string `json:"content_type"`
	Lastmod     int64  `json:"lastmod"`
}

// Returns every URL that belongs in the sitemap: published and active entries
// of public content types that own an entry-type route and resolve as
// indexable. Drafts (no published revision), private/trash entries,
// non-public content types, redirect/system routes, admin/preview URLs and
// noindex revisions are all excluded by the joins and filters below.
// <lastmod> comes from the published revision timestamp, so a newer draft
// never changes the sitemap.
func (q *Queries) ListSitemapEntries(ctx context.Context) ([]ListSitemapEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSitemapEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitemapEntriesRow{}
	for rows.Next() {
		var i ListSitemapEntriesRow
		if err := rows.Scan(&i.RoutePath, &i.ContentType, &i.Lastmod); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
