// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sitemap.sql

package db

import (
	"context"
)

const listSitemapEntries = `-- name: ListSitemapEntries :many
SELECT
    rt.path AS route_path,
    e.content_type_id AS content_type,
    r.created_at AS lastmod
FROM routes rt
JOIN entries e
    ON e.id = rt.entry_id
JOIN entry_revisions r
    ON r.id = e.published_revision_id
WHERE rt.route_type = 'entry'
  AND e.status = 'active'
  AND e.published_revision_id IS NOT NULL
ORDER BY rt.path
`

type ListSitemapEntriesRow struct {
	RoutePath   string `json:"route_path"`
	ContentType string `json:"content_type"`
	Lastmod     int64  `json:"lastmod"`
}

// Returns every publicly published entry that owns an entry-type route. Drafts,
// private/trash entries, redirect routes, admin/preview URLs and unpublished
// entries are excluded by the joins and filters below. The published revision
// timestamp drives <lastmod> so a newer draft does not change the sitemap.
func (q *Queries) ListSitemapEntries(ctx context.Context) ([]ListSitemapEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSitemapEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitemapEntriesRow{}
	for rows.Next() {
		var i ListSitemapEntriesRow
		if err := rows.Scan(&i.RoutePath, &i.ContentType, &i.Lastmod); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
