// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomies.sql

package db

import (
	"context"
	"database/sql"
)

const createTaxonomy = `-- name: CreateTaxonomy :exec
INSERT INTO taxonomies (id, content_type_id, singular_name, plural_name, hierarchical, public, route_base, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaxonomyParams struct {
	ID            string         `json:"id"`
	ContentTypeID string         `json:"content_type_id"`
	SingularName  string         `json:"singular_name"`
	PluralName    string         `json:"plural_name"`
	Hierarchical  int64          `json:"hierarchical"`
	Public        int64          `json:"public"`
	RouteBase     sql.NullString `json:"route_base"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) CreateTaxonomy(ctx context.Context, arg CreateTaxonomyParams) error {
	_, err := q.db.ExecContext(ctx, createTaxonomy,
		arg.ID,
		arg.ContentTypeID,
		arg.SingularName,
		arg.PluralName,
		arg.Hierarchical,
		arg.Public,
		arg.RouteBase,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTaxonomy = `-- name: DeleteTaxonomy :exec
DELETE FROM taxonomies WHERE id = ?
`

func (q *Queries) DeleteTaxonomy(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTaxonomy, id)
	return err
}

const getTaxonomy = `-- name: GetTaxonomy :one
SELECT id, content_type_id, singular_name, plural_name, hierarchical, public, route_base, created_at, updated_at FROM taxonomies WHERE id = ? LIMIT 1
`

func (q *Queries) GetTaxonomy(ctx context.Context, id string) (Taxonomy, error) {
	row := q.db.QueryRowContext(ctx, getTaxonomy, id)
	var i Taxonomy
	err := row.Scan(
		&i.ID,
		&i.ContentTypeID,
		&i.SingularName,
		&i.PluralName,
		&i.Hierarchical,
		&i.Public,
		&i.RouteBase,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaxonomies = `-- name: ListTaxonomies :many
SELECT id, content_type_id, singular_name, plural_name, hierarchical, public, route_base, created_at, updated_at FROM taxonomies ORDER BY id
`

func (q *Queries) ListTaxonomies(ctx context.Context) ([]Taxonomy, error) {
	rows, err := q.db.QueryContext(ctx, listTaxonomies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Taxonomy{}
	for rows.Next() {
		var i Taxonomy
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.SingularName,
			&i.PluralName,
			&i.Hierarchical,
			&i.Public,
			&i.RouteBase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxonomiesByContentType = `-- name: ListTaxonomiesByContentType :many
SELECT id, content_type_id, singular_name, plural_name, hierarchical, public, route_base, created_at, updated_at FROM taxonomies WHERE content_type_id = ? ORDER BY id
`

func (q *Queries) ListTaxonomiesByContentType(ctx context.Context, contentTypeID string) ([]Taxonomy, error) {
	rows, err := q.db.QueryContext(ctx, listTaxonomiesByContentType, contentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Taxonomy{}
	for rows.Next() {
		var i Taxonomy
		if err := rows.Scan(
			&i.ID,
			&i.ContentTypeID,
			&i.SingularName,
			&i.PluralName,
			&i.Hierarchical,
			&i.Public,
			&i.RouteBase,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaxonomy = `-- name: UpdateTaxonomy :exec
UPDATE taxonomies SET singular_name = ?, plural_name = ?, hierarchical = ?, public = ?, route_base = ?, updated_at = ? WHERE id = ?
`

type UpdateTaxonomyParams struct {
	SingularName string         `json:"singular_name"`
	PluralName   string         `json:"plural_name"`
	Hierarchical int64          `json:"hierarchical"`
	Public       int64          `json:"public"`
	RouteBase    sql.NullString `json:"route_base"`
	UpdatedAt    int64          `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateTaxonomy(ctx context.Context, arg UpdateTaxonomyParams) error {
	_, err := q.db.ExecContext(ctx, updateTaxonomy,
		arg.SingularName,
		arg.PluralName,
		arg.Hierarchical,
		arg.Public,
		arg.RouteBase,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
