// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terms.sql

package db

import (
	"context"
	"database/sql"
)

const countTermsByTaxonomy = `-- name: CountTermsByTaxonomy :one
SELECT COUNT(*) FROM terms WHERE taxonomy_id = ?
`

func (q *Queries) CountTermsByTaxonomy(ctx context.Context, taxonomyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTermsByTaxonomy, taxonomyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTerm = `-- name: CreateTerm :exec
INSERT INTO terms (id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTermParams struct {
	ID          string         `json:"id"`
	TaxonomyID  string         `json:"taxonomy_id"`
	ParentID    sql.NullString `json:"parent_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreateTerm(ctx context.Context, arg CreateTermParams) error {
	_, err := q.db.ExecContext(ctx, createTerm,
		arg.ID,
		arg.TaxonomyID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTerm = `-- name: DeleteTerm :exec
DELETE FROM terms WHERE id = ?
`

func (q *Queries) DeleteTerm(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTerm, id)
	return err
}

const getTerm = `-- name: GetTerm :one
SELECT id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at FROM terms WHERE id = ? LIMIT 1
`

func (q *Queries) GetTerm(ctx context.Context, id string) (Term, error) {
	row := q.db.QueryRowContext(ctx, getTerm, id)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.TaxonomyID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTermBySlug = `-- name: GetTermBySlug :one
SELECT id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at FROM terms WHERE taxonomy_id = ? AND slug = ? LIMIT 1
`

type GetTermBySlugParams struct {
	TaxonomyID string `json:"taxonomy_id"`
	Slug       string `json:"slug"`
}

func (q *Queries) GetTermBySlug(ctx context.Context, arg GetTermBySlugParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, getTermBySlug, arg.TaxonomyID, arg.Slug)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.TaxonomyID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTermByTaxonomyAndSlug = `-- name: GetTermByTaxonomyAndSlug :one
SELECT id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at FROM terms WHERE taxonomy_id = ? AND slug = ? LIMIT 1
`

type GetTermByTaxonomyAndSlugParams struct {
	TaxonomyID string `json:"taxonomy_id"`
	Slug       string `json:"slug"`
}

func (q *Queries) GetTermByTaxonomyAndSlug(ctx context.Context, arg GetTermByTaxonomyAndSlugParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, getTermByTaxonomyAndSlug, arg.TaxonomyID, arg.Slug)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.TaxonomyID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildTerms = `-- name: ListChildTerms :many
SELECT id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at FROM terms WHERE parent_id = ? ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListChildTerms(ctx context.Context, parentID sql.NullString) ([]Term, error) {
	rows, err := q.db.QueryContext(ctx, listChildTerms, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.TaxonomyID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTermsByTaxonomy = `-- name: ListTermsByTaxonomy :many
SELECT id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at FROM terms WHERE taxonomy_id = ? ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListTermsByTaxonomy(ctx context.Context, taxonomyID string) ([]Term, error) {
	rows, err := q.db.QueryContext(ctx, listTermsByTaxonomy, taxonomyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.TaxonomyID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTermsByTaxonomyWithCounts = `-- name: ListTermsByTaxonomyWithCounts :many
SELECT
    t.id, t.taxonomy_id, t.parent_id, t.name, t.slug, t.description, t.created_at, t.updated_at,
    COUNT(DISTINCT e.id) AS published_count
FROM terms t
LEFT JOIN entry_revision_terms ert ON ert.term_id = t.id
LEFT JOIN entries e ON e.published_revision_id = ert.revision_id AND e.status = 'active'
WHERE t.taxonomy_id = ?
GROUP BY t.id
ORDER BY t.name COLLATE NOCASE
`

type ListTermsByTaxonomyWithCountsRow struct {
	ID             string         `json:"id"`
	TaxonomyID     string         `json:"taxonomy_id"`
	ParentID       sql.NullString `json:"parent_id"`
	Name           string         `json:"name"`
	Slug           string         `json:"slug"`
	Description    string         `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	PublishedCount int64          `json:"published_count"`
}

func (q *Queries) ListTermsByTaxonomyWithCounts(ctx context.Context, taxonomyID string) ([]ListTermsByTaxonomyWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTermsByTaxonomyWithCounts, taxonomyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTermsByTaxonomyWithCountsRow{}
	for rows.Next() {
		var i ListTermsByTaxonomyWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaxonomyID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTermsByTaxonomy = `-- name: SearchTermsByTaxonomy :many
SELECT id, taxonomy_id, parent_id, name, slug, description, created_at, updated_at FROM terms WHERE taxonomy_id = ? AND (name LIKE '%' || ? || '%' OR slug LIKE '%' || ? || '%') ORDER BY name COLLATE NOCASE LIMIT ? OFFSET ?
`

type SearchTermsByTaxonomyParams struct {
	TaxonomyID string         `json:"taxonomy_id"`
	Column2    sql.NullString `json:"column_2"`
	Column3    sql.NullString `json:"column_3"`
	Limit      int64          `json:"limit"`
	Offset     int64          `json:"offset"`
}

func (q *Queries) SearchTermsByTaxonomy(ctx context.Context, arg SearchTermsByTaxonomyParams) ([]Term, error) {
	rows, err := q.db.QueryContext(ctx, searchTermsByTaxonomy,
		arg.TaxonomyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Term{}
	for rows.Next() {
		var i Term
		if err := rows.Scan(
			&i.ID,
			&i.TaxonomyID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTerm = `-- name: UpdateTerm :exec
UPDATE terms SET parent_id = ?, name = ?, slug = ?, description = ?, updated_at = ? WHERE id = ?
`

type UpdateTermParams struct {
	ParentID    sql.NullString `json:"parent_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description string         `json:"description"`
	UpdatedAt   int64          `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateTerm(ctx context.Context, arg UpdateTermParams) error {
	_, err := q.db.ExecContext(ctx, updateTerm,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
