// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package db

import (
	"context"
)

const getThemeCustomization = `-- name: GetThemeCustomization :one
SELECT theme_id, theme_version, settings_json, custom_css, updated_at
FROM theme_customizations
WHERE theme_id = ?
`

func (q *Queries) GetThemeCustomization(ctx context.Context, themeID string) (ThemeCustomization, error) {
	row := q.db.QueryRowContext(ctx, getThemeCustomization, themeID)
	var i ThemeCustomization
	err := row.Scan(
		&i.ThemeID,
		&i.ThemeVersion,
		&i.SettingsJson,
		&i.CustomCss,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertThemeCustomization = `-- name: UpsertThemeCustomization :exec
INSERT INTO theme_customizations (theme_id, theme_version, settings_json, custom_css, updated_at)
VALUES (?, ?, ?, ?, unixepoch())
ON CONFLICT(theme_id) DO UPDATE SET
    theme_version = excluded.theme_version,
    settings_json = excluded.settings_json,
    custom_css = excluded.custom_css,
    updated_at = excluded.updated_at
`

type UpsertThemeCustomizationParams struct {
	ThemeID      string `json:"theme_id"`
	ThemeVersion int64  `json:"theme_version"`
	SettingsJson string `json:"settings_json"`
	CustomCss    string `json:"custom_css"`
}

func (q *Queries) UpsertThemeCustomization(ctx context.Context, arg UpsertThemeCustomizationParams) error {
	_, err := q.db.ExecContext(ctx, upsertThemeCustomization,
		arg.ThemeID,
		arg.ThemeVersion,
		arg.SettingsJson,
		arg.CustomCss,
	)
	return err
}
