-- ===== 0003_lcp_and_assets.sql =====
-- Priority stays an author override: auto follows document order, high wins over
-- auto, and normal explicitly excludes an image from automatic LCP selection.
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["mediaId"],"properties":{"mediaId":{"type":"string","default":""},"alt":{"type":"string","default":""},"caption":{"type":"string","default":""}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["none","left","center"],"default":"none"},"decorative":{"type":"boolean","default":false},"sizes":{"type":"string","default":""},"eager":{"type":"boolean","default":false},"priority":{"type":"string","enum":["auto","high","normal"],"default":"auto"}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"image","fields":{"props.mediaId":{"label":"Image","control":"media","group":"Content"},"props.alt":{"label":"Alt text","control":"text","group":"Accessibility"},"settings.decorative":{"label":"Decorative (no alt)","control":"checkbox","group":"Accessibility"},"props.caption":{"label":"Caption","control":"text","group":"Content"},"settings.align":{"label":"Alignment","control":"segmented","group":"Layout"},"settings.sizes":{"label":"Sizes (responsive)","control":"text","group":"Advanced"},"settings.priority":{"label":"Prioritize loading (LCP image)","control":"select","group":"Advanced"}}}}',
    template = '{{ $m := media .Props.mediaId }}{{ if $m.Src }}<figure class="stratum-image stratum-image-align-{{ .Settings.align }}"><img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}" sizes="{{ if .Settings.sizes }}{{ .Settings.sizes }}{{ else }}(min-width: 768px) min(100vw, 1200px), 100vw{{ end }}"{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ if not .Settings.decorative }}{{ if .Props.alt }}{{ .Props.alt }}{{ else }}{{ $m.Alt }}{{ end }}{{ end }}"{{ if .Priority }} loading="eager" fetchpriority="high" decoding="async"{{ else }} loading="lazy" decoding="async"{{ end }}>{{ if .Props.caption }}<figcaption class="stratum-image-caption">{{ .Props.caption }}</figcaption>{{ end }}</figure>{{ else }}<div class="stratum-image stratum-image-missing" role="img" aria-label="Missing image">Image unavailable</div>{{ end }}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'image' AND version = 1;

UPDATE block_definitions SET
    template = '{{ $m := media .Context.Entry.FeaturedImage }}{{ if $m.Src }}<figure class="stratum-featured-image stratum-featured-image-fit-{{ .Settings.objectFit }} stratum-featured-image-ar-{{ .Settings.aspectRatio }} stratum-featured-image-align-{{ .Settings.align }}"><img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}" sizes="(min-width:992px) 768px,(min-width:640px) 480px,100vw"{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ $m.Alt }}"{{ if .Priority }} loading="eager" fetchpriority="high" decoding="async"{{ else }} loading="lazy" decoding="async"{{ end }}></figure>{{ else }}<div class="stratum-featured-image stratum-featured-image-missing">Featured image</div>{{ end }}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'featured-image' AND version = 1;
