-- Core Image block: references a media asset by id and only stores usage-specific
-- data (alt override, caption). The renderer resolves mediaId to the
-- optimized variants, so URLs never live in the document.
INSERT INTO block_definitions (
    id, namespace, name, version, display_name, description, schema_json,
    renderer_type, template, styles, source, enabled, created_at, updated_at
)
VALUES (
    'core-image-v1', 'core', 'image', 1, 'Image', 'An image selected from the Media Library.',
    '{"schemaVersion":1,"props":{"type":"object","required":["mediaId"],"properties":{"mediaId":{"type":"string","default":""},"alt":{"type":"string","default":""},"caption":{"type":"string","default":""}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["none","left","center"],"default":"none"},"decorative":{"type":"boolean","default":false},"sizes":{"type":"string","default":""},"eager":{"type":"boolean","default":false}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"image","fields":{"props.mediaId":{"label":"Image","control":"media","group":"Content"},"props.alt":{"label":"Alt text","control":"text","group":"Accessibility"},"settings.decorative":{"label":"Decorative (no alt)","control":"checkbox","group":"Accessibility"},"props.caption":{"label":"Caption","control":"text","group":"Content"},"settings.align":{"label":"Alignment","control":"segmented","group":"Layout"},"settings.sizes":{"label":"Sizes (responsive)","control":"text","group":"Advanced"},"settings.eager":{"label":"Load eagerly (LCP)","control":"checkbox","group":"Advanced"}}}}',
    'template',
     '{{ $m := media .Props.mediaId }}{{ if $m.Src }}<figure class="stratum-image stratum-image-align-{{ .Settings.align }}"><img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}"{{ if .Settings.sizes }} sizes="{{ .Settings.sizes }}"{{ end }}{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ if not .Settings.decorative }}{{ if .Props.alt }}{{ .Props.alt }}{{ else }}{{ $m.Alt }}{{ end }}{{ end }}" decoding="async" fetchpriority="{{ if .Settings.eager }}high{{ end }}">{{ if .Props.caption }}<figcaption class="stratum-image-caption">{{ .Props.caption }}</figcaption>{{ end }}</figure>{{ else }}<div class="stratum-image stratum-image-missing">Image unavailable</div>{{ end }}',
    '.stratum-image{margin:0}.stratum-image img{display:block;max-width:100%;height:auto}.stratum-image-fit-cover img{object-fit:cover;width:100%;height:100%}.stratum-image-fit-contain img{object-fit:contain}.stratum-image-ar-1-1{aspect-ratio:1/1}.stratum-image-ar-4-3{aspect-ratio:4/3}.stratum-image-ar-16-9{aspect-ratio:16/9}.stratum-image-ar-3-2{aspect-ratio:3/2}.stratum-image-ar-1-1 img,.stratum-image-ar-4-3 img,.stratum-image-ar-16-9 img,.stratum-image-ar-3-2 img{width:100%;height:100%}.stratum-image-align-left{text-align:left}.stratum-image-align-center{text-align:center}.stratum-image-align-right{text-align:right}.stratum-image-align-full img{width:100%}.stratum-image-caption{margin-top:var(--st-space-xs);font-size:var(--st-small-size,.875rem);color:var(--st-color-text-muted)}.stratum-image-missing{padding:var(--st-space-lg);border:1px dashed var(--st-color-border);text-align:center;color:var(--st-color-text-muted)}',
    'core', 1, unixepoch(), unixepoch()
);