-- Rich Text v2 stores inline content as structured JSON and leaves v1 rows
-- available for historic documents. Runtime migration upgrades v1 in memory.
INSERT INTO block_definitions (id, namespace, name, version, display_name, description, schema_json, renderer_type, template, styles, source, enabled, created_at, updated_at)
SELECT 'core-heading-v2', 'core', 'heading', 2, 'Heading', 'A semantic heading with structured inline content.',
  '{"schemaVersion":1,"props":{"type":"object","required":["text"],"properties":{"text":{"type":"object","default":{"version":1,"content":[]},"required":["version","content"],"properties":{"version":{"type":"integer","enum":[1]},"content":{"type":"array","items":{"type":"object","required":["text"],"properties":{"text":{"type":"string"},"marks":{"type":"array","items":{"type":"object","required":["type"],"properties":{"type":{"type":"string","enum":["bold","italic","strike","code","link"]},"href":{"type":"string"}}}}}}}}},"level":{"type":"integer","enum":[1,2,3,4,5,6],"default":2}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["left","center","right"],"default":"left"},"visualSize":{"type":"string","enum":["auto","sm","md","lg","xl"],"default":"auto"},"tone":{"type":"string","enum":["default","muted","primary"],"default":"default"},"maxWidth":{"type":"string","enum":["normal","wide","none"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"text","icon":"heading","summaryFields":["props.text"],"fields":{"props.text":{"label":"Text","control":"richtext"},"props.level":{"label":"Level","control":"select"},"settings.align":{"label":"Alignment","control":"segmented","group":"Style"},"settings.visualSize":{"label":"Visual size","control":"segmented","group":"Style"},"settings.tone":{"label":"Tone","control":"select","group":"Style"},"settings.maxWidth":{"label":"Max width","control":"segmented","group":"Layout"}}}}',
  'template', '{{ if integerEquals .Props.level 1 }}<h1 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h1>{{ else if integerEquals .Props.level 3 }}<h3 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h3>{{ else if integerEquals .Props.level 4 }}<h4 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h4>{{ else if integerEquals .Props.level 5 }}<h5 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h5>{{ else if integerEquals .Props.level 6 }}<h6 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h6>{{ else }}<h2 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h2>{{ end }}',
  '.stratum-heading{margin:0}.stratum-heading-size-sm{font-size:var(--st-h3-size,1.5rem)}.stratum-heading-size-md{font-size:var(--st-h2-size,2rem)}.stratum-heading-size-lg{font-size:var(--st-h1-size,2.5rem)}.stratum-heading-size-xl{font-size:clamp(2.5rem,5vw,4rem)}.stratum-heading-size-auto{}.stratum-maxw-normal{max-width:var(--st-content-width)}.stratum-maxw-wide{max-width:var(--st-wide-width)}.stratum-maxw-none{max-width:none}', 'core', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM block_definitions WHERE namespace = 'core' AND name = 'heading' AND version = 2);

INSERT INTO block_definitions (id, namespace, name, version, display_name, description, schema_json, renderer_type, template, styles, source, enabled, created_at, updated_at)
SELECT 'core-text-v2', 'core', 'text', 2, 'Text', 'A paragraph with structured inline content.',
  '{"schemaVersion":1,"props":{"type":"object","required":["text"],"properties":{"text":{"type":"object","default":{"version":1,"content":[]},"required":["version","content"],"properties":{"version":{"type":"integer","enum":[1]},"content":{"type":"array","items":{"type":"object","required":["text"],"properties":{"text":{"type":"string"},"marks":{"type":"array","items":{"type":"object","required":["type"],"properties":{"type":{"type":"string","enum":["bold","italic","strike","code","link"]},"href":{"type":"string"}}}}}}}}}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["left","center","right"],"default":"left"},"tone":{"type":"string","enum":["default","muted","primary"],"default":"default"},"size":{"type":"string","enum":["sm","md","lg"],"default":"md"},"maxWidth":{"type":"string","enum":["narrow","normal","wide","none"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"text","icon":"text","summaryFields":["props.text"],"fields":{"props.text":{"label":"Text","control":"richtext"},"settings.align":{"label":"Alignment","control":"segmented","group":"Style"},"settings.tone":{"label":"Tone","control":"select","group":"Style"},"settings.size":{"label":"Size","control":"segmented","group":"Style"},"settings.maxWidth":{"label":"Max width","control":"segmented","group":"Layout"}}}}',
  'template', '<p class="stratum-text stratum-align-{{ .Settings.align }} stratum-tone-{{ .Settings.tone }} stratum-text-size-{{ .Settings.size }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</p>',
  '.stratum-text{margin:0}.stratum-text-size-sm{font-size:var(--st-small-size,.875rem)}.stratum-text-size-md{font-size:inherit}.stratum-text-size-lg{font-size:1.15rem;line-height:1.6}.stratum-maxw-narrow{max-width:38rem}.stratum-maxw-normal{max-width:var(--st-content-width)}.stratum-maxw-wide{max-width:var(--st-wide-width)}.stratum-maxw-none{max-width:none}', 'core', 1, unixepoch(), unixepoch()
WHERE NOT EXISTS (SELECT 1 FROM block_definitions WHERE namespace = 'core' AND name = 'text' AND version = 2);

UPDATE block_definitions SET enabled = 0, updated_at = unixepoch()
WHERE namespace = 'core' AND name IN ('heading', 'text') AND version = 1;
