-- Generic entry-bound blocks. Values are resolved from the current immutable
-- revision context; no block receives storage access or an expression language.
PRAGMA foreign_keys = ON;

INSERT INTO block_definitions (id,namespace,name,version,display_name,description,schema_json,renderer_type,template,styles,source,enabled,created_at,updated_at) VALUES
('core-entry-field-v1','core','entry-field',1,'Entry Field','Display a system or custom field from the current entry.',
'{"schemaVersion":1,"props":{"type":"object","required":["source"],"properties":{"source":{"type":"string","default":"entry.title"}}},"settings":{"type":"object","properties":{"tag":{"type":"string","enum":["span","p","h1","h2","h3","h4","h5","h6","strong"],"default":"span"},"prefix":{"type":"string","default":""},"suffix":{"type":"string","default":""}}},"children":{"mode":"none"},"editor":{"category":"dynamic","icon":"text","contexts":["entry","layout-template"],"fields":{"props.source":{"label":"Field","control":"select","group":"Content","optionsSource":"entry-fields"},"settings.tag":{"label":"Element","control":"select","group":"Style"},"settings.prefix":{"label":"Prefix","control":"text","group":"Content"},"settings.suffix":{"label":"Suffix","control":"text","group":"Content"}}}}',
'runtime','<span class="stratum-entry-field"></span>','.stratum-entry-field{white-space:pre-wrap}','core',1,unixepoch(),unixepoch()),
('core-entry-media-v1','core','entry-media',1,'Entry Media','Display a media field from the current entry.',
'{"schemaVersion":1,"props":{"type":"object","required":["source"],"properties":{"source":{"type":"string","default":"entry.featured_media"}}},"settings":{"type":"object","properties":{"alt":{"type":"string","default":""},"sizes":{"type":"string","default":"100vw"}}},"children":{"mode":"none"},"editor":{"category":"dynamic","icon":"image","contexts":["entry","layout-template"],"fields":{"props.source":{"label":"Media field","control":"select","group":"Content","optionsSource":"entry-fields"},"settings.alt":{"label":"Alt override","control":"text","group":"Content"},"settings.sizes":{"label":"Sizes","control":"text","group":"Style"}}}}',
'runtime','<figure class="stratum-entry-media"></figure>','.stratum-entry-media{margin:0}.stratum-entry-media img{display:block;max-width:100%;height:auto}','core',1,unixepoch(),unixepoch())
ON CONFLICT(namespace,name,version) DO UPDATE SET display_name=excluded.display_name,description=excluded.description,schema_json=excluded.schema_json,renderer_type=excluded.renderer_type,template=excluded.template,styles=excluded.styles,source=excluded.source,enabled=excluded.enabled,updated_at=excluded.updated_at;

INSERT INTO block_definitions (id,namespace,name,version,display_name,description,schema_json,renderer_type,template,styles,source,enabled,created_at,updated_at) VALUES
('core-collection-v2','core','collection',2,'Collection','Query any content type and render children once per published entry.',
'{"schemaVersion":1,"props":{"type":"object","properties":{}},"settings":{"type":"object","properties":{"contentType":{"type":"string","default":"post"},"limit":{"type":"integer","minimum":1,"maximum":20,"default":6},"offset":{"type":"integer","minimum":0,"default":0},"source":{"type":"string","enum":["query","context"],"default":"query"},"excludeCurrent":{"type":"boolean","default":false},"orderBy":{"type":"string","default":"entry.published_at"},"direction":{"type":"string","enum":["asc","desc"],"default":"desc"},"termId":{"type":"string","default":""},"filters":{"type":"array","items":{"type":"object","required":["field","operator"],"properties":{"field":{"type":"string","default":"entry.title"},"operator":{"type":"string","enum":["equals","not_equals","contains","exists","not_exists","greater_than","greater_or_equal","less_than","less_or_equal","is_true","is_false","before","after"],"default":"equals"},"value":{"type":"string","default":""}}}}}},"children":{"mode":"any"},"editor":{"category":"query","icon":"collection","contexts":["entry","layout-template"],"fields":{"settings.contentType":{"label":"Content Type","control":"select","group":"Query","optionsSource":"content-types"},"settings.limit":{"label":"Limit","control":"number","group":"Query"},"settings.source":{"label":"Source","control":"select","group":"Query"},"settings.excludeCurrent":{"label":"Exclude current","control":"checkbox","group":"Query"},"settings.orderBy":{"label":"Sort by","control":"select","group":"Query","optionsSource":"entry-fields"},"settings.direction":{"label":"Direction","control":"select","group":"Query"},"settings.termId":{"label":"Taxonomy term ID","control":"text","group":"Query"},"settings.filters":{"label":"Filters","group":"Query"}}}}',
'runtime','<div class="stratum-collection">{{ .Children }}</div>','.stratum-collection{display:grid;gap:var(--st-space-lg)}','core',1,unixepoch(),unixepoch())
ON CONFLICT(namespace,name,version) DO UPDATE SET display_name=excluded.display_name,description=excluded.description,schema_json=excluded.schema_json,renderer_type=excluded.renderer_type,template=excluded.template,styles=excluded.styles,source=excluded.source,enabled=excluded.enabled,updated_at=excluded.updated_at;
