-- 058_epic3_blocks.sql
-- EPIC 3: design system polish + core layout blocks + patterns support
-- Adds gallery, embed, columns and upgrades existing blocks with semantic variants.

PRAGMA foreign_keys = ON;

-- ============================================================
-- Embed: privacy-conscious YouTube/Vimeo embed
-- ============================================================
INSERT INTO block_definitions (
    id, namespace, name, version, display_name, description, schema_json,
    renderer_type, template, styles, source, enabled, created_at, updated_at
)
VALUES (
    'core-embed-v1', 'core', 'embed', 1, 'Embed', 'Embed a YouTube or Vimeo video.',
    '{"schemaVersion":1,"props":{"type":"object","required":["url"],"properties":{"url":{"type":"string","default":""}}},"settings":{"type":"object","properties":{"aspect":{"type":"string","enum":["16:9","4:3","1:1"],"default":"16:9"}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"embed","fields":{"props.url":{"label":"URL","control":"text","group":"Content"},"settings.aspect":{"label":"Aspect","control":"select","group":"Style"}}}}',
    'template',
    '{{ $yt := youtubeID .Props.url }}{{ $vm := vimeoID .Props.url }}{{ if $yt }}<div class="stratum-embed stratum-embed-aspect-{{ .Settings.aspect }}"><iframe src="https://www.youtube-nocookie.com/embed/{{ $yt }}" title="YouTube video" loading="lazy" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>{{ else if $vm }}<div class="stratum-embed stratum-embed-aspect-{{ .Settings.aspect }}"><iframe src="https://player.vimeo.com/video/{{ $vm }}" title="Vimeo video" loading="lazy" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>{{ end }}',
    '.stratum-embed{position:relative;width:100%;overflow:hidden;background:var(--st-color-surface-muted)}.stratum-embed iframe{position:absolute;top:0;left:0;width:100%;height:100%;border:0}.stratum-embed-aspect-16\:9{aspect-ratio:16/9}.stratum-embed-aspect-4\:3{aspect-ratio:4/3}.stratum-embed-aspect-1\:1{aspect-ratio:1/1}',
    'core', 1, unixepoch(), unixepoch()
)
ON CONFLICT(namespace, name, version) DO UPDATE SET
    display_name=excluded.display_name,
    description=excluded.description,
    schema_json=excluded.schema_json,
    renderer_type=excluded.renderer_type,
    template=excluded.template,
    styles=excluded.styles,
    source=excluded.source,
    enabled=excluded.enabled,
    updated_at=excluded.updated_at;

-- ============================================================
-- Columns: semantic multi-column layout
-- ============================================================
INSERT INTO block_definitions (
    id, namespace, name, version, display_name, description, schema_json,
    renderer_type, template, styles, source, enabled, created_at, updated_at
)
VALUES (
    'core-columns-v1', 'core', 'columns', 1, 'Columns', 'A responsive column layout.',
    '{"schemaVersion":1,"props":{"type":"object","properties":{}},"settings":{"type":"object","properties":{"columns":{"type":"integer","enum":[2,3,4],"default":2},"ratio":{"type":"string","enum":["equal","1-2","2-1","1-3-2-3","2-3-1-3"],"default":"equal"},"gap":{"type":"string","enum":["none","xs","sm","md","lg","xl"],"default":"md"},"mobileStack":{"type":"boolean","default":true}}},"children":{"mode":"any","min":0},"editor":{"category":"layout","icon":"columns","fields":{"settings.columns":{"label":"Columns","control":"segmented","group":"Layout"},"settings.ratio":{"label":"Ratio","control":"select","group":"Layout"},"settings.gap":{"label":"Gap","control":"select","group":"Layout"},"settings.mobileStack":{"label":"Stack on mobile","control":"checkbox","group":"Layout"}}}}',
    'template',
    '<div class="stratum-columns stratum-columns-{{ .Settings.columns }} stratum-columns-ratio-{{ .Settings.ratio }} stratum-columns-gap-{{ .Settings.gap }}{{ if .Settings.mobileStack }} stratum-columns-mobile-stack{{ end }}">{{ .Children }}</div>',
    '.stratum-columns{display:grid;gap:var(--st-space-md)}.stratum-columns-2{grid-template-columns:repeat(2,1fr)}.stratum-columns-3{grid-template-columns:repeat(3,1fr)}.stratum-columns-4{grid-template-columns:repeat(4,1fr)}.stratum-columns-ratio-1-2{grid-template-columns:1fr 2fr}.stratum-columns-ratio-2-1{grid-template-columns:2fr 1fr}.stratum-columns-ratio-1-3-2-3{grid-template-columns:1fr 2fr}.stratum-columns-ratio-2-3-1-3{grid-template-columns:2fr 1fr}.stratum-columns-gap-none{gap:0}.stratum-columns-gap-xs{gap:var(--st-space-xs)}.stratum-columns-gap-sm{gap:var(--st-space-sm)}.stratum-columns-gap-md{gap:var(--st-space-md)}.stratum-columns-gap-lg{gap:var(--st-space-lg)}.stratum-columns-gap-xl{gap:var(--st-space-xl)}@media(max-width:640px){.stratum-columns-mobile-stack{grid-template-columns:1fr !important}}@media(max-width:800px){.stratum-columns-3,.stratum-columns-4{grid-template-columns:repeat(2,1fr)}.stratum-columns-mobile-stack.stratum-columns-3,.stratum-columns-mobile-stack.stratum-columns-4{grid-template-columns:1fr}}@media(max-width:480px){.stratum-columns-2{grid-template-columns:1fr}}',
    'core', 1, unixepoch(), unixepoch()
)
ON CONFLICT(namespace, name, version) DO UPDATE SET
    display_name=excluded.display_name,
    description=excluded.description,
    schema_json=excluded.schema_json,
    renderer_type=excluded.renderer_type,
    template=excluded.template,
    styles=excluded.styles,
    source=excluded.source,
    enabled=excluded.enabled,
    updated_at=excluded.updated_at;

-- ============================================================
-- Upgrade heading v2: add 2xl and display visualSize variants
-- ============================================================
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["text"],"properties":{"text":{"type":"object","default":{"version":1,"content":[]},"required":["version","content"],"properties":{"version":{"type":"integer","enum":[1]},"content":{"type":"array","items":{"type":"object","required":["text"],"properties":{"text":{"type":"string"},"marks":{"type":"array","items":{"type":"object","required":["type"],"properties":{"type":{"type":"string","enum":["bold","italic","strike","code","link"]},"href":{"type":"string"}}}}}}}}},"level":{"type":"integer","enum":[1,2,3,4,5,6],"default":2}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["left","center","right"],"default":"left"},"visualSize":{"type":"string","enum":["auto","sm","md","lg","xl","2xl","display"],"default":"auto"},"tone":{"type":"string","enum":["default","muted","primary"],"default":"default"},"maxWidth":{"type":"string","enum":["normal","wide","none"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"text","icon":"heading","summaryFields":["props.text"],"fields":{"props.text":{"label":"Text","control":"richtext"},"props.level":{"label":"Level","control":"select"},"settings.align":{"label":"Alignment","control":"segmented","group":"Style"},"settings.visualSize":{"label":"Visual size","control":"segmented","group":"Style"},"settings.tone":{"label":"Tone","control":"select","group":"Style"},"settings.maxWidth":{"label":"Max width","control":"segmented","group":"Layout"}}}}',
    template = '{{ if integerEquals .Props.level 1 }}<h1 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h1>{{ else if integerEquals .Props.level 3 }}<h3 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h3>{{ else if integerEquals .Props.level 4 }}<h4 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h4>{{ else if integerEquals .Props.level 5 }}<h5 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h5>{{ else if integerEquals .Props.level 6 }}<h6 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h6>{{ else }}<h2 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ richText .Props.text }}</h2>{{ end }}',
    styles = '.stratum-heading{margin:0}.stratum-heading-size-sm{font-size:var(--st-h3-size,1.5rem)}.stratum-heading-size-md{font-size:var(--st-h2-size,2rem)}.stratum-heading-size-lg{font-size:var(--st-h1-size,2.5rem)}.stratum-heading-size-xl{font-size:clamp(2.5rem,5vw,4rem)}.stratum-heading-size-2xl{font-size:clamp(3rem,6vw,5rem)}.stratum-heading-size-display{font-size:clamp(3.5rem,8vw,6.5rem);line-height:0.95;letter-spacing:-0.04em}.stratum-heading-size-auto{}.stratum-maxw-normal{max-width:var(--st-content-width)}.stratum-maxw-wide{max-width:var(--st-wide-width)}.stratum-maxw-none{max-width:none}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'heading' AND version = 2;

-- ============================================================
-- Upgrade button v1: add link variant and ensure token-based classes; empty hides
-- ============================================================
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["label","url"],"properties":{"label":{"type":"string","default":"Button"},"url":{"type":"string","default":"#"}}},"settings":{"type":"object","properties":{"variant":{"type":"string","enum":["primary","secondary","outline","ghost","link"],"default":"primary"},"size":{"type":"string","enum":["sm","md","lg"],"default":"md"},"width":{"type":"string","enum":["auto","full"],"default":"auto"},"align":{"type":"string","enum":["left","center","right"],"default":"left"},"openInNewTab":{"type":"boolean","default":false}}},"children":{"mode":"none"},"editor":{"category":"design","icon":"button","fields":{"props.label":{"label":"Label","control":"text"},"props.url":{"label":"URL","control":"text"},"settings.variant":{"label":"Variant","control":"segmented","group":"Style"},"settings.size":{"label":"Size","control":"segmented","group":"Style"},"settings.width":{"label":"Width","control":"segmented","group":"Layout"},"settings.align":{"label":"Alignment","control":"segmented","group":"Layout"},"settings.openInNewTab":{"label":"Open in new tab","control":"checkbox","group":"Link"}}}}',
    template = '{{ if and .Props.label .Props.url }}<div class="stratum-btn-wrap stratum-align-{{ .Settings.align }}{{ if eq .Settings.width "full" }} stratum-btn-wrap-full{{ end }}"><a class="stratum-button stratum-button-{{ .Settings.variant }} stratum-button-size-{{ .Settings.size }}{{ if eq .Settings.width "full" }} stratum-button-full{{ end }}" href="{{ .Props.url }}"{{ if .Settings.openInNewTab }} target="_blank" rel="noopener noreferrer"{{ end }}>{{ .Props.label }}</a></div>{{ end }}',
    styles = '.stratum-btn-wrap{margin:0}.stratum-btn-wrap-full{display:block}.stratum-button{display:inline-flex;align-items:center;justify-content:center;padding:var(--st-button-padding-y,.65rem) var(--st-button-padding-x,1rem);border:2px solid transparent;border-radius:var(--st-button-radius,.35rem);font-weight:var(--st-button-font-weight,600);text-decoration:none;cursor:pointer}.stratum-button-primary{background:var(--st-color-primary,#175cd3);color:var(--st-color-primary-contrast,#fff)}.stratum-button-primary:hover{background:var(--st-color-primary-hover,#1d4ed8)}.stratum-button-secondary{background:var(--st-color-secondary,#475467);color:var(--st-color-secondary-contrast,#fff)}.stratum-button-outline{border-color:var(--st-color-primary,#175cd3);color:var(--st-color-primary,#175cd3);background:transparent}.stratum-button-outline:hover{background:var(--st-color-primary,#175cd3);color:var(--st-color-primary-contrast,#fff)}.stratum-button-ghost{color:var(--st-color-primary,#175cd3);background:transparent}.stratum-button-ghost:hover{background:var(--st-color-surface-muted,#f4f6f8)}.stratum-button-link{background:transparent;color:var(--st-link-color);text-decoration:underline;padding:0;border:none}.stratum-button-link:hover{color:var(--st-link-hover-color)}.stratum-button-size-sm{padding:.4rem .75rem;font-size:var(--st-small-size,.875rem)}.stratum-button-size-lg{padding:.85rem 1.5rem;font-size:1.1rem}.stratum-button-full{display:block;width:100%;text-align:center}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'button' AND version = 1;

-- ============================================================
-- Upgrade image v1: add radius, aspect, fit settings (additive, keeps LCP Priority + WebP)
-- ============================================================
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["mediaId"],"properties":{"mediaId":{"type":"string","default":""},"alt":{"type":"string","default":""},"caption":{"type":"string","default":""}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["none","left","center"],"default":"none"},"decorative":{"type":"boolean","default":false},"sizes":{"type":"string","default":""},"eager":{"type":"boolean","default":false},"radius":{"type":"string","enum":["none","sm","md","lg"],"default":"none"},"aspect":{"type":"string","enum":["auto","square","4:3","16:9"],"default":"auto"},"fit":{"type":"string","enum":["auto","cover","contain"],"default":"auto"}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"image","fields":{"props.mediaId":{"label":"Image","control":"media","group":"Content"},"props.alt":{"label":"Alt text","control":"text","group":"Accessibility"},"settings.decorative":{"label":"Decorative (no alt)","control":"checkbox","group":"Accessibility"},"props.caption":{"label":"Caption","control":"text","group":"Content"},"settings.align":{"label":"Alignment","control":"segmented","group":"Layout"},"settings.radius":{"label":"Radius","control":"select","group":"Style"},"settings.aspect":{"label":"Aspect","control":"select","group":"Style"},"settings.fit":{"label":"Fit","control":"select","group":"Style"},"settings.sizes":{"label":"Sizes (responsive)","control":"text","group":"Advanced"},"settings.eager":{"label":"Load eagerly (LCP)","control":"checkbox","group":"Advanced"}}}}',
    template = '{{ $m := media .Props.mediaId }}{{ if $m.Src }}{{ $sizes := "(min-width: 768px) min(100vw, 1200px), 100vw" }}{{ if .Settings.sizes }}{{ $sizes = .Settings.sizes }}{{ end }}<figure class="stratum-image stratum-image-align-{{ .Settings.align }} stratum-image-radius-{{ .Settings.radius }} stratum-image-aspect-{{ .Settings.aspect }} stratum-image-fit-{{ .Settings.fit }}">{{ if $m.WebPSrcSet }}<picture><source type="image/webp" srcset="{{ $m.WebPSrcSet }}" sizes="{{ $sizes }}">{{ end }}<img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}" sizes="{{ $sizes }}"{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ if not .Settings.decorative }}{{ if .Props.alt }}{{ .Props.alt }}{{ else }}{{ $m.Alt }}{{ end }}{{ end }}"{{ if .Priority }} loading="eager" fetchpriority="high" decoding="async"{{ else }} loading="lazy" decoding="async"{{ end }}>{{ if $m.WebPSrcSet }}</picture>{{ end }}{{ if .Props.caption }}<figcaption class="stratum-image-caption">{{ .Props.caption }}</figcaption>{{ end }}</figure>{{ else }}<div class="stratum-image stratum-image-missing" role="img" aria-label="Missing image">Image unavailable</div>{{ end }}',
    styles = '.stratum-image{margin:0}.stratum-image img{display:block;max-width:100%;height:auto}.stratum-image-fit-cover img{object-fit:cover;width:100%;height:100%}.stratum-image-fit-contain img{object-fit:contain}.stratum-image-aspect-square img{aspect-ratio:1/1;object-fit:cover}.stratum-image-aspect-4\:3 img{aspect-ratio:4/3;object-fit:cover}.stratum-image-aspect-16\:9 img{aspect-ratio:16/9;object-fit:cover}.stratum-image-radius-sm img{border-radius:var(--st-radius-sm)}.stratum-image-radius-md img{border-radius:var(--st-radius-md)}.stratum-image-radius-lg img{border-radius:var(--st-radius-lg)}.stratum-image-align-left{text-align:left}.stratum-image-align-left img{margin-inline:0 auto}.stratum-image-align-center{text-align:center}.stratum-image-align-center img{margin-inline:auto}.stratum-image-align-right{text-align:right}.stratum-image-align-right img{margin-inline:auto 0}.stratum-image-caption{margin-top:var(--st-space-xs);font-size:var(--st-small-size,.875rem);color:var(--st-color-text-muted)}.stratum-image-missing{padding:var(--st-space-lg);border:1px dashed var(--st-color-border);text-align:center;color:var(--st-color-text-muted);border-radius:var(--st-radius-md)}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'image' AND version = 1;

-- ============================================================
-- Upgrade section: add secondary background and 2xl spacing
-- ============================================================
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","properties":{}},"settings":{"type":"object","properties":{"width":{"type":"string","enum":["content","wide","full"],"default":"content"},"verticalSpacing":{"type":"string","enum":["none","sm","md","lg","xl","2xl"],"default":"md"},"horizontalPadding":{"type":"string","enum":["none","sm","md","lg"],"default":"md"},"align":{"type":"string","enum":["left","center"],"default":"left"},"background":{"type":"string","enum":["default","surface","muted","primary","secondary"],"default":"default"},"minHeight":{"type":"string","enum":["auto","small","medium","screen"],"default":"auto"},"anchorID":{"type":"string","default":""}}},"children":{"mode":"any","min":0},"editor":{"category":"layout","icon":"section","fields":{"settings.width":{"label":"Width","control":"segmented","group":"Layout"},"settings.verticalSpacing":{"label":"Vertical spacing","control":"select","group":"Layout"},"settings.horizontalPadding":{"label":"Horizontal padding","control":"select","group":"Layout"},"settings.align":{"label":"Content alignment","control":"segmented","group":"Style"},"settings.background":{"label":"Background","control":"select","group":"Style"},"settings.minHeight":{"label":"Min height","control":"select","group":"Layout"},"settings.anchorID":{"label":"Anchor ID","control":"text","group":"Advanced"}}}}',
    template = '<section{{ if .Settings.anchorID }} id="{{ .Settings.anchorID }}"{{ end }} class="stratum-section stratum-section-width-{{ .Settings.width }} stratum-section-vspace-{{ .Settings.verticalSpacing }} stratum-section-hpad-{{ .Settings.horizontalPadding }} stratum-section-align-{{ .Settings.align }} stratum-section-bg-{{ .Settings.background }} stratum-section-minh-{{ .Settings.minHeight }}">{{ .Children }}</section>',
    styles = '.stratum-section{margin-inline:auto}.stratum-section-width-content{max-width:var(--st-content-width)}.stratum-section-width-wide{max-width:var(--st-wide-width)}.stratum-section-width-full{max-width:none}.stratum-section-vspace-none{padding-block:0}.stratum-section-vspace-sm{padding-block:clamp(2.5rem,4vw,3rem)}.stratum-section-vspace-md{padding-block:clamp(4rem,6vw,5.5rem)}.stratum-section-vspace-lg{padding-block:clamp(5.5rem,7vw,7rem)}.stratum-section-vspace-xl{padding-block:clamp(7rem,9vw,9rem)}.stratum-section-vspace-2xl{padding-block:clamp(8rem,10vw,11rem)}.stratum-section-hpad-none{padding-inline:0}.stratum-section-hpad-sm{padding-inline:var(--st-space-md)}.stratum-section-hpad-md{padding-inline:var(--st-space-lg)}.stratum-section-hpad-lg{padding-inline:clamp(2rem,5vw,6rem)}.stratum-section-align-left{text-align:left}.stratum-section-align-center{text-align:center}.stratum-section-bg-default{background:transparent}.stratum-section-bg-surface{background:var(--st-color-surface)}.stratum-section-bg-muted{background:var(--st-color-surface-muted)}.stratum-section-bg-primary{background:var(--st-color-primary);color:var(--st-color-primary-contrast)}.stratum-section-bg-secondary{background:var(--st-color-secondary);color:var(--st-color-secondary-contrast)}.stratum-section-minh-auto{min-height:auto}.stratum-section-minh-small{min-height:30vh}.stratum-section-minh-medium{min-height:50vh}.stratum-section-minh-screen{min-height:100vh}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'section' AND version = 1;
