-- 060_restore_image_priority.sql
-- Restore Image priority (auto/high/normal) that was lost in 058 when
-- radius/aspect/fit were added. Keep the new visual settings and drop the
-- legacy eager boolean from the canonical schema; old documents with eager
-- remain tolerated by the renderer (priority fallback).

PRAGMA foreign_keys = ON;

UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["mediaId"],"properties":{"mediaId":{"type":"string","default":""},"alt":{"type":"string","default":""},"caption":{"type":"string","default":""}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["none","left","center"],"default":"none"},"decorative":{"type":"boolean","default":false},"sizes":{"type":"string","default":""},"priority":{"type":"string","enum":["auto","high","normal"],"default":"auto"},"radius":{"type":"string","enum":["none","sm","md","lg"],"default":"none"},"aspect":{"type":"string","enum":["auto","square","4:3","16:9"],"default":"auto"},"fit":{"type":"string","enum":["auto","cover","contain"],"default":"auto"}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"image","fields":{"props.mediaId":{"label":"Image","control":"media","group":"Content"},"props.alt":{"label":"Alt text","control":"text","group":"Accessibility"},"settings.decorative":{"label":"Decorative (no alt)","control":"checkbox","group":"Accessibility"},"props.caption":{"label":"Caption","control":"text","group":"Content"},"settings.align":{"label":"Alignment","control":"segmented","group":"Layout"},"settings.radius":{"label":"Radius","control":"select","group":"Style"},"settings.aspect":{"label":"Aspect","control":"select","group":"Style"},"settings.fit":{"label":"Fit","control":"select","group":"Style"},"settings.sizes":{"label":"Sizes (responsive)","control":"text","group":"Advanced"},"settings.priority":{"label":"Priority","control":"select","group":"Advanced"}}}}',
    template = '{{ $m := media .Props.mediaId }}{{ if $m.Src }}{{ $sizes := "(min-width: 768px) min(100vw, 1200px), 100vw" }}{{ if .Settings.sizes }}{{ $sizes = .Settings.sizes }}{{ end }}<figure class="stratum-image stratum-image-align-{{ .Settings.align }} stratum-image-radius-{{ .Settings.radius }} stratum-image-aspect-{{ .Settings.aspect }} stratum-image-fit-{{ .Settings.fit }}">{{ if $m.WebPSrcSet }}<picture><source type="image/webp" srcset="{{ $m.WebPSrcSet }}" sizes="{{ $sizes }}">{{ end }}<img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}" sizes="{{ $sizes }}"{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ if not .Settings.decorative }}{{ if .Props.alt }}{{ .Props.alt }}{{ else }}{{ $m.Alt }}{{ end }}{{ end }}"{{ if .Priority }} loading="eager" fetchpriority="high" decoding="async"{{ else }} loading="lazy" decoding="async"{{ end }}>{{ if $m.WebPSrcSet }}</picture>{{ end }}{{ if .Props.caption }}<figcaption class="stratum-image-caption">{{ .Props.caption }}</figcaption>{{ end }}</figure>{{ else }}<div class="stratum-image stratum-image-missing" role="img" aria-label="Missing image">Image unavailable</div>{{ end }}',
    styles = '.stratum-image{margin:0}.stratum-image img{display:block;max-width:100%;height:auto}.stratum-image-fit-cover img{object-fit:cover;width:100%;height:100%}.stratum-image-fit-contain img{object-fit:contain}.stratum-image-aspect-square img{aspect-ratio:1/1;object-fit:cover}.stratum-image-aspect-4\:3 img{aspect-ratio:4/3;object-fit:cover}.stratum-image-aspect-16\:9 img{aspect-ratio:16/9;object-fit:cover}.stratum-image-radius-sm img{border-radius:var(--st-radius-sm)}.stratum-image-radius-md img{border-radius:var(--st-radius-md)}.stratum-image-radius-lg img{border-radius:var(--st-radius-lg)}.stratum-image-align-left{text-align:left}.stratum-image-align-left img{margin-inline:0 auto}.stratum-image-align-center{text-align:center}.stratum-image-align-center img{margin-inline:auto}.stratum-image-align-right{text-align:right}.stratum-image-align-right img{margin-inline:auto 0}.stratum-image-caption{margin-top:var(--st-space-xs);font-size:var(--st-small-size,.875rem);color:var(--st-color-text-muted)}.stratum-image-missing{padding:var(--st-space-lg);border:1px dashed var(--st-color-border);text-align:center;color:var(--st-color-text-muted);border-radius:var(--st-radius-md)}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'image' AND version = 1;
