-- 063_gallery_v2_compatibility.sql
-- Fix Gallery versioning: restore v1 as compatibility renderer (hidden) and introduce canonical v2.

PRAGMA foreign_keys = ON;

-- Restore v1 as compatibility: accept all historical keys (gap none/xs/sm/md/lg, aspectRatio, captions, aspect, radius)
-- and hide from new inserts (enabled=0) while remaining renderable.
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","properties":{"images":{"type":"string","default":""}}},"settings":{"type":"object","properties":{"columns":{"type":"integer","enum":[2,3,4],"default":3},"gap":{"type":"string","enum":["none","xs","sm","md","lg"],"default":"sm"},"aspectRatio":{"type":"string","enum":["auto","1:1","4:3","16:9","3:2"],"default":"auto"},"captions":{"type":"boolean","default":false},"aspect":{"type":"string","enum":["auto","square","4:3"],"default":"auto"},"radius":{"type":"string","enum":["none","sm","md","lg"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"gallery","fields":{"props.images":{"label":"Images (legacy)","control":"text","group":"Content"},"settings.columns":{"label":"Columns","control":"segmented","group":"Layout"},"settings.gap":{"label":"Gap","control":"select","group":"Layout"},"settings.aspectRatio":{"label":"Aspect Ratio (legacy)","control":"select","group":"Style"},"settings.aspect":{"label":"Aspect","control":"select","group":"Style"},"settings.radius":{"label":"Radius","control":"select","group":"Style"},"settings.captions":{"label":"Show captions","control":"checkbox","group":"Content"}}}}',
    template = '{{ $ids := split "," .Props.images }}{{ $gap := .Settings.gap }}{{ if not $gap }}{{ $gap = "sm" }}{{ end }}{{ $aspect := .Settings.aspect }}{{ $legacy := .Settings.aspectRatio }}{{ if and (or (not $aspect) (eq $aspect "auto")) $legacy }}{{ if eq $legacy "1:1" }}{{ $aspect = "square" }}{{ else if eq $legacy "16:9" }}{{ $aspect = "16:9" }}{{ else if eq $legacy "3:2" }}{{ $aspect = "3:2" }}{{ else if eq $legacy "4:3" }}{{ $aspect = "4:3" }}{{ end }}{{ end }}{{ if not $aspect }}{{ $aspect = "auto" }}{{ end }}{{ $radius := .Settings.radius }}{{ if not $radius }}{{ $radius = "none" }}{{ end }}{{ if $ids }}<div class="stratum-gallery stratum-gallery-cols-{{ .Settings.columns }} stratum-gallery-gap-{{ $gap }} stratum-gallery-radius-{{ $radius }}{{ if ne $aspect "auto" }} stratum-gallery-aspect-{{ $aspect }}{{ end }}">{{ range $ids }}{{ $m := media . }}{{ if $m.Src }}<figure class="stratum-gallery-item">{{ if $m.WebPSrcSet }}<picture><source type="image/webp" srcset="{{ $m.WebPSrcSet }}" sizes="(min-width:992px) 33vw,(min-width:640px) 50vw,100vw">{{ end }}<img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}" sizes="(min-width:992px) 33vw,(min-width:640px) 50vw,100vw"{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ $m.Alt }}" loading="lazy" decoding="async">{{ if $m.WebPSrcSet }}</picture>{{ end }}</figure>{{ end }}{{ end }}</div>{{ else }}{{ if .Context.IsPreview }}<div class="stratum-gallery stratum-gallery-empty">No images selected</div>{{ end }}{{ end }}',
    styles = '.stratum-gallery{display:grid;gap:var(--st-space-sm)}.stratum-gallery-cols-2{grid-template-columns:repeat(2,1fr)}.stratum-gallery-cols-3{grid-template-columns:repeat(3,1fr)}.stratum-gallery-cols-4{grid-template-columns:repeat(4,1fr)}.stratum-gallery-gap-none{gap:0}.stratum-gallery-gap-xs{gap:var(--st-space-xs)}.stratum-gallery-gap-sm{gap:var(--st-space-sm)}.stratum-gallery-gap-md{gap:var(--st-space-md)}.stratum-gallery-gap-lg{gap:var(--st-space-lg)}.stratum-gallery-item{margin:0;overflow:hidden;border-radius:var(--st-radius-md)}.stratum-gallery-radius-none .stratum-gallery-item{border-radius:0}.stratum-gallery-radius-sm .stratum-gallery-item{border-radius:var(--st-radius-sm)}.stratum-gallery-radius-md .stratum-gallery-item{border-radius:var(--st-radius-md)}.stratum-gallery-radius-lg .stratum-gallery-item{border-radius:var(--st-radius-lg)}.stratum-gallery-aspect-square .stratum-gallery-item{aspect-ratio:1/1}.stratum-gallery-aspect-4\:3 .stratum-gallery-item{aspect-ratio:4/3}.stratum-gallery-aspect-16\:9 .stratum-gallery-item{aspect-ratio:16/9}.stratum-gallery-aspect-3\:2 .stratum-gallery-item{aspect-ratio:3/2}.stratum-gallery-item img{display:block;width:100%;height:100%;object-fit:cover}.stratum-gallery-empty{padding:var(--st-space-lg);border:1px dashed var(--st-color-border);text-align:center;color:var(--st-color-text-muted)}@media(max-width:640px){.stratum-gallery-cols-3,.stratum-gallery-cols-4{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.stratum-gallery{grid-template-columns:1fr}}',
    enabled = 0,
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'gallery' AND version = 1;

-- Canonical Gallery v2: typed array, clean semantic settings
INSERT INTO block_definitions (
    id, namespace, name, version, display_name, description, schema_json,
    renderer_type, template, styles, source, enabled, created_at, updated_at
)
VALUES (
    'core-gallery-v2', 'core', 'gallery', 2, 'Gallery', 'A responsive grid of images from the Media Library.',
    '{"schemaVersion":1,"props":{"type":"object","required":["images"],"properties":{"images":{"type":"array","items":{"type":"string"},"default":[]}}},"settings":{"type":"object","properties":{"columns":{"type":"integer","enum":[2,3,4],"default":3},"gap":{"type":"string","enum":["sm","md","lg"],"default":"md"},"aspect":{"type":"string","enum":["auto","square","4:3"],"default":"auto"},"radius":{"type":"string","enum":["none","sm","md","lg"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"media","icon":"gallery","fields":{"props.images":{"label":"Images","control":"media-multiple","group":"Content"},"settings.columns":{"label":"Columns","control":"segmented","group":"Layout"},"settings.gap":{"label":"Gap","control":"select","group":"Layout"},"settings.aspect":{"label":"Aspect","control":"select","group":"Style"},"settings.radius":{"label":"Radius","control":"select","group":"Style"}}}}',
    'template',
    '{{ $ids := .Props.images }}{{ if $ids }}<div class="stratum-gallery stratum-gallery-cols-{{ .Settings.columns }} stratum-gallery-gap-{{ .Settings.gap }} stratum-gallery-radius-{{ .Settings.radius }}{{ if ne .Settings.aspect "auto" }} stratum-gallery-aspect-{{ .Settings.aspect }}{{ end }}">{{ range $ids }}{{ $m := media . }}{{ if $m.Src }}<figure class="stratum-gallery-item">{{ if $m.WebPSrcSet }}<picture><source type="image/webp" srcset="{{ $m.WebPSrcSet }}" sizes="(min-width:992px) 33vw,(min-width:640px) 50vw,100vw">{{ end }}<img src="{{ $m.Src }}"{{ if $m.SrcSet }} srcset="{{ $m.SrcSet }}" sizes="(min-width:992px) 33vw,(min-width:640px) 50vw,100vw"{{ end }}{{ if $m.Width }} width="{{ $m.Width }}"{{ end }}{{ if $m.Height }} height="{{ $m.Height }}"{{ end }} alt="{{ $m.Alt }}" loading="lazy" decoding="async">{{ if $m.WebPSrcSet }}</picture>{{ end }}</figure>{{ end }}{{ end }}</div>{{ else }}{{ if .Context.IsPreview }}<div class="stratum-gallery stratum-gallery-empty">No images selected</div>{{ end }}{{ end }}',
    '.stratum-gallery{display:grid;gap:var(--st-space-md)}.stratum-gallery-cols-2{grid-template-columns:repeat(2,1fr)}.stratum-gallery-cols-3{grid-template-columns:repeat(3,1fr)}.stratum-gallery-cols-4{grid-template-columns:repeat(4,1fr)}.stratum-gallery-gap-sm{gap:var(--st-space-sm)}.stratum-gallery-gap-md{gap:var(--st-space-md)}.stratum-gallery-gap-lg{gap:var(--st-space-lg)}.stratum-gallery-item{margin:0;overflow:hidden;border-radius:var(--st-radius-md)}.stratum-gallery-radius-none .stratum-gallery-item{border-radius:0}.stratum-gallery-radius-sm .stratum-gallery-item{border-radius:var(--st-radius-sm)}.stratum-gallery-radius-md .stratum-gallery-item{border-radius:var(--st-radius-md)}.stratum-gallery-radius-lg .stratum-gallery-item{border-radius:var(--st-radius-lg)}.stratum-gallery-aspect-square .stratum-gallery-item{aspect-ratio:1/1}.stratum-gallery-aspect-4\:3 .stratum-gallery-item{aspect-ratio:4/3}.stratum-gallery-item img{display:block;width:100%;height:100%;object-fit:cover}.stratum-gallery-empty{padding:var(--st-space-lg);border:1px dashed var(--st-color-border);text-align:center;color:var(--st-color-text-muted)}@media(max-width:640px){.stratum-gallery-cols-3,.stratum-gallery-cols-4{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.stratum-gallery{grid-template-columns:1fr}}',
    'core', 1, unixepoch(), unixepoch()
)
ON CONFLICT(namespace, name, version) DO UPDATE SET
    display_name=excluded.display_name,
    description=excluded.description,
    schema_json=excluded.schema_json,
    renderer_type=excluded.renderer_type,
    template=excluded.template,
    styles=excluded.styles,
    source=excluded.source,
    enabled=excluded.enabled,
    updated_at=excluded.updated_at;
