-- 075_stack_2xl.sql
-- Extend Stack to support 2xl gap for editorial rhythm (major internal groups 48-72).
-- Historical documents using xs/sm/md/lg/xl remain valid; new value is additive.
PRAGMA foreign_keys = ON;

UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","properties":{}},"settings":{"type":"object","properties":{"direction":{"type":"string","enum":["vertical","horizontal"],"default":"vertical"},"gap":{"type":"string","enum":["none","xs","sm","md","lg","xl","2xl"],"default":"md"},"align":{"type":"string","enum":["start","center","end","stretch"],"default":"stretch"},"justify":{"type":"string","enum":["start","center","end","between"],"default":"start"},"wrap":{"type":"boolean","default":false},"width":{"type":"string","enum":["auto","full"],"default":"auto"}}},"children":{"mode":"any","min":0},"editor":{"category":"layout","icon":"stack","fields":{"settings.direction":{"label":"Direction","control":"segmented","group":"Layout"},"settings.gap":{"label":"Gap","control":"select","group":"Layout"},"settings.align":{"label":"Cross axis","control":"segmented","group":"Layout"},"settings.justify":{"label":"Main axis","control":"segmented","group":"Layout"},"settings.wrap":{"label":"Wrap","control":"checkbox","group":"Layout"},"settings.width":{"label":"Width","control":"segmented","group":"Layout"}}}}',
    template = '<div class="stratum-stack stratum-stack-dir-{{ .Settings.direction }} stratum-stack-gap-{{ .Settings.gap }} stratum-stack-align-{{ .Settings.align }} stratum-stack-justify-{{ .Settings.justify }}{{ if .Settings.wrap }} stratum-stack-wrap{{ end }}{{ if eq .Settings.width "full" }} stratum-stack-full{{ end }}">{{ .Children }}</div>',
    styles = '.stratum-stack{display:flex}.stratum-stack-dir-vertical{flex-direction:column}.stratum-stack-dir-horizontal{flex-direction:row}.stratum-stack-gap-none{gap:0}.stratum-stack-gap-xs{gap:var(--st-space-xs)}.stratum-stack-gap-sm{gap:var(--st-space-sm)}.stratum-stack-gap-md{gap:var(--st-space-md)}.stratum-stack-gap-lg{gap:var(--st-space-lg)}.stratum-stack-gap-xl{gap:var(--st-space-xl)}.stratum-stack-gap-2xl{gap:var(--st-space-2xl)}.stratum-stack-align-start{align-items:flex-start}.stratum-stack-align-center{align-items:center}.stratum-stack-align-end{align-items:flex-end}.stratum-stack-align-stretch{align-items:stretch}.stratum-stack-justify-start{justify-content:flex-start}.stratum-stack-justify-center{justify-content:center}.stratum-stack-justify-end{justify-content:flex-end}.stratum-stack-justify-between{justify-content:space-between}.stratum-stack-wrap{flex-wrap:wrap}.stratum-stack-full{width:100%}@media(max-width:640px){.stratum-stack-dir-horizontal{flex-direction:column}}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'stack' AND version = 1;
