-- 077_section_gutter_fix.sql
-- Section v2 horizontalPadding=md must map to canonical Theme gutter var(--st-gutter)
-- so Header, Footer and Section inner align to same horizontal rhythm.
PRAGMA foreign_keys = ON;

UPDATE block_definitions SET
    styles = '.stratum-section--v2{width:100%;max-width:none;margin-inline:0;box-sizing:border-box}.stratum-section--v2.stratum-section-vspace-none{padding-block:0}.stratum-section--v2.stratum-section-vspace-sm{padding-block:clamp(20px,2.5vw,28px)}.stratum-section--v2.stratum-section-vspace-md{padding-block:clamp(36px,4vw,56px)}.stratum-section--v2.stratum-section-vspace-lg{padding-block:clamp(56px,6vw,80px)}.stratum-section--v2.stratum-section-vspace-xl{padding-block:clamp(80px,8vw,112px)}.stratum-section--v2.stratum-section-minh-auto{min-height:auto}.stratum-section--v2.stratum-section-minh-small{min-height:30vh}.stratum-section--v2.stratum-section-minh-medium{min-height:50vh}.stratum-section--v2.stratum-section-minh-screen{min-height:100vh;display:flex;flex-direction:column;justify-content:center}.stratum-section--v2.stratum-section-bg-default{background:transparent}.stratum-section--v2.stratum-section-bg-surface{background:var(--st-color-surface)}.stratum-section--v2.stratum-section-bg-muted{background:var(--st-color-surface-muted)}.stratum-section--v2.stratum-section-bg-primary{background:var(--st-color-primary);color:var(--st-color-primary-contrast)}.stratum-section--v2.stratum-section-bg-primary .stratum-heading{color:var(--st-color-primary-contrast)}.stratum-section--v2.stratum-section-bg-primary .stratum-text{color:var(--st-color-primary-contrast)}.stratum-section--v2.stratum-section-bg-primary .stratum-button-primary{background:var(--st-color-primary-contrast);color:var(--st-color-primary)}.stratum-section--v2.stratum-section-bg-primary .stratum-button-primary:hover{background:color-mix(in srgb,var(--st-color-primary-contrast) 88%,var(--st-color-primary));color:var(--st-color-primary)}.stratum-section__inner{width:100%;margin-inline:auto;box-sizing:border-box;min-width:0}.stratum-section__inner.stratum-section-width-content{max-width:var(--st-content-width)}.stratum-section__inner.stratum-section-width-wide{max-width:var(--st-wide-width)}.stratum-section__inner.stratum-section-width-full{max-width:none}.stratum-section__inner.stratum-section-hpad-none{padding-inline:0}.stratum-section__inner.stratum-section-hpad-sm{padding-inline:var(--st-space-md)}.stratum-section__inner.stratum-section-hpad-md{padding-inline:var(--st-gutter)}.stratum-section__inner.stratum-section-hpad-lg{padding-inline:clamp(2rem,5vw,6rem)}.stratum-section-align-left{text-align:left}.stratum-section-align-center{text-align:center}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'section' AND version = 2;
