-- 086_inline_editable_fields.sql — M5A basic inline editing
-- Adds inline:true/inlineMode:plain to heading/text/button label and
-- instruments editor-only field markers (data-stratum-editor-field).
-- Public output remains clean (no markers when Editor disabled).

-- Heading @2: inline richtext plain + editor marker
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["text"],"properties":{"text":{"type":"object","default":{"version":1,"content":[]},"required":["version","content"],"properties":{"version":{"type":"integer","enum":[1]},"content":{"type":"array","items":{"type":"object","required":["text"],"properties":{"text":{"type":"string"},"marks":{"type":"array","items":{"type":"object","required":["type"],"properties":{"type":{"type":"string","enum":["bold","italic","strike","code","link"]},"href":{"type":"string"}}}}}}}}},"level":{"type":"integer","enum":[1,2,3,4,5,6],"default":2}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["left","center","right"],"default":"left"},"visualSize":{"type":"string","enum":["auto","sm","md","lg","xl","2xl","display"],"default":"auto"},"tone":{"type":"string","enum":["default","muted","primary"],"default":"default"},"maxWidth":{"type":"string","enum":["normal","wide","none"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"text","icon":"heading","summaryFields":["props.text"],"fields":{"props.text":{"label":"Text","control":"richtext","inline":true,"inlineMode":"plain","placeholder":"Add heading\u2026"},"props.level":{"label":"Level","control":"select"},"settings.align":{"label":"Alignment","control":"segmented","group":"Style"},"settings.visualSize":{"label":"Visual size","control":"segmented","group":"Style"},"settings.tone":{"label":"Tone","control":"select","group":"Style"},"settings.maxWidth":{"label":"Max width","control":"segmented","group":"Layout"}}}}',
    template = '{{ if integerEquals .Props.level 1 }}<h1 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Add heading…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</h1>{{ else if integerEquals .Props.level 3 }}<h3 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Add heading…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</h3>{{ else if integerEquals .Props.level 4 }}<h4 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Add heading…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</h4>{{ else if integerEquals .Props.level 5 }}<h5 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Add heading…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</h5>{{ else if integerEquals .Props.level 6 }}<h6 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Add heading…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</h6>{{ else }}<h2 class="stratum-heading stratum-align-{{ .Settings.align }} stratum-heading-size-{{ .Settings.visualSize }} stratum-tone-{{ .Settings.tone }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Add heading…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</h2>{{ end }}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'heading' AND version = 2;

-- Text @2: inline richtext plain + editor marker
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["text"],"properties":{"text":{"type":"object","default":{"version":1,"content":[]},"required":["version","content"],"properties":{"version":{"type":"integer","enum":[1]},"content":{"type":"array","items":{"type":"object","required":["text"],"properties":{"text":{"type":"string"},"marks":{"type":"array","items":{"type":"object","required":["type"],"properties":{"type":{"type":"string","enum":["bold","italic","strike","code","link"]},"href":{"type":"string"}}}}}}}}}}},"settings":{"type":"object","properties":{"align":{"type":"string","enum":["left","center","right"],"default":"left"},"tone":{"type":"string","enum":["default","muted","primary"],"default":"default"},"size":{"type":"string","enum":["sm","md","lg"],"default":"md"},"maxWidth":{"type":"string","enum":["narrow","normal","wide","none"],"default":"none"}}},"children":{"mode":"none"},"editor":{"category":"text","icon":"text","summaryFields":["props.text"],"fields":{"props.text":{"label":"Text","control":"richtext","inline":true,"inlineMode":"plain","placeholder":"Start typing\u2026"},"settings.align":{"label":"Alignment","control":"segmented","group":"Style"},"settings.tone":{"label":"Tone","control":"select","group":"Style"},"settings.size":{"label":"Size","control":"segmented","group":"Style"},"settings.maxWidth":{"label":"Max width","control":"segmented","group":"Layout"}}}}',
    template = '<p class="stratum-text stratum-align-{{ .Settings.align }} stratum-tone-{{ .Settings.tone }} stratum-text-size-{{ .Settings.size }} stratum-maxw-{{ .Settings.maxWidth }}">{{ if .Context.Editor }}<span data-stratum-editor-field="props.text" data-placeholder="Start typing…">{{ richText .Props.text }}</span>{{ else }}{{ richText .Props.text }}{{ end }}</p>',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'text' AND version = 2;

-- Button @1: inline plain label + editor marker with empty placeholder handling
UPDATE block_definitions SET
    schema_json = '{"schemaVersion":1,"props":{"type":"object","required":["label","url"],"properties":{"label":{"type":"string","default":"Button"},"url":{"type":"string","default":"#"}}},"settings":{"type":"object","properties":{"variant":{"type":"string","enum":["primary","secondary","outline","ghost","link"],"default":"primary"},"size":{"type":"string","enum":["sm","md","lg"],"default":"md"},"width":{"type":"string","enum":["auto","full"],"default":"auto"},"align":{"type":"string","enum":["left","center","right"],"default":"left"},"openInNewTab":{"type":"boolean","default":false}}},"children":{"mode":"none"},"editor":{"category":"design","icon":"button","fields":{"props.label":{"label":"Label","control":"text","inline":true,"inlineMode":"plain","placeholder":"Add button label\u2026"},"props.url":{"label":"URL","control":"text"},"settings.variant":{"label":"Variant","control":"segmented","group":"Style"},"settings.size":{"label":"Size","control":"segmented","group":"Style"},"settings.width":{"label":"Width","control":"segmented","group":"Layout"},"settings.align":{"label":"Alignment","control":"segmented","group":"Layout"},"settings.openInNewTab":{"label":"Open in new tab","control":"checkbox","group":"Link"}}}}',
    template = '{{ $url := safeURL .Props.url }}{{ if .Context.Editor }}<div class="stratum-btn-wrap stratum-align-{{ .Settings.align }}{{ if eq .Settings.width "full" }} stratum-btn-wrap-full{{ end }}">{{ if and .Props.label $url }}<a class="stratum-button stratum-button-{{ .Settings.variant }} stratum-button-size-{{ .Settings.size }}{{ if eq .Settings.width "full" }} stratum-button-full{{ end }}" href="{{ $url }}"{{ if .Settings.openInNewTab }} target="_blank" rel="noopener noreferrer"{{ end }}><span data-stratum-editor-field="props.label" data-placeholder="Add button label…">{{ .Props.label }}</span></a>{{ else }}<a class="stratum-button stratum-button-{{ .Settings.variant }} stratum-button-size-{{ .Settings.size }}{{ if eq .Settings.width "full" }} stratum-button-full{{ end }} stratum-button--placeholder" href="{{ if $url }}{{ $url }}{{ else }}#{{ end }}"{{ if .Settings.openInNewTab }} target="_blank" rel="noopener noreferrer"{{ end }}><span data-stratum-editor-field="props.label" data-placeholder="Add button label…">{{ .Props.label }}</span></a>{{ end }}</div>{{ else }}{{ if and .Props.label $url }}<div class="stratum-btn-wrap stratum-align-{{ .Settings.align }}{{ if eq .Settings.width "full" }} stratum-btn-wrap-full{{ end }}"><a class="stratum-button stratum-button-{{ .Settings.variant }} stratum-button-size-{{ .Settings.size }}{{ if eq .Settings.width "full" }} stratum-button-full{{ end }}" href="{{ $url }}"{{ if .Settings.openInNewTab }} target="_blank" rel="noopener noreferrer"{{ end }}>{{ .Props.label }}</a></div>{{ end }}{{ end }}',
    updated_at = unixepoch()
WHERE namespace = 'core' AND name = 'button' AND version = 1;
